### ISSUE TITLE
[0.2.6] Mouse not grabbing on QEMU GTK

### ISSUE THREAD

**Issue by rdbo** [riverwm/river#1003]
OS: Alpine Linux (edge)
river 0.2.6

I've been trying to use QEMU with the GTK UI, and normally it grabs the input so that I can use the mouse on the VM.
But that's not what's happening: I click the QEMU window, and even though it says that the input is grabbed, I can move the mouse around freely on my regular desktop, and no input is given to the VM (the mouse does not move, or very rarely, moves a little bit).
When using QEMU SDL, the mouse moves as expected (even though the pointer speed is not the same, but probably unrelated).

**Comment by adamcstephens** [comment]
You may want to test this using master since it has diverged quite a bit.

**Comment by ifreund** [comment]
Yeah, the pointer constraints implementation has been completely rewritten since 0.2, so testing with master branch would be a good idea.

However, are you sure that GTK QEMU even supports pointer constraints on wayland? Does it work on any compositor? A WAYLAND_DEBUG=1 log of the program running would tell for sure.

**Comment by rdbo** [comment]
Hey, forgot about this
I tried building master before making the issue, but failed. Now I tried again and managed to build.
In the built version of river, the cursor moves, but not at the same speed at the OS cursor (like in the SDL mode), but also, the cursor doesn't grab
I added the `WAYLAND_DEBUG=1` to the QEMU command and it shows a bunch of output.
You mentioned pointer constraints, so I found this and looks useful:
```
[2722912.950] wl_registry@2.global(13, "zwlr_output_manager_v1", 4)
[2722912.965] wl_registry@2.global(14, "zwlr_output_power_manager_v1", 1)
[2722912.981] wl_registry@2.global(15, "ext_idle_notifier_v1", 1)
[2722912.998] wl_registry@2.global(16, "zwp_pointer_constraints_v1", 1)
[2722913.021] wl_registry@2.global(17, "zwp_relative_pointer_manager_v1", 1)
[2722913.039] wl_registry@2.global(18, "zwlr_virtual_pointer_manager_v1", 2)
[2722913.056] wl_registry@2.global(19, "zwp_virtual_keyboard_manager_v1", 1)
```

**Comment by ifreund** [comment]
Could you please share the full WAYLAND_DEBUG=1 log of e.g. opening up a QEMU GTK window, moving the cursor across it, and closing it? Just a snippet isn't very useful.

I have a suspicion that QEMU's GTK wayland backend doesn't support pointer constraints.

**Comment by ifreund** [comment]
Looks like I was correct and GTK doesn't support this feature: https://gitlab.gnome.org/GNOME/gtk/-/issues/5313
