### ISSUE TITLE
River Fais to Start on Alpine

### ISSUE THREAD

**Issue by VehementHam** [riverwm/river#1005]
#### This is what I have done after the install
Set up repositories
```
vi /etc/repositories
```
The file should read:
```
http://dl-cdn.alpinelinux.org/alpine/edge/main
http://dl-cdn.alpinelinux.org/alpine/edge/community
http://dl-cdn.alpinelinux.org/alpine/edge/testing
```
Update and upgrade
```
apk update && update
```
Set up eudev
```
setup-devd udev
```
Install the mesa-gallium drivers
```
apk add mesa-dri-gallium
```
Install River and the documentation
```
apk add river river-doc
```
Install Foot
```
apk add foot
```
Start the seat daemon
```
rc-update add seatd
rc-service seatd start
```
Add the user to the nessessary groups
```
adduser <user> seat
adduser <user> input
adduser <user> video
```
Copy the sample config into the config directory
```
install -Dm0755 /usr/share/doc/river/examples/init -t /home/<user>/.config/river
```
Now edit the /home/<user>/vehementham/.profile to read the following
```
if [ -z "$XDG_RUNTIME_DIR" ]; then
	XDG_RUNTIME_DIR="/tmp/$(id -u)-runtime-dir"

	mkdir -pm 0700 "$XDG_RUNTIME_DIR"
	export XDG_RUNTIME_DIR
fi
```
Now install the nessessary packages to enter a GUI session
```
apk add xwayland... still unsure what deps are mising
```
Now logout of root. Login as the user.
```
river
```
#### Error
```
Wayland serverIME_DIR is invalid or not set in the environment
```

**Comment by ifreund** [comment]
the error message is cut off, you can collect the full message by redirecting river's stderr to a file.

It certainly seems like XDG_RUNTIME_DIR didn't get set properly though, you should check to make sure it's correct after logging in but before starting river.

**Comment by nmeum** [comment]
I suppose you don't have xwayland installed?

See: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/61376

**Comment by VehementHam** [comment]
![image](https://github.com/riverwm/river/assets/75701545/9264a6f5-188f-4a92-83d8-23abdd62d98e)
![image](https://github.com/riverwm/river/assets/75701545/5a3111f2-d665-4c17-8632-f4afc8a54f4d)

**Comment by VehementHam** [comment]
I don't understand how `$XDG_RUNTIME_DIR` is not set. I followed [these](
![image](https://github.com/riverwm/river/assets/75701545/3e0774d0-39ee-4945-81ed-a45c6c1b2b75)
) instructions.  I also tried rebooting.

**Comment by novakne** [comment]
Have you checked that the directory is really created after login, before trying to launch river,  for example zsh do not source `~/.profile`

**Comment by VehementHam** [comment]
I get the same error after sourcing `.profile`.

**Comment by VehementHam** [comment]
I manually created the directory, and I still get the error.

**Comment by ifreund** [comment]
As the error message says, the XDG_RUNTIME_DIR environment variable is either invaild or not set. There's no bug on river's side here, the issue is with your configuration. I recommend running `echo $XDG_RUNTIME_DIR` before trying to start river to check that your configuration attempts have worked.

Alternatively, consider using a distro that robustly handles this for you.

**Comment by VehementHam** [comment]
When `$XDG_RUNTIME_DIR`, is set, I still get the exact same error. I have confirmed with `echo $XDG_RUNTIME_DIR`.

**Comment by ifreund** [comment]
> When `$XDG_RUNTIME_DIR`, is set, I still get the exact same error. I have confirmed with `echo $XDG_RUNTIME_DIR`.

According to libwayland it is either not set or not an absolute path:
```c
		runtime_dir = getenv("XDG_RUNTIME_DIR");
		if (!runtime_dir || runtime_dir[0] != '/') {
			wl_log("error: XDG_RUNTIME_DIR is invalid or not set in"
			       " the environment\n");

			/* to prevent programs reporting
			 * "failed to add socket: Success" */
			errno = ENOENT;
			return -1;
		}
```
