### ISSUE TITLE
Support Running Without XWayland For All Builds

### ISSUE THREAD

**Issue by VehementHam** [riverwm/river#1007]
The issue with the current system is that precompiled binaries, installed by a package manager, will always require XWayland. I personally do not need XWayland, and therefore it is a hugely bloated to have to use. My purposal is that instead of having a build flag for XWayland support, include XWayland support for all builds, and make it so that it is not required to run River. 

Compiling from source would require a compiler which is also added bloat.

**Comment by ifreund** [comment]
This is already implemented on river's master branch, see the `-no-xwayland` option.

**Comment by VehementHam** [comment]
I don't have that option. My version is `0.2.6`.

**Comment by novakne** [comment]
Yes because as said above this is in master so either you can wait for 0.3 or build the master branch
