### ISSUE TITLE
Map keys to other keys

### ISSUE THREAD

**Issue by jbirnick** [riverwm/river#1010]
For me it's annoying to use the arrow keys, because my right hand needs to move so far.

That's why I want to map `Alt + {h,j,k,l}` to the arrow keys. (Or is there a common other mapping?)

How to achieve that with the river config?

**Comment by itshog** [comment]
I'd suggest you look at [wtype](https://github.com/atx/wtype), [ydotool](https://github.com/ReimuNotMoe/ydotool) or [swhkd](https://github.com/waycrate/swhkd) for these kind of things

**Comment by ifreund** [comment]
Yeah, I think tools using the virtual keyboard protocol like wtype are a fine way to support this use-case for now at least.
