### ISSUE TITLE
Screen suspend looses wlr-randr screen scaling setting

### ISSUE THREAD

**Issue by hholst80** [riverwm/river#1018]
Happens on river 0.2.6-1 (Artix Linux)

After the screen has been resurrected from sleep mode the randr scaling is reset to 1.0.

Is this supposed to happen?  I cannot remember Sway loosing the setting.  Hyprland never was able to come back from a screen sleep without killing Hyprland so there I do not know.

**Comment by ifreund** [comment]
So far the approach to persistent output configuration for river has been a long-running daemon such as [kanshi](https://sr.ht/~emersion/kanshi/) or [way-displays](https://github.com/alex-courtis/way-displays).

This may change eventually but I don't have plans to do so at the moment.
