### ISSUE TITLE
Glitchy And Slow On Alpine

### ISSUE THREAD

**Issue by VehementHam** [riverwm/river#1019]
### [issue.webm](https://github.com/riverwm/river/assets/75701545/643700ec-e152-49c0-ac27-fc2a1810a3b6)
My steps:
Install Alpine.
```
Mirror=https://dl-cdn.alpinelinux.org/alpine/edge/main/
Window Manager: River
Text editor: vis
WWW Client: Lynx
Terminal Emulator: Foot
Launcher: fuzzel
Bar: Yambar
Shell: ASH
Font: Mononoki Nerd Font

Set up repositories
	vi /etc/repositories
The file should read:
	http://dl-cdn.alpinelinux.org/alpine/edge/main
	http://dl-cdn.alpinelinux.org/alpine/edge/community
	http://dl-cdn.alpinelinux.org/alpine/edge/testing
Update and upgrade
	apk update && update
Remove Doas
	apk del doas
Set up eudev
	setup-devd udev
Install the mesa-gallium drivers
	apk add mesa-dri-gallium
Install River documentation (optional)
	apk add river-doc

Install River

Option 1: From APK
	apk add river
	apk add xwayland (optional)

Option 2: From source (Not working)
Install packages that will be used to build river
	apk add git zig pkgconfig
Install river dependencies
	apk add wayland wayland-dev wayland-protocols wlroots wlroots-dev libxkbcommon libxkbcommon-dev libevdev libevdev-dev pixman pixman-dev
Clone river
	mkdir /home/<user>/.Git
	cd /home/<user>/.Git
	git clone https://github.com/riverwm/river.git
	git submodule update --init
Revert to the latest version
	git reset --hard v0.2.6
Build river
	zig build -Doptimize=ReleaseSafe --prefix /usr/local/bin install
Remove unneded packages (optional)
	apk del git zig pkgconfig 

Install Foot
	apk add foot
Start the seat daemon
	rc-update add seatd
	rc-service seatd start
Add the user to the nessessary groups
	adduser <user> seat
	adduser <user> input
	adduser <user> video
Install Git
	apk add git
Crate directories
	cd /home/<user>
	mkdir -p .Git .config .local/bin
Change to the /home/<user>/.Git directory
	cd /home/<user>/.Git
Clone the git repo for this guide
	git clone https://git.disroot.org/oink/minimal-but-usable.git
Remove Git
	apk del git
Change to the directory.
	cd minimal-but-usable
Copy config files
	cp .profile /home/<user>/
	cp .ashrc /home/<user>/
	mkdir -p /home/<user>/.local/bin/
	cp lynx /home/<user>/.local/bin/
	cp -r vis river foot yambar fuzzel /home/<user>/.config/
Create the wallpaper folder
	mkdir -p /home/<user>/.local/share/wallpapers/
Copy the wallpaper over
	cp Wallpapers/wallpaper.png /home/<user>/.local/share/wallpapers/
Now install the nessessary packages to enter a GUI session
	apk add xwayland... still unsure what deps are mising
Install packages
	apk add lynx vis fuzzel fastfetch yambar imv wlr-randr wbg
Install a font 
	apk add font-mononoki-nerd
Now give the user ownership of the files
	chown -R <user>:<user> /home/<user>/

Now logout of root. Login as the user.
Run River
	river
```

**Comment by VehementHam** [comment]
`.log`:
``
info: initializing server
info(wlroots): [libseat] [libseat/libseat.c:73] Seat opened with backend 'seatd'
info(wlroots): [libseat] [libseat/backend/seatd.c:212] Enabling seat
info(wlroots): [backend/session/session.c:109] Successfully loaded libseat session
info(wlroots): [backend/backend.c:220] Found 1 GPUs
info(wlroots): [backend/drm/backend.c:200] Initializing DRM backend for /dev/dri/card0 (virtio_gpu)
info(wlroots): [backend/drm/drm.c:253] Found 1 DRM CRTCs
info(wlroots): [backend/drm/drm.c:180] Found 1 DRM planes
info(wlroots): [backend/headless/backend.c:68] Creating headless backend
info(wlroots): [render/egl.c:201] Supported EGL client extensions: EGL_EXT_client_extensions EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_explicit_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_EXT_platform_xcb EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
libEGL warning: egl: failed to create dri2 screen
error(wlroots): [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to create screen"
libEGL warning: egl: failed to create dri2 screen
error(wlroots): [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to create screen"
libEGL warning: NEEDS EXTENSION: falling back to kms_swrast
info(wlroots): [render/egl.c:347] Using EGL 1.5
info(wlroots): [render/egl.c:348] Supported EGL display extensions: EGL_ANDROID_blob_cache EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_EXT_query_reset_notification_strategy EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_context_flush_control EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image_base EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_gl_interop EGL_MESA_image_dma_buf_export EGL_MESA_query_driver 
info(wlroots): [render/egl.c:350] Supported EGL device extensions: EGL_EXT_device_drm EGL_EXT_device_drm_render_node
info(wlroots): [render/egl.c:352] EGL vendor: Mesa Project
info(wlroots): [render/gles2/renderer.c:718] Creating GLES2 renderer
info(wlroots): [render/gles2/renderer.c:719] Using OpenGL ES 3.2 Mesa 24.0.2
info(wlroots): [render/gles2/renderer.c:720] GL vendor: Mesa
info(wlroots): [render/gles2/renderer.c:721] GL renderer: llvmpipe (LLVM 17.0.6, 256 bits)
info(wlroots): [render/gles2/renderer.c:722] Supported GLES2 extensions: GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_filter_anisotropic GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_EXT_draw_instanced GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_type_2_10_10_10_REV GL_NV_conditional_render GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_NV_pack_subimage GL_NV_texture_barrier GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_OES_viewport_array GL_ANGLE_pack_reverse_row_order GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_EXT_occlusion_query_boolean GL_EXT_robustness GL_EXT_texture_rg GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_APPLE_sync GL_EXT_draw_buffers GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_NV_generate_mipmap_sRGB GL_NV_pixel_buffer_object GL_OES_depth_texture_cube_map GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_color_buffer_float GL_EXT_debug_label GL_EXT_sRGB_write_control GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_group_vote GL_EXT_shader_implicit_conversions GL_EXT_shader_integer_mix GL_EXT_tessellation_point_size GL_EXT_tessellation_shader GL_ANDROID_extension_pack_es31a GL_ARM_shader_framebuffer_fetch_depth_stencil GL_EXT_base_instance GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_copy_image GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_gpu_shader5 GL_EXT_polygon_offset_clamp GL_EXT_primitive_bounding_box GL_EXT_render_snorm GL_EXT_shader_io_blocks GL_EXT_texture_border_clamp GL_EXT_texture_buffer GL_EXT_texture_cube_map_array GL_EXT_texture_norm16 GL_EXT_texture_view GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_NV_image_formats GL_NV_shader_noperspective_interpolation GL_OES_copy_image GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_gpu_shader5 GL_OES_primitive_bounding_box GL_OES_sample_shading GL_OES_sample_variables GL_OES_shader_io_blocks GL_OES_shader_multisample_interpolation GL_OES_tessellation_point_size GL_OES_tessellation_shader GL_OES_texture_border_clamp GL_OES_texture_buffer GL_OES_texture_cube_map_array GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_OES_texture_view GL_EXT_blend_func_extended GL_EXT_buffer_storage GL_EXT_float_blend GL_EXT_geometry_point_size GL_EXT_geometry_shader GL_EXT_texture_filter_minmax GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_OES_EGL_image_external_essl3 GL_OES_geometry_point_size GL_OES_geometry_shader GL_OES_shader_image_atomic GL_EXT_clear_texture GL_EXT_clip_cull_distance GL_EXT_disjoint_timer_query GL_EXT_texture_compression_s3tc_srgb GL_MESA_shader_integer_functions GL_EXT_clip_control GL_EXT_color_buffer_half_float GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_texture_compression_bptc GL_EXT_texture_mirror_clamp_to_edge GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_EXT_shader_framebuffer_fetch_non_coherent GL_EXT_texture_shadow_lod GL_MESA_framebuffer_flip_y GL_EXT_depth_clamp GL_EXT_texture_query_lod GL_MESA_sampler_objects GL_MESA_bgra 
info(wlroots): [xwayland/server.c:108] Starting Xwayland on :0
info(wlroots): [backend/drm/drm.c:1338] Scanning DRM connectors on /dev/dri/card0
info(wlroots): [backend/drm/drm.c:1389] Found connector 'Virtual-1'
info(wlroots): [backend/drm/drm.c:1414] 'Virtual-1' connected
info(wlroots): [backend/drm/drm.c:1230] Physical size: 320x200
info(wlroots): [backend/drm/drm.c:1287] Detected modes:
info(wlroots): [backend/drm/drm.c:1315]   1280x800 @ 74.994 Hz (preferred)
info(wlroots): [backend/drm/drm.c:1315]   5120x2160 @ 50.000 Hz 
info(wlroots): [backend/drm/drm.c:1315]   4096x2160 @ 50.000 Hz 
info(wlroots): [backend/drm/drm.c:1315]   3840x2160 @ 60.000 Hz 
info(wlroots): [backend/drm/drm.c:1315]   3840x2160 @ 59.940 Hz 
info(wlroots): [backend/drm/drm.c:1315]   3840x2160 @ 50.000 Hz 
info(wlroots): [backend/drm/drm.c:1315]   1920x1440 @ 60.000 Hz 
info(wlroots): [backend/drm/drm.c:1315]   2560x1080 @ 50.000 Hz 
info(wlroots): [backend/drm/drm.c:1315]   1856x1392 @ 59.995 Hz 
info(wlroots): [backend/drm/drm.c:1315]   1792x1344 @ 60.000 Hz 
info(wlroots): [backend/drm/drm.c:1315]   2048x1152 @ 60.000 Hz 
info(wlroots): [backend/drm/drm.c:1315]   1920x1200 @ 59.885 Hz 
info(wlroots): [backend/drm/drm.c:1315]   1920x1080 @ 60.000 Hz 
info(wlroots): [backend/drm/drm.c:1315]   1920x1080 @ 50.000 Hz 
info(wlroots): [backend/drm/drm.c:1315]   1600x1200 @ 60.000 Hz 
info(wlroots): [backend/drm/drm.c:1315]   1680x1050 @ 59.954 Hz 
info(wlroots): [backend/drm/drm.c:1315]   1400x1050 @ 59.978 Hz 
info(wlroots): [backend/drm/drm.c:1315]   1280x1024 @ 60.020 Hz 
info(wlroots): [backend/drm/drm.c:1315]   1440x900 @ 59.887 Hz 
info(wlroots): [backend/drm/drm.c:1315]   1280x960 @ 60.000 Hz 
info(wlroots): [backend/drm/drm.c:1315]   1360x768 @ 60.015 Hz 
info(wlroots): [backend/drm/drm.c:1315]   1280x768 @ 59.870 Hz 
info(wlroots): [backend/drm/drm.c:1315]   1024x768 @ 60.004 Hz 
info(wlroots): [backend/drm/drm.c:1315]   800x600 @ 60.317 Hz 
info(wlroots): [backend/drm/drm.c:1315]   640x480 @ 60.000 Hz 
info(wlroots): [backend/drm/drm.c:1315]   640x480 @ 59.940 Hz 
info(wlroots): [backend/drm/drm.c:1447] connector Virtual-1: Requesting modeset
info(wlroots): [backend/drm/drm.c:586] connector Virtual-1: Modesetting with 1280x800 @ 74.994 Hz
info: running init executable '/home/vehementham/.config/river/init'
info: running server
Refusing to try glamor on llvmpipe
EGL setup failed, disabling glamor
Failed to initialize glamor, falling back to sw
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
info(wlroots): [backend/drm/drm.c:586] connector Virtual-1: Modesetting with 1920x1080 @ 60.000 Hz
info: main.c:356: 1.1.0
info: fcft.c:338: fcft: 3.1.8 +graphemes +runs +svg(nanosvg) -assertions
info: fcft.c:377: fontconfig: 2.15.0, freetype: 2.13.2, harfbuzz: 8.3.0, utf8proc: 2.9.0 (Unicode 15.1.0)
info: fcft.c:848: /usr/share/fonts/mononoki-nerd/MononokiNerdFontMono-Regular.ttf: size=12.00pt/12.50px, dpi=75.00
info: fcft.c:848: /usr/share/fonts/mononoki-nerd/MononokiNerdFontMono-Regular.ttf: size=17.28pt/18.00px, dpi=75.00
info: fcft.c:848: /usr/share/fonts/mononoki-nerd/MononokiNerdFontMono-Regular.ttf: size=15.36pt/16.00px, dpi=75.00
info: bar/wayland.c:558: monitor: Virtual-1: 1920x1080+0+0 (320x200mm)
 err: modules/network.c:1150: wlp3s0: failed to find interface
info: main.c:200: output: Red Hat, Inc. QEMU Monitor (1920x1080, scale=1)
info: main.c:108: render: 1920x1080 (scaled from 3840x2160)
warn: wayland.c:1509: fractional scaling not available
warn: wayland.c:1512: no server-side cursors available, falling back to client-side cursors
warn: wayland.c:1523: text input interface not implemented by compositor; IME will be disabled
info: main.c:1154: version: 1.9.2 +cairo +png +svg(librsvg) -assertions
info: config.c:1475: loading configuration from /home/vehementham/.config/fuzzel/fuzzel.ini
info: wayland.c:2018: Virtual-1: 1920x1080+0x0@60Hz QEMU Monitor 14.86" scale=1 PPI=160x154 (physical) PPI=160x154 (logical), DPI=148.28
info: fcft.c:338: fcft: 3.1.8 +graphemes +runs +svg(nanosvg) -assertions
info: fcft.c:377: fontconfig: 2.15.0, freetype: 2.13.2, harfbuzz: 8.3.0, utf8proc: 2.9.0 (Unicode 15.1.0)
info: fcft.c:848: /usr/share/fonts/mononoki-nerd/MononokiNerdFontMono-Regular.ttf: size=12.00pt/24.71px, dpi=148.28
info: shutting down
info: main.c:378: aborted: Terminated (15)
(EE) failed to read Wayland events: Broken pipe
 err: wayland.c:1405: failed to read events from the Wayland socket: Broken pipe
 err: wayland.c:1977: failed to roundtrip Wayland display: Broken pipe
 err: wayland.c:1977: failed to roundtrip Wayland display: Broken pipe
 err: wayland.c:1977: failed to roundtrip Wayland display: Broken pipe
warn: terminal.c:1802: slave exited with signal 1 (Hangup)
 err: wayland.c:1942: failed to flush wayland socket: Broken pipe
 ```

**Comment by ifreund** [comment]
As can be read in the river log, river falls back to the llvmpipe software rendered because the install graphics drivers do not support the required features.

I suppose you're missing some package or other, check the dependencies of the alpine river package.

**Comment by VehementHam** [comment]
Somehow my VM hardware was changed

I wasted an hour trying to figure out what package I was missing.
