### ISSUE TITLE
Layer surfaces can overflow onto neighboring outputs.

### ISSUE THREAD

**Issue by LordMZTE** [riverwm/river#1028]
The screenshot below shows waybar getting too wide to fit on one monitor and overflowing onto the neighboring output. River should crop it instead.
![screenshot](https://github.com/riverwm/river/assets/28735087/f02b3cf0-cf1d-47b9-a7a4-4082e591cae8)

**Comment by ifreund** [comment]
Fixed in 6491310e12c3d6bb91b7d9cd456bd3d83695b985
