### ISSUE TITLE
suspend and scaling resets to 1.0

### ISSUE THREAD

**Issue by hholst80** [riverwm/river#1030]
Idk why but after a screen suspend River looses the scaling and it resets to 1.0 scaling.

I set it with 

```
[I] root@neo ~
# wlr-randr --output DP-1 --scale 3
```

**Comment by MaxVerevkin** [comment]
To have persistent settings, you can use a tool like [`kanshi`](https://git.sr.ht/~emersion/kanshi/refs).

**Comment by ifreund** [comment]
Duplicate of #1018 as well...
