### ISSUE TITLE
Feature request: Action to change focused view based on direction

### ISSUE THREAD

**Issue by revsuine** [riverwm/river#1032]
The implementation would probably just be to expand `focus-view next|previous` to allow `up|right|down|left` as options. This would be a really helpful QoL feature which is available on Sway and Hyprland (I know River is not trying to be either, but it's something that I'm used to with tiling WMs/Wayland compositors).

An equivalent extension for the `swap` action would also be really useful.

**Comment by Leon-Plickat** [comment]
This is already implemented.

**Comment by revsuine** [comment]
Apologies, I didn't see it in the riverctl manpage. Is it just `focus-view up|right|down|left`?

**Comment by Leon-Plickat** [comment]
If you do not see it in your local man page, then you will not have this available. I think this feature was added after the currently latest release. A new release will be tagged soon, otherwise you can build from source to get this.
