### ISSUE TITLE
Implement idle-inhibit-unstable-v1

### ISSUE THREAD

**Issue by RasmusBertell** [riverwm/river#199]
Waybar keeps crashing when clicking the idle inhibitor module. On sway it seems to work so that leads me to believe it is a problem with river not implementing the [idle inhibit protocol](https://github.com/wayland-project/wayland-protocols/blob/master/unstable/idle-inhibit/idle-inhibit-unstable-v1.xml).

I'm fine if you decide to not support the protocol, but could there be a little note about it in the wiki, especially since waybar is a recommended software?

**Comment by ifreund** [comment]
Waybar crashing when the compositor does not advertise a global it expects is a waybar bug. It should probably print a helpful error message instead.

I think river should definitely support the idle inhibit protocol, it's just that nobody's gotten around to implementing it yet.

**Comment by RasmusBertell** [comment]
I'll open a waybar issue about this also then.

I'd love to help implement this, but unfortunately I have zero knowledge on zig

**Comment by antaxiom** [comment]
Any movement on getting this done? I'd like the idle_inhibitor on waybar as well. Separately, is there any other way to control the idle behavior, I haven't tested this, but I'm not sure what would happen if I just left a movie running (though I haven't seen it go to sleep on its own yet).

**Comment by edrex** [comment]
Cage impl, for reference: https://github.com/Hjdskes/cage/pull/22/commits/17497f10c2a02fd06bed4999e58373b7b61b25c6
