### ISSUE TITLE
Implement full damage tracking

### ISSUE THREAD

**Issue by ifreund** [riverwm/river#206]
This should make river use significantly fewer resources and save everyone's laptop batteries.

See: https://emersion.fr/blog/2019/intro-to-damage-tracking/

Consider reviving https://github.com/swaywm/wlroots/pull/1552 or implementing something similar in wlroots.

Edit: The next wlroots release (0.15.0) will bring a scene graph API with full damage tracking support. The current plan is to use this instead of implementing full damage tracking manually in river.

**Comment by ifreund** [comment]
Basic yes/no damage tracking has now been implemented and river will not redraw anything if nothing has changed. However river will still redraw the entire output every time anything does change.

This issue now track implementing "full" damage tracking to improve this.

**Comment by fine2006** [comment]
Newbie here, how significant of a difference does yes/no damage tracking makes? And how much would full damage tracking improve it?

**Comment by novakne** [comment]
@fine2006 a big one, first it hides a bug where the output had freeze, and it improves cpu usage, so better battery life
Full damage tracking will "only" improve cpu usage AFAIK

**Comment by fine2006** [comment]
That's good news for me! I can use river on my laptop now! But on my old desktop I would wait because any cpu is precious.

**Comment by Leon-Plickat** [comment]
> has there been any progress on this?

Yes, but actually not from rivers side. wlroots is currently gaining a scene-graph API, which allows us to let wlroots take care of some of the rendering details river currently handles itself. Damage tracking is among these.

**Comment by metalune1** [comment]
oh that's great, so that'll mean that soon basically all the WMs will have damage tracking?

**Comment by Leon-Plickat** [comment]
> oh that's great, so that'll mean that soon basically all the WMs will
> have damage tracking?

At least all that are using the scene graph API.

But keep in mind that the vast majority of wlroots based compositors
seem to be abandoned projects, so I would not hold my breath for any
of them.

**Comment by metalune1** [comment]
> At least all that are using the scene graph API. 
ah I see
> But keep in mind that the vast majority of wlroots based compositors seem to be abandoned projects, so I would not hold my breath for any of them.
yeah, not like I cared about any of them besides of this one

**Comment by chcore** [comment]
Will this improve the performance of VNC applications? I notice that wayvnc uses a negligible amount of CPU when I'm running sway, vs 30-40% of a core when running river. This is when no VNC clients are even connected.

**Comment by Ristovski** [comment]
Are there any news about this? From what I could gather, wlroots now seems to have the required API for this?

**Comment by ifreund** [comment]
> Are there any news about this? From what I could gather, wlroots now seems to have the required API for this?

The scene graph API on wlroots master branch has come a long way and made many changes since 0.15 was released. I don't plan on switch river over to the scene graph API until 0.16 is out and we upgrade to that.
