### ISSUE TITLE
Better window matching for filters

### ISSUE THREAD

**Issue by Leon-Plickat** [riverwm/river#289]
Currently both the float and CSD filter use only the app-id to match windows, which is insufficient. Consider for example the case of the dev-tools window (which I want floating) of a browser (which I want tiled), which both per spec have the same app-id, and therefore will be treated identical by the filters.

I propose that filters should also be capable to match windows based on the view title.

**Comment by ThreeFx** [comment]
How far do we want to take this? In the end we are probably talking about a filter DSL (who knows what crazy setups are required for some special applications).

Adding a matching option for window titles would help with day-to-day work (mainly getting the Firefox media sharing window to float nicely). I'm imagining something like this:

```
# matches the app-id 'asdf' for backwards compatibility
riverctl float-filter-add asdf

# matches the app-id 'asdf'
riverctl float-filter-add app-id:asdf

# matches the title 'asdf' exactly
riverctl float-filter-add title:asdf
```

Alternatively the title could be an optional argument

```
# matches app-id 'asdf' AND title 'qwer'
riverctl float-filter-add asdf qwer
```

What do you think?

**Comment by Leon-Plickat** [comment]
> How far do we want to take this?

Not far at all.

The plan is to eventually outsource filters to external clients.

**Comment by ThreeFx** [comment]
Sounds good, I was wanting to start hacking on some wayland stuff anyway :)
