### ISSUE TITLE
Some small issues

### ISSUE THREAD

**Issue by mortezadadgar** [riverwm/river#333]
I have faced some issues that I think is worth mentioning here

- river failed to parse configuration in `$HOME/.config/river/init` I ended up editing `/etc/river/init`
- is there any way to open programs in specific tags like open firefox in tag 2, it's the closest command I found but didn't open firefox `riverctl map normal Mod4+Shift F spawn-tagmask $((1 << 2)) firefox`
- Sometimes touchpad get unresponsive after opening a link in firefox with native wayland support (I didn't test xwayland)
- any way to switch back to the last visited tag like `bspc desktop -f last` in bspwm

**Comment by novakne** [comment]
> river failed to parse configuration in $HOME/.config/river/init I ended up editing /etc/river/init

Is your `init` executable?

> is there any way to open programs in specific tags like open firefox in tag 2

Not yet, see #201 

> Sometimes touchpad get unresponsive after opening a link in firefox with native wayland support (I didn't test xwayland)

Never encouter this issue, maybe if you can get  a log

> any way to switch back to the last visited tag like bspc desktop -f last in bspwm

I don't think so

**Comment by mortezadadgar** [comment]
@novakne yeah the config file wasn't executable
here's the log I got with log level 6 https://del.dog/eckasakynu.txt

**Comment by novakne** [comment]
I don't see anything unusual in these logs, is that a log after the touchpad get unresponsive?

**Comment by mortezadadgar** [comment]
> I don't see anything unusual in these logs, is that a log after the touchpad get unresponsive?

yes I enabled natural and tap, opened firefox searched in github, opened a link without changing the cursor position I can't scroll down or up with touchpad (I hope it's clear enough lol)

**Comment by novakne** [comment]
hmm I can't reproduce this issue

Though if all your others questions are answered I think you should open an other issue just for this issue, reposting your log and the description

**Comment by ifreund** [comment]
> yes I enabled natural and tap, opened firefox searched in github, opened a link without changing the cursor position I can't scroll down or up with touchpad (I hope it's clear enough lol)

Running firefox with `WAYLAND_DEBUG=1 firefox` would be useful to determine if this is a river or firefox issue.

**Comment by Leon-Plickat** [comment]
Can't scroll? Probably a focusing issue with Firefox. It is not uncommon. IIRC older versions of Firefox sometimes forgot that your cursor is over a scrollable element when you load a new site.

As a workaround, try focusing a different window and then firefox again.

**Comment by mortezadadgar** [comment]
> Can't scroll? Probably a focusing issue with Firefox. It is not uncommon. IIRC older versions of Firefox sometimes forgot that your cursor is over a scrollable element when you load a new site.
> 
> As a workaround, try focusing a different window and then firefox again.

I'm running firefox 89.0-1 and focusing to a different window didn't solve the problem


> > yes I enabled natural and tap, opened firefox searched in github, opened a link without changing the cursor position I can't scroll down or up with touchpad (I hope it's clear enough lol)
> 
> Running firefox with `WAYLAND_DEBUG=1 firefox` would be useful to > determine if this is a river or firefox issue.

https://del.dog/zuresypuph
I stoped firefox as long as I faced the touchpad unresponsiveness

**Comment by nagy135** [comment]
I would really appreaciate that feature where you could *select previously focused workspace in bspwm*. It would translate here as previously remembered state of tags. Its really crucial because workflow where you do something and need to briefly check something on other ws and go back is quite often (at least for me)

**Comment by ifreund** [comment]
This issue has no clear focus, I believe that all the bugs here have been fixed at this point. If anyone cares strongly about any of the feature requests, feel free to open a new issue.
