### ISSUE TITLE
[Feature request] possibility for set-cursor-warp on-focus-change

### ISSUE THREAD

**Issue by user18130814200115-2** [riverwm/river#349]
This would warp the cursor to the center of the focused window (client) whenever the focus changes.
Extra points if a function of the type `riverctl center-cursor {window,output}` can be used.

This feature is useful if you move around a lot with your keyboard, and afterwards need to use your mouse. Es specially id you have focus-follows-cursor on at either strict or normal.

For reference, there is sway's `mouse_warping container`.
Or [this custom script I wrote for sway](https://github.com/user18130814200115-2/swayscrips/tree/main/mousetofocus).

Thank you for all the hard work <3

**Comment by novakne** [comment]
Implemented in 8036ae2bd179d66f6317e5c7cbd388e88877d9f7
