### ISSUE TITLE
Protocols: implement input-method-v2

### ISSUE THREAD

**Issue by user18130814200115-2** [riverwm/river#351]
Implementing input-method-v2 would open river up to alternative input managers such as `fcitx` or `wlpinyin`.
This would allow users to write in other languages (primarily languages that do not use the western alphabet)

**Comment by HeavyRain266** [comment]
You can setup your input language through `XKB_DEFAULT_LAYOUT="layout code" river` and this will allow you to use e.g.. cyrylic, arabic and other alphabets.

**Comment by user18130814200115-2** [comment]
> You can setup your input language through `XKB_DEFAULT_LAYOUT="layout code" river` and this will allow you to use e.g.. cyrylic, arabic and other alphabets.

Good point, I am aware of this, but it is unrelated to my request.

Alternate input methods are distinct from alternate layouts in that you can for instance write in pinyin (mandarin Chinese using the latin alphabet) and turn it into Chinese characters.

For instance, I would type `ta` to get `他`.
This cannot be done with regular layouts because to get the character multiple inputs need to be given.
Furthermore, for many of these input methods it is the case that many possible characters exist for a given input. 
The above mentioned input `ta` in pinyin can mean (among other things) `他, 她, 它, 塔 or 牠`

**Comment by hillyu** [comment]
looks like this protocol is essential for fcitx5 to work properly, and much needed.

**Comment by glyh** [comment]
Don't want to be a killjoy but this one is actually not good-to-have, but a crucial part for most of cjk users...

**Comment by ifreund** [comment]
This has been implemented in https://github.com/riverwm/river/pull/859

Support for input method popups is tracked by https://github.com/riverwm/river/issues/946
