### ISSUE TITLE
[feature request][river-layout] Tag parameter for user_command event

### ISSUE THREAD

**Issue by Leon-Plickat** [riverwm/river#383]
It is not guaranteed that the next layout_demand event after a user_command
event has the same active tags. As an example, a user could trigger a
user_command while no views are visible, then switch to a different tag set
which has active tags.

Obviously the active tags of the previous layout_demand may also be differently.

Therefore, it is currently impossible to correctly implement a layout generator
which has user commands apply only to the currently active tag set.

Simply adding the currently active tags as a parameter to the user_command event
would solve this. It would add effectively no complexity serverside and even
reduce complexity and improve correctnes client-side in the case of layouts with
per-tag configuration of any kind.

**Comment by Leon-Plickat** [comment]
Layouts with per-tag values are IMO a valid use-case and river should support external clients wanting to do this in a correct, non-hacky fashion.

**Comment by Leon-Plickat** [comment]
If I am not mistaken, this would only require a new version of the interface, not the entire protocol, so it is non-breaking.

**Comment by novakne** [comment]
So this issue can be closed
