### ISSUE TITLE
[feature request] Event mappings (hooks)

### ISSUE THREAD

**Issue by minego** [riverwm/river#385]
I would really like the ability to map an action to be performed based on events, such as a new window being opened or switching focus to a new window.

My goal is to be able to configure a script that should be run when the currently active window changes, which could then change some settings based on the currently active application.

This would likely also require a command to ask river what the active application is. My goal is to get xkeysnail like functionality by running a command when an application is selected to set a keyboard layout so that I can have application specific keyboard layouts.

**Comment by Leon-Plickat** [comment]
See also #52.

**Comment by Leon-Plickat** [comment]
> This would likely also require a command to ask river what the active application is.

The title of the focused application can be fetched with the river-status protocol extension. In the future we may want to link a foreign toplevel handle instead.

**Comment by ifreund** [comment]
My long term vision is to move all window management logic out of the compositor process into a separate window manager process. This would involve exposing these kinds of events to the window manager process.

I have no plans to expose this kind of information except as part of making that transition possible though
