### ISSUE TITLE
Fractional scaling makes compositing not pixel-perfect

### ISSUE THREAD

**Issue by lucat1** [riverwm/river#434]
As you can see in the screenshot I've attached below these is a 1 pixel tall line between the `foot` terminal and `waybar`. My screen configuration is as follows: `1920x1080 scaling 1.25` and the background is se to `#ffffff`, which is why the line is pitch white. I have tested this behaviour without either `waybar` or the `1.25` scaling and this bug dissapears. Note that waybar is tall `22px` wile `-view-padding` and `-outer-padding` for rivertile are set to 0. On the screen you can see two instances of `foot` open, using a font size of `16px` (if that matters).
I'm sure there could be more configurations which cause this kind of breaking behaviour, that's just what I'm running currently. I don't have any familiarity with the codebase but I can suppose this could be a rounding error somewhere in the `rivertile` positioning logic. Please let me know if you need any additional information to reproduce this bug.

![09-21-21--10-59-41](https://user-images.githubusercontent.com/29304787/134142974-af647601-5159-4a6f-b19c-2c9edef16e5f.png)

**Comment by Leon-Plickat** [comment]
> scaling 1.25

Fractional scaling and pixel-perfect rendering are incompatible.

When doing fractional scaling, in reality the next highest integer scaling is used for rendering and everything is then down-scaled when compositing. Inconsistencies like this have to be expected. You have a window which by the very nature of things has a width and height in pixels, integers. Scaling of `1.25` means it actually renders at scale `2`, which obviously is still integer, but during compositing the scale-2-buffer gets scaled to `0.625` times its size. Only if you are really lucky does this result in an integer, so there is some rounding done here when getting it on screen. So yes, this is a rounding error, but not one we can realistically do much about.

This simply is the very nature of fractional scaling, even if clients were aware of it. The big proprietary operating systems use a lot of magic, smoke and mirrors to pretend that fractional scaling works well, but it really does not. Maybe in the future we could investigating adding some of that magic to river as well, but **a)** it falls in the same category as eye-candy so it's simply not a priority right now and **b)** perhaps the wlroots scene graph API will give it to us for free when river eventually switches to that, so any effort to work on this now is wasted.

**Comment by lucat1** [comment]
I understand why this is not high priority currently and that it's an aftermath of using fractional scaling. I don't have any interest in rushing this as it's not a deal breaker for me, just wanted to point out that this doesn't happen in sway with the same exact configuration. Could be the entirely different implementation or that new wlroots feature, can't really tell.

**Comment by worldpe** [comment]
Fractional scaling cant be pixel perfect by definition

**Comment by ifreund** [comment]
I think this has been fixed for a while. If anyone can reproduce on master please drop a comment.
