### ISSUE TITLE
[feature request] Could `focus-follows-cursor` detect output change?

### ISSUE THREAD

**Issue by nwg-piotr** [riverwm/river#448]
Hi,

I first installed river 2 days ago, to test how [my stuff](https://github.com/nwg-piotr/nwg-shell) behaves here, and I must say you're doing a great job!

As I use my mouse quite heavily on a triple-headed setup, `focus-follows-cursor normal` fits my needs best. It would be even more convenient if pointing an empty output (with no surface on it) changed focus as well. Otherwise I need to put the mouse down and switch outputs using the keyboard. Could it be changed?

**Comment by nwg-piotr** [comment]
BTW: if there existed a command to focus outputs by name (not just `left` | `right` | `next` | `previous`), the problem could be temporarily resolved with a script...

**Comment by keshto** [comment]
Would be nice to have a click option for changing the focus of the output, as I have the tendency to use my other monitor to put my cursor out of the way of the working output.

**Comment by Leon-Plickat** [comment]
@keshto outputs can already be focused via mouse click. I don't think that patch made it into the last release though.

**Comment by keshto** [comment]
@Leon-Plickat that explains that since I am using 0.1.2. I guess I could build from master if it is stable enough and test or just wait and open an issue if I don't see it in next release. Thanks for the info :+1:

**Comment by edrex** [comment]
I'd like this too, and would be willing to implement it as a first patch.

**Comment by Leon-Plickat** [comment]
@edrex you may want to wait with that patch until the scene-graph port is complete.

**Comment by larstiq** [comment]
> @edrex you may want to wait with that patch until the scene-graph port is complete.

I didn't want to wait so implemented https://github.com/riverwm/river/pull/956/
