### ISSUE TITLE
Feature request: Ability to hide the cursor (akin to unclutter)

### ISSUE THREAD

**Issue by sagehane** [riverwm/river#453]
I couldn't find this feature on river, while sway seems to have it under `hide_cursor` here: https://github.com/swaywm/sway/blob/master/sway/sway-input.5.scd#seat-configuration.

I also couldn't find any wm-agnostic tool for this, so I figured it needs to be supported on river's side?

**Comment by Leon-Plickat** [comment]
Yes, this is something a compositor needs to implement itself, since a Wayland client can only set the cursor image when the pointer is over on of its surfaces.

Should not be too hard to implement, basically just hooking into the idle system.

**Comment by tiosgz** [comment]
> Tested on `0.2.0-dev-a8491eb` from archlinux aur.

Can you try git master? I think e0246c04104fad95573f07c3bfc4547c7ce1d116 could fix it.

**Comment by ifreund** [comment]
Indeed, that commit fixed the issue described. I now see that I forgot to close this issue.
