### ISSUE TITLE
DMENU ignores keystrokes if no Xwayland clients are present and in focus.

### ISSUE THREAD

**Issue by Shinyzenith** [riverwm/river#455]
Description: dmenu doesn't accept input unless a wayland client exists on the screen which is actively checking for keystrokes. Example, if dmenu_run is being executed on a tag where no other app is open, none of the keystrokes will be accepted, works when any other app is opened ( example, terminal ) .
( Sorry for incorrect terminology, if any)

Any possible workaround? ( dmenu works flawlessly under sway so I assume one already exists. )

**Comment by HeavyRain266** [comment]
If you want native dmenu replacement, I suggest you to use [bemenu](https://github.com/Cloudef/bemenu) instead of bothering with launcher programs running through XWayland.

**Comment by Shinyzenith** [comment]
I know but bemenu has some missing features, hence this gh issue.

**Comment by Shinyzenith** [comment]
I'm trying to fix this by getting the surface and then calling wlr.XdgSurface.fromWlrSurface but I keep getting this error, if anyone can provide a fix that would be amazing,

**Comment by Shinyzenith** [comment]
![image](https://user-images.githubusercontent.com/60808802/158050094-2c0ce502-3124-4abf-9a74-9283857b2f65.png)

![image](https://user-images.githubusercontent.com/60808802/158050097-db2863d3-70f9-46ea-ab9c-be352024e0bd.png)

**Comment by Shinyzenith** [comment]
https://github.com/riverwm/river/pull/569 should hopefully close this issue.
