### ISSUE TITLE
[feature request] assign view to active tags when moving it to a different output

### ISSUE THREAD

**Issue by aldrenean** [riverwm/river#457]
Under current behavior, sending a window to my second monitor keeps it on the same tag, regardless of which tag my second monitor was displaying. So if I'm on tag 2 on my primary and tag 1 on my secondary, I have to switch to tag 2 on my secondary to retrieve the window I just sent over. 

This behavior is not nonsensical, but it isn't how any other tiling WM I've used has worked. Generally if I'm sending a window to another output it's because I want it visible on that output immediately. I assume it would be more complex to first get the tag of the destination output, but I personally would much prefer that behavior. Or maybe there's a way to set it up with riverctl and I'm just missing it?

**Comment by Leon-Plickat** [comment]
Currently there is no way around this behaviour. However it will be resolved eventually as a side effect of either #357 or #447.

**Comment by rickalex21** [comment]
Any workarounds for this? It is a bit of a hassle to have to switch tags every time I
move a window from one monitor to the next.

**Comment by NickHastings** [comment]
I think it is already implemented. See https://github.com/riverwm/river/pull/811

**Comment by ifreund** [comment]
Indeed it is :)

**Comment by rickalex21** [comment]
Thanks, I had a feeling it had something to do with `current-tags`. For anyone else reading
this it's:

```sh
riverctl map normal $mod+Control Semicolon send-to-output -current-tags next
```
