### ISSUE TITLE
[Question] How to use the NVIDIA proprietary driver when running river?

### ISSUE THREAD

**Issue by uncomfyhalomacro** [riverwm/river#462]
From my understanding, sway does this by `WLR_DRM_DEVICES=/dev/dri/card1` or similar. does river have something like this?

**Comment by novakne** [comment]
Properitary drivers are not and never will be officially supported by river,  if it works it works, but no there is nothing like this in river and it's not planned.

**Comment by uncomfyhalomacro** [comment]
Alright closing this issue. Thanks for clarifying! :100:

**Comment by ifreund** [comment]
Like sway, river use wlroots and therefore wlroots environment variables will affect river: https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/docs/env_vars.md
