### ISSUE TITLE
[feature request] First empty tag

### ISSUE THREAD

**Issue by mitinarseny** [riverwm/river#463]
It would be cool if there is a `riverctl` command that would return first tag with no windows in it. It would make it possible to implement "set first empty tag for current window" in the following scenario:
1. suppose I am now have tag `1` displayed (so I can see all the windows with this tag)
2. the focus in on the window `A`, but there is also window `B` with the same tag (so I can see both tiled)
3. I hit a key binding that moves `A` (since it is the current window) to first unused tag (that would be `2`)

Although, It does not well combines with the fact that a tag is not a workspace. So, in my setup I use `1 << ($i - 1)` with `for i in $(seq 1 9)`, with means that the actual first my from my perspective is `1`, the second is `2`, third is `4` and so on... Thus, "first unused tag" if currently used are only `1` and `2`, would not be `4`, but `3`, which is `1 | 2`...  
Anyway, maybe you have some ideas, how it could be implemented then?

**Comment by user18130814200115-2** [comment]
This one liner should do the trick:
`raw=$(ristate -vt & sleep 0.2 && kill $! ); printf "%s" "$raw" | grep -o "[0-9]" | sort -n | awk '{for(i=p+1; i<$1; i++) print i} {p=$1}'`
It uses [ristate](https://gitlab.com/snakedye/ristate) and some standard utils (printf, grep, sort, head and awk).

In other words, this does not need to be added to river(ctl)

With some more math, you can get the command you requested
`raw=$(ristate -vt & sleep 0.2 && kill $! ); riverctl set-view-tags $(printf "%s" "$raw" | grep -o "[0-9]" | sort -n  | awk '{for(i=p+1; i<$1; i++) print i} {p=$1}' | xargs -i_ printf "2^(_-1)\n" | bc)`

Let me know if you have any problems with it
