### ISSUE TITLE
fresh void musl installation errors

### ISSUE THREAD

**Issue by 5sanon** [riverwm/river#467]
got the xbps package on a fresh void musl installation, and im getting these errors. it is probably because i am dumb, but i have no idea how to fix this. first one was ran without sudo and i sudoed the second one because it said permission denied. i even reinstalled and was getting the same errors. 
![error](https://user-images.githubusercontent.com/82610174/141661363-0c78a62d-0f7d-414a-8577-42271fe2cf0a.jpg)
sorry for the blur, phone cameras idk.
i installed seatd because it was in the errors and i linked it in /var/service, didnt fix anything :/

**Comment by deepaknegilachu** [comment]
Ssanon do u have mesa-dri installed

**Comment by 5sanon** [comment]
> Ssanon do u have mesa-dri installed

I did not, but now that I do running ` $ river` does the same but running `$ sudo river` gives me this
`error: AddSocketFailednd/server.c:99 WAYLAND_SOCKET=24 Xwayland :3 -rootless -terminate -core -listenfd 22 -listenfd 23 -wm 26w_lod GL_INTEL_blackhole_render GL_MESA_framebuffer_flip_y GL_NV_compute_shader_derivatives GL_EXT_demote_to_help`
then it gives a whole bunch of lines that look similar like
`???:?:?: 0x55954336e881 in ??? (???)`

**Comment by TWB0109** [comment]
I think I have a solution...
* Install elogind (and acpid) with:
    ```
    # xbps-install -S elogind acpid
    # ln -s /etc/sv/{elogind,acpid} /var/service/
    # sv up {elogind,acpid}
    # sv start {elogind,acpid}
    ```
* Reboot if needed
* Run ```river``` in tty

**Comment by 5sanon** [comment]
> I think I have a solution...
> 
>     * Install elogind (and acpid) with:
>       ```
>       # xbps-install -S elogind acpid
>       # ln -s /etc/sv/{elogind,acpid} /var/service/
>       # sv up {elogind,acpid}
>       # sv start {elogind,acpid}
>       ```
> 
>     * Reboot if needed
> 
>     * Run `river` in tty
> 
> 
> I'm using glibc, but I suppose this will also work for you

Didn't seem to work, sadly.

**Comment by deepaknegilachu** [comment]
wait

**Comment by deepaknegilachu** [comment]
u need elogind polkit xorg-xserver-wayland river foot fuzzel river mesa-dri .
then enable polkit and dbus 
and then type river in tty1

**Comment by 5sanon** [comment]
> u need elogind polkit xorg-xserver-wayland river foot fuzzel river mesa-dri . then enable polkit and dbus and then type river in tty1

It worked! I was missing polkitd
