### ISSUE TITLE
Layer surface vertical wrap around

### ISSUE THREAD

**Issue by dnkl** [riverwm/river#468]
I'm seeing what I consider to be weird behavior when mapping many layer surfaces, at increasing y-coordinates. A picture says, perhaps not all, but a lot:
![many-layer-surfaces](https://user-images.githubusercontent.com/14031526/141826843-3900927c-04ba-48b3-95b9-385e390e48ca.png)

This is fnott showing notifications. I've triggered them in order ("one", "two", "three", ...). Note how the bottom one is "ten", and then there's **one** final notification at the top, "eleven". It looks like it has wrapped around.

After "eleven", I also create the notifications "twelve" and "thirteen". These are closed (`layer_surface.close()`) before being mapped. I.e. river rejects their first configuring commit.

I don't mind the surfaces being closed immediately. That's what I would expect to happen anyway. But the one that wraps around doesn't look intentional?

(note that the latest release of fnott isn't great at handling this situation - running latest master is advised if you want to use fnott for testing).

River version: 0.2.0-dev-f3475c5

**Comment by dnkl** [comment]
(edited issue and added river version)

**Comment by Leon-Plickat** [comment]
While the wrap-around is no doubt a bug, I also think the layer shell makes no guarantees w.r.t. surface ordering, so clients should not depend on the stacking order of the surfaces matching the order in which they were created.

**Comment by dnkl** [comment]
> I also think the layer shell makes no guarantees w.r.t. surface ordering, so clients should not depend on the stacking order of the surfaces matching the order in which they were created.

Correct. I position them by setting the layer surface's anchors and margins.

**Comment by Leon-Plickat** [comment]
>  I position them by setting the layer surface's anchors and margins.

Sounds a bit hacky TBH, but that explains why the notifications past eleven are not shown (see e6f11fc5d2e6c876839be0b684fcb82f2692503d).

**Comment by dnkl** [comment]
> Sounds a bit hacky TBH

It is. But there aren't that many alternatives.

The only other alternative I'm aware of is using a single surface for all notifications, and render the margins between the notifications fully transparent, combined with setting input regions.

**Comment by Leon-Plickat** [comment]
> It is. But there aren't that many alternatives.

If you ever want to create and standardize a better shell for desktop widgets, you'll definitely have my support :D

**Comment by ifreund** [comment]
@dnkl would you mind testing #481 if you still have the same fnott config? I didn't take the time to figure out the proper fnott settings to reproduce this.

**Comment by dnkl** [comment]
Tested quickly, and appears to work. Thanks!
