### ISSUE TITLE
Unable to change keyboard layout

### ISSUE THREAD

**Issue by LukeDotDev** [riverwm/river#469]
Hi! 
So i've been trying to change the keyboard layout for awhile now, and I cant seem to make it persistent, I've tried loadkeys, setxkbmap, and so on, but I cant figure out what the correct way is. loadkeys works in TTY but not in the WM, is there some documentation I've missed? If so how would I go about changing the keyboard layout? Thanks! : )

**Comment by Leon-Plickat** [comment]
Unfortunately, currently the only way to set the keyboard layout by setting the `XKB_DEFAULT_LAYOUT` (and similar) env var before launching river. See `man river.1` for more.

**Comment by LukeDotDev** [comment]
Thanks alot! So would I be correct to assume it goes in the /river/init file somewhere? Sorry I'm kinda new to all this.

**Comment by Leon-Plickat** [comment]
No, init is executed by river after it already started, so setting the env var here would not affect anything. You have to set it before executing river.

**Comment by LukeDotDev** [comment]
Ah, so if i understood that correctly its supposed to go in something like /etc/environment? As that loads before river starts? Or am I completely lost here?

**Comment by LukeDotDev** [comment]
Issue has been fixed! Thanks for all the help <3
