### ISSUE TITLE
Feature request: Naming tags (again)

### ISSUE THREAD

**Issue by mhwombat** [riverwm/river#470]
I would like to revisit issue #72, allowing the user to name tags. (I can't re-open that issue, so I've created a new one.)

This is a feature that I would dearly love. In sway, I use the first letter of the name in the relevant key bindings for named workspaces. For example:

    Mod4+n switches to workspace "nixos"
    Mod4+Shift+n moves container to workspace "nixos"

I also have a few workspaces that have names instead of numbers; I use the ordinary number keys for them.

Here are my arguments for why this should be done in river rather than the status bar:

1. Having the tags names and the key mappings in one place (the river config) makes it easier to add new tags, and to keep both names and keymaps in sync as I change the projects I'm working on.
2. I try out new status bars from time to time. If those status bars have river support, they should be able to just pick up the tag names. I would rather not have to define the names in the configuration files for all of the status bars that I might use.

River could continue to use the binary flags as it currently does. It just needs to provide a way for the user to associate a string (name) with a tag, and a way to query the tag names (for use by status bars).

**Comment by ifreund** [comment]
I don't have a problem with the status quo currently, all this would change is how river/status bars are configured not the actual functionality. I intend for the way river is configured by users to evolve considerably still and sticking to core functionality/avoiding complication by features that aren't strictly necessary throughout this evolution is important.
