### ISSUE TITLE
Rivertile Segmentation Fault 0.1.0

### ISSUE THREAD

**Issue by TogoorooDev** [riverwm/river#471]
starting river gives me the error here (appears to be in rivertile): 
`Segmentation fault at address 0x8`
`???:?:?: 0x7f4489422ff7 in ??? (???)`
`error: BrokenPipe`
`/home/username/source/river-0.1.0/zig-cache/zig-wayland/wayland_client.zig:73:5: 0x205de6 in std.start.main (rivertile)`
`    return switch (os.errno(rc)) {`
`   ^`
`/home/username/source/river-0.1.0/rivertile/main.zig:383:22: 0x205e73 in std.start.main (rivertile)`
`    while (true) _ = try display.dispatch();`

full output: https://termbin.com/13b4
I am running this with version 0.1.0 on Gentoo, installed a few days ago. Sway is working perfectly. 
Here is the init (mostly copied from the default one): https://termbin.com/m2yi

**Comment by TogoorooDev** [comment]
i will try this with the latest from git now

**Comment by TogoorooDev** [comment]
I get the same error on with the latest git version

**Comment by user18130814200115-2** [comment]
Do you have `rivertile` installed and executable?

**Comment by ifreund** [comment]
@TogoorooDev it looks like you're using a version of seatd affected by the bug discussed here and a libinput version new enough to trigger it: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3200

**Comment by TogoorooDev** [comment]
@ifreund Thank you, that did fix the issue and river runs now.
