### ISSUE TITLE
ckb-next segfaults under river, not under GNOME or Plasma

### ISSUE THREAD

**Issue by CoatlessEskimo** [riverwm/river#479]
I've tried both with and without `GDK_BACKEND=x11`. I'm unsure as to whether or not this is a river issue, wayland issue, or ckb-next issue, as this seems to happen on both river and qtile (main reason I jumped ship from qtile).
```
ali@archlinux ~/ckb-next (master) [SIGSEGV]> GDK_BACKEND=x11 ckb-next
QObject::startTimer: Timers cannot have negative intervals
Path to settings: "/home/ali/.config/ckb-next/ckb-next.conf"
fish: Job 1, 'GDK_BACKEND=x11 ckb-next' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by novakne** [comment]
Is it wayland native or does it needs Xwayland? Looks like it's a qt app, maybe you need some env variables
https://github.com/swaywm/sway/wiki/Running-programs-natively-under-wayland#qt5

**Comment by ifreund** [comment]
Version 0.4.4 doesn't crash for me on void linux, I didn't set any environment variables and it ran using wayland by default. My qt version is `5.15.3`

**Comment by ifreund** [comment]
Can anybody else reproduce this?

**Comment by nzure** [comment]
Just installed from the AUR, runs with no problems (Using `qt 5.15.2` and `ckb 0.4.4`).
