### ISSUE TITLE
Ability to re-enable touchpad while typing

### ISSUE THREAD

**Issue by antaxiom** [riverwm/river#488]
Hello, I've been having a fantastic time with River on my laptop, but I've started to play games an encountered a pretty serious issue I can't seem to make it so I can "use the touchpad while typing" (effectively moving and aiming in a first person game), I luckily have a Thinkpad with a touchpoint which doesn't have this issue as it's seen as a mouse. 

I haven't seen any option in `riverctl` to change this, any advice? 
I've found a way to disable it for gnome and that indeed works, but the solution is obviously only for gnome.

**Comment by ifreund** [comment]
The riverctl man pages mentions a `disable-while-typing` toggle for input devices, does this not work?

**Comment by novakne** [comment]
Yeah it should, at least for me using `riverctl input <device-name> disable-while-typing disabled` works, I never tried with games though
