### ISSUE TITLE
Support Zig 0.9

### ISSUE THREAD

**Issue by McSinyx** [riverwm/river#489]
I am sure that the [maintainers are aware of the recent Zig release](https://ziglang.org/download/0.9.0/release-notes.html#Isaac-Freund-Joins-the-Core-Zig-Team) with multiple breaking changes in the std library, so please consider this as a tracking issue for progress.

**Comment by novakne** [comment]
If you look at the `next-zig` branch you'll see that it's already done so it should be merge to master soon

**Comment by McSinyx** [comment]
Awesome!

**Comment by ifreund** [comment]
river 0.1.2 has just been released.
