### ISSUE TITLE
Visual glitch on border's bottom left corner, with a scaling factor of 1.75

### ISSUE THREAD

**Issue by dnkl** [riverwm/river#496]
I was testing how foot behaved under various scaling factors, and noticed what looks like a mistake in river's rendering of the SSD's bottom left corner.

Note how the left border continues down below the bottom border:
![river-bottom-right-border-scale-175](https://user-images.githubusercontent.com/14031526/147603535-8b7dd064-bd18-47a6-8267-677961b96ee6.png)

I didn't notice any issues with 1.5 or 2x scaling, only at 1.75x.

Version: 0.2.0-dev-d93ee2c - built december 11:th (yup, getting a bit outdated...)

**Comment by ifreund** [comment]
Should be fixed in f370202b685eb9e9ddeda50acfb06179f9fc82c4
