### ISSUE TITLE
Popup menus showing in the middle of the screen

### ISSUE THREAD

**Issue by KSPAtlas** [riverwm/river#498]
I've noticed on certain applications popup menus are shown in the middle, meaning that if a program has a popup menu that closes when not hovered, they CANT be used. Ive nad this bug on Waybar and Lagrange (when running SDL_VIDEODRIVER=wayland)

**Comment by ifreund** [comment]
I'm not sure what is going wrong with Lagrange, but I'm pretty sure it's not river's fault. It creates a xdg toplevel and then immediately destroys it when I right click under river and sway when using the wayland SDL backend. It doesn't even start under weston. I'm calling this a client bug.

With regards to Waybar, I'm not entirely sure what popup you are talking about. Could you clarify how to reproduce the problem there?

**Comment by ifreund** [comment]
RE  Lagrange: https://github.com/skyjake/lagrange/issues/429

**Comment by hillyu** [comment]
have similar issue with qutebrowser, however the issue exists when I am using sway. The symptom is a bit different: I have two monitors, one is hidpi (scale 2) the other is standard (scale 1), the context menu popup in the middle if I right click on the lower part of the screen on standard monitor. But if i start a second window (open a page in a new window or start a new instance), everything is normal on that new window/instance.
