### ISSUE TITLE
Black screen on some Wine games after they lose focus

### ISSUE THREAD

**Issue by Snektron** [riverwm/river#500]
This is the same issue as https://github.com/swaywm/sway/issues/4324, which was resolved by https://github.com/swaywm/sway/pull/5566.

**Comment by ifreund** [comment]
Thanks for the link to the sway fix!

**Comment by novakne** [comment]
@Snektron would you mind testing the PR above, please I have nothing to reproduce this bug

**Comment by Snektron** [comment]
Sorry, unfortunately i have not yet been able to successfully build master river yet.

**Comment by Snektron** [comment]
@novakne It seems to work properly now :)

**Comment by ifreund** [comment]
Thanks for confirming!
