### ISSUE TITLE
Resizing windows small enough can push part of them offscreen

### ISSUE THREAD

**Issue by j-james** [riverwm/river#512]
Example with Thunar:

![2022-01-20-202320](https://user-images.githubusercontent.com/35242550/150465548-4cc92f05-42c3-4e92-9baa-c93459947a01.png)

river version: `0.2.0-dev-a782c6a`

**Comment by Leon-Plickat** [comment]
This is not an error. In Wayland the server has full control over positioning, but the dimensions of windows ultimately are up to the client. And some clients have a minimum window size and will never allow their window to be smaller than it.

**Comment by j-james** [comment]
Ah, interesting. Good to know!
