### ISSUE TITLE
Chromium based browsers don't work on the wlroots 0.15 release branch of river

### ISSUE THREAD

**Issue by Shinyzenith** [riverwm/river#514]
reverting to 0.14 fixed it

**Comment by Shinyzenith** [comment]
posting the error logs in a second, need to go back to 0,15 to get it.

**Comment by Shinyzenith** [comment]
![Sun-Jan-23-06:17:03-AM-IST-2022](https://user-images.githubusercontent.com/60808802/150660276-44ce8f96-ec52-4900-a66e-c3302966a62e.png)

**Comment by novakne** [comment]
This is a bug on your browser side, they bind to wl_output v4 without supporting it.

Looks like there are already some issues about this [1], [2], [3], seems like it was fixed though, so maybe you're using a version without the fix.

[1]: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3344#note_1189198
[2]: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3351
[3]: https://bugs.chromium.org/p/chromium/issues/detail?id=1279574

**Comment by ifreund** [comment]
This is a chromium bug, not an issue with river or wlroots. See the issues linked by novakne for more information.

**Comment by Shinyzenith** [comment]
Understood, Thank you 👍🏽 @ifreund @novakne
