### ISSUE TITLE
change main count based on amount of windows open in current tag?

### ISSUE THREAD

**Issue by amydotsh** [riverwm/river#515]
so, i want to change the main count to 2 when the amount of windows open in the current tag is greater than 3, i have no idea how to do this but i assume its probably possible. if anyone can help that'd be great :)

**Comment by Leon-Plickat** [comment]
It is possible, however it will require you to use a custom layout generator. Modifying rivertile for this should be straight forward. In it's code search for `.layout_demand`. That is the code that runs when a new layout is generated. `ev.view_count` is the amount of windows and you can easily set `main_count` to whatever you like here.

**Comment by amydotsh** [comment]
i copied rivertile and added
```
if (ev.view_count > 4)
    main_count = 2;
```
but i have no clue how to build it. i tried making a build.zig and i set the executable the tile's main.zig, but i just get errors sooo yeah. i dont know zig, but i'd like to learn it one day it might be fun.
```
./amytile/main.zig:60:15: error: unable to find 'flags'
const flags = @import("flags");
              ^
./amytile/main.zig:330:20: note: referenced here
    const result = flags.parse(argv[1..], &[_]flags.Flag{
                   ^
/usr/lib/zig/std/start.zig:471:40: note: referenced here
            const result = root.main() catch |err| {
                                       ^
amytile...The following command exited with error code 1:
/usr/bin/zig build-exe /home/amy/burgerking/amytile/amytile/main.zig --cache-dir /home/amy/burgerking/amytile/zig-cache --global-cache-dir /home/amy/.cache/zig --name amytile --enable-cache 
error: the following build command failed with exit code 1:
/home/amy/burgerking/amytile/zig-cache/o/d1b8b091deb40e3fda7b0513b862c0ad/build /usr/bin/zig /home/amy/burgerking/amytile /home/amy/burgerking/amytile/zig-cache /home/amy/.cache/zig --prefix /home/amy/.local install
```

**Comment by amydotsh** [comment]
I am using the xbps package of river & zig if that helps understand the issue

**Comment by Leon-Plickat** [comment]
Rivertile uses command flag parsing code from `common/`. So you need to copy that file to your modified rivertile as well.

Then, either change the line in rivertile to `const flags = @import("flags.zig");` or add it as a package in build.zig like this `rivertile.addPackagePath("flags", "common/flags.zig");`.

**Comment by amydotsh** [comment]
changed the line in rivertile to the correct one, spent a couple hours trying to figure it out and i just cant :/ i tried lots of things, but i set it back to just what i had before + the line in rivertile changed to that.
<details>
<summary>error message</summary>

```
./src/main.zig:333:41: error: unable to find 'build_options'
        try std.io.getStdOut().writeAll(@import("build_options").version ++ "\n");
                                        ^
/usr/lib/zig/std/start.zig:471:40: note: referenced here
            const result = root.main() catch |err| {
                                       ^
amytile...The following command exited with error code 1:
/usr/bin/zig build-exe /home/amy/burgerking/amytile/src/main.zig --cache-dir /home/amy/burgerking/amytile/zig-cache --global-cache-dir /home/amy/.cache/zig --name amytile --pkg-begin flags /home/amy/burgerking/amytile/src/flags.zig --pkg-end --enable-cache 
error: the following build command failed with exit code 1:
/home/amy/burgerking/amytile/zig-cache/o/d1b8b091deb40e3fda7b0513b862c0ad/build /usr/bin/zig /home/amy/burgerking/amytile /home/amy/burgerking/amytile/zig-cache /home/amy/.cache/zig --prefix /home/amy/.local install
```
</details>

<details>
<summary>rivertile main.zig</summary>

```
const std = @import("std");
const mem = std.mem;
const math = std.math;
const os = std.os;
const assert = std.debug.assert;

const wayland = @import("wayland");
const wl = wayland.client.wl;
const river = wayland.client.river;

const flags = @import("flags.zig");
//
// same as release 1.0 up till .layout_demand line 195
//
            .layout_demand => |ev| {
                const main_count = math.clamp(output.main_count, 1, ev.view_count);
                const secondary_count = if (ev.view_count > main_count)
                    ev.view_count - main_count
                else
                    0;

                if (ev.view_count > 3)
                    main_count = 2;
// same as release 1.0 all the way down
```
</details>

<details>
<summary>build.zig</summary>

```
const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    const target = b.standardTargetOptions(.{});
    const mode = b.standardReleaseOptions();

    const amytile = b.addExecutable("amytile", "src/main.zig");
    amytile.setTarget(target);
    amytile.setBuildMode(mode);
    amytile.addPackagePath("flags", "src/flags.zig");
    amytile.install();

    const run_cmd = amytile.run();
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| {
        run_cmd.addArgs(args);
    }

    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);
}
```
</details>

main.zig and flags.zig share a directory in src/

**Comment by Leon-Plickat** [comment]
Ah, yeah rivertile needs a few things in the build system setup.

I recommand you check out rivercarro[1], which is a fork of rivertile
with working build system, to see what you need to to. Probably the
easiest route.


Friendly greetings,
Leon Henrik Plickat

[1] https://git.sr.ht/~novakane/rivercarro

**Comment by amydotsh** [comment]
ill check it out, thanks :)

**Comment by novakne** [comment]
Have a look at [rivercarro](https://git.sr.ht/~novakane/rivercarro) build.zig if you want an example on how to made a rivertile version outside river

**Comment by novakne** [comment]
@amydotsh Here you go :) https://git.sr.ht/~novakane/rivertile
