### ISSUE TITLE
river 0.1.2 versus Valheim mouse focus/clicks, fixed in 0.1.0 and master (745fe82)

### ISSUE THREAD

**Issue by jokeyrhyme** [riverwm/river#517]
Howdie, thanks again for sharing your work here, `river` has been my daily-driver for a while now and it's working well for me

`wlroots` 0.15 finally went stable in Archlinux this week, enabling me to upgrade to `river` 0.1.2 (from 0.1.0), and I noticed an issue when trying to play Valheim (full-screen native-Linux xwayland) via Steam

Steps to reproduce:

1. open Steam (I'm using the flatpak)
2. launch Valheim (would be interesting to see if this happened with other games)
3. press arrow keys on keyboard, observe that Valheim has focus and is receiving keyboard events (able to navigate menu)
4. move mouse, observe that Valheim's custom mouse cursor is not active (unexpected)
5. try to click menus with mouse, observe that clicks seem to be going to the Steam window behind Valheim, e.g. Steam's context menu pops up if I right-click (unexpected)
6. try moving/re-tagging Valheim so it's on another workspace and navigate to that workspace (away from Steam), observe that clicks are still going to Steam even though it's not underneath/behind Valheim (unexpected)

I thought this was a wlroots 0.15 issue, but Valheim works fine in sway 1.7, so I went and built `river` master (745fe82) and it's working as expected there, too, yay! I've not isolated the exact commit that addresses my issues, but I can if you think that would help

So, the bug seems to be in `river` 0.1.2

I was wondering if it was appropriate for master (745fe82) to be tagged/released as an 0.1.3 or something?

**Comment by ifreund** [comment]
Sure, we can do a 0.1.3 release sometime soon, master has accumulated a fair number of bugfixes since 0.1.2 was released. It may take me a few days to find the time to do the cherry picking and push the tag though.

**Comment by ifreund** [comment]
Fwiw the commit that fixed that issue with valheim was almost certainly e16eabd9282e77c89e47874838443fb34150b56d.

**Comment by ifreund** [comment]
just tagged 0.1.3! https://github.com/riverwm/river/releases/tag/v0.1.3
