### ISSUE TITLE
river fails to build 

### ISSUE THREAD

**Issue by wael444** [riverwm/river#518]
```
$ zig build -Drelease-safe --prefix ~/.local install
./build.zig:73:22: error: no member named 'addOptions' in struct 'std.build.Builder'
    const options = b.addOptions();
                     ^
/usr/lib/zig/std/special/build_runner.zig:170:24: note: referenced here
        .ErrorUnion => try root.build(builder),
```

**Comment by novakne** [comment]
You are not using zig 0.9

**Comment by wael444** [comment]
> You are not using zig 0.9

unfortunately Void Linux zig package is still on 0.8.1.

**Comment by novakne** [comment]
@wael444 you can use a tarball from [zig website](https://ziglang.org/download/), and for void zig need llvm to be updated to llvm13 so that take some time.

**Comment by wael444** [comment]
> llvm13 hasn't been packaged for void yet. Until then, zig cannot be updated. Unless you intend to update LLVM I'd recommend just closing this PR. The zig update will be included in the LLVM update PR when someone gets around to it.

> and for void zig need llvm to be updated to llvm13 so that take some time.

that hurts.
