### ISSUE TITLE
Floating window moving broken with windows that don't ack configures

### ISSUE THREAD

**Issue by vainiovano** [riverwm/river#519]
Run a client that doesn't respond to configures, or weston-simple-shm with this patch:
```diff
diff --git a/clients/simple-shm.c b/clients/simple-shm.c
index 1c2bea9e..13023a5e 100644
--- a/clients/simple-shm.c
+++ b/clients/simple-shm.c
@@ -130,9 +130,8 @@ handle_xdg_surface_configure(void *data, struct xdg_surface *surface,
 {
        struct window *window = data;
 
-       xdg_surface_ack_configure(surface, serial);
-
        if (window->wait_for_configure) {
+               xdg_surface_ack_configure(surface, serial);
                redraw(window, NULL, 0);
                window->wait_for_configure = false;
        }
```

After the window has been:
1. made floating
2. been tried to be resized

, the window can't be moved any more and the cursor moves very weirdly when trying to move the window. This video showcases the issue:

https://user-images.githubusercontent.com/16741932/151663418-053d8dfd-a250-4e3d-81eb-46c6bd9e3a64.mp4

**Comment by ifreund** [comment]
I've looked into fixing this, but it's a fair bit of work to do properly. Since this only affects poorly behaving clients and I already plan on rewriting most of this code while migrating to the new wlroots scene API, I'm probably going to leave off fixing this until.

Does this affect any real clients you are trying to use with river?

**Comment by vainiovano** [comment]
> Does this affect any real clients you are trying to use with river?

It doesn't. I found it while trying to port renderdoc to Wayland (and wasn't very successful...). I haven't seen this issue with any real clients.
