### ISSUE TITLE
Execute 2 deamon programs at the same time

### ISSUE THREAD

**Issue by NiceStuff2Code** [riverwm/river#523]
I try to run waybar and rivertile at the same time. If i run this, i got waybar but no tilling windows

![IMG_20220131_132440.jpg](https://user-images.githubusercontent.com/34421646/151793517-9721f765-430c-4737-aaec-56dffe8c6a7f.jpg)

**Comment by Leon-Plickat** [comment]
The `init` is just a shell script. The `exec` command replaced the current process with the command you provided. So if you have an `exec` in a shell script, any code after it will never be reached.

If you want to run multiple programs in the background, you can either do `<command> &` or `riverctl spawn <command>`.
