### ISSUE TITLE
Implement titlebars or have some sort of (thicker?) border for actions

### ISSUE THREAD

**Issue by keshto** [riverwm/river#528]
Implement titlebars or have some sort of (thicker?) border for actions, so one could for example, middle click and close a window.

broken out from larger https://github.com/riverwm/river/issues/526

**Comment by ifreund** [comment]
SSD beyond the basic borders we have currently is not planned.

**Comment by keshto** [comment]
Having one border thicker than the other 3 is not the same as a titlebar (even though at some point having titlebars might be desirable), but ok...

**Comment by Leon-Plickat** [comment]
> (even though at some point having titlebars might be desirable)

Proper titlebars would require text rendering, which comes with a lot of nasty dependencies that river really should not include.

Maybe client-rendered titlebars will be a thing eventually, but server-side likely never.
