### ISSUE TITLE
river 0.2.0

### ISSUE THREAD

**Issue by ifreund** [riverwm/river#529]
This is the tracking issue for river 0.2.0.

New features:

- Touch input is supported for clients that accept touch input. No pointer emulation is implemented yet.
- `ext-sesson-lock-v1` is supported. This is a more robust protocol for screenlocking that I developed earlier this year. See [this blog post](https://isaacfreund.com/blog/2022-02/) for more information.
- `ext-idle-notify-v1` is supported. This replaces the KDE idle protocol, support for which has been removed.
- `riverctl focus-output` and `riverctl send-to-output` may target an output by name.
- `riverctl map` has a new `-layout` flag which may be used to map keys independent of the currently active keyboard layout.
- `riverctl keyboard-layout` allows setting the keyboard layout and xkb options at runtime.
- `riverctl map-switch` allows running a command when e.g. a laptop lid is closed.
- `riverctl map-pointer` may run arbitrary commands.
- `riverctl focus-follows-cursor` has a new `always` mode.
- `riverctl set-cursor-warp` has a new `on-focus-change` mode.
- The cursor may be (automatically) hidden with the new `riverctl hide-cursor` command.
- Keyboard groups are now supported with the new `riverctl keyboard-group-create` and related commands.
- `wlr-output-management-unstable-v1` version 4 is now implemented, which means that adaptive sync or VRR may be enabled using a suitable client.
- `wp-single-pixel-buffer-v1` is supported.
- The `river-status-unstable-v1` protocol has been extended to expose the current mode and layout name to clients such as status bars.
- The `river-layout-v3` protocol has been extended to expose the currently active tags when a command is sent to the layout generator client.

Breaking changes compared to 0.1.0:

- Input device names are now prefixed with the device type 422cd3e
- The `riverctl spawn-tagmask` command applies globally.
- Support for the `input-inhibit` protocol has been removed 78a46c316a2c220c96c377ffaaa090c16668fd4f. Lock screens should now use `ext-session-lock-v1`
- Support for the `org_kde_kwin_idle` protocol has been removed 6ac3928556af555df7572e6b2f6ff32ba0be1d68. The `ext-idle-notify-v1` protocol should be used instead.
- wlroots 0.16 is required as a build dependency instead of 0.15.

**Comment by Leon-Plickat** [comment]
New features:

* keyboard layout can be set via command at runtime

**Comment by ifreund** [comment]
> New features:
> 
>     * keyboard layout can be set via command at runtime

added, thanks for the reminder :)

**Comment by ifreund** [comment]
https://github.com/riverwm/river/releases/tag/v0.2.0
