### ISSUE TITLE
Why switch from gpl-3.0-or-later to gpl-3.0-only?

### ISSUE THREAD

**Issue by Zaedus** [riverwm/river#530]
This is more out of curiosity, but what inspired this change in license? I'm trying to understand licensing better, specifically why choose one over another, especially a seemingly subtle difference.

**Comment by ifreund** [comment]
I just decided that I didn't feel ok with some organization over which I have 0 control having the power to release a new version of the GPL which my software is then automatically licensed under. What if I don't agree with the new version of the license?

**Comment by Leon-Plickat** [comment]
Additionally, a hostile takeover of the FSF is not impossible. If a license-troll got hold of the GPL rights, all projects using the "or later" clause are kinda screwed.

Further reading: https://ariadne.space/2021/11/16/the-problematic-gpl-or-later-clause/
