### ISSUE TITLE
failed to open DRM

### ISSUE THREAD

**Issue by amydotsh** [riverwm/river#538]
void linux, river from xbps repo
i have all dependencies, polkit elogind dbus, mesa-dri is installed all required drivers for intel gpu installed, river was working perfectly fine this morning, i remember updating packages, though i dont think any of them wouldve broken anything, then a few hours later i rebooted and river would not launch through tty
i have tried a lot of different things and i am just clueless so im resorting to here
the issue has to do with wlroots, it fails to open any DRM device deviceession and sometimes gives an error found 0 GPUs.
i hope the answer is obvious and that im just dumb

**Comment by novakne** [comment]
Can you share the complete log message please?

**Comment by Leon-Plickat** [comment]
What output does `ls /dev/dri/` give you?

**Comment by amydotsh** [comment]
oh! and when i try it for a second time it gives a new error
<details>

```
$ river
# same first line
# same second line
error: BackendCreateFailedackend.c:371] Failed to open any DRM deviceession
# same last 3 lines, with the question marks and numbers
```
</details>

**Comment by Leon-Plickat** [comment]
> oh! and when i try it for a second time it gives a new error

I think it's the same error. There are probably multiple things dumping messages to the TTY, and they then overlap in random ways.

> no such file or directory

Then your system does not recognize any graphics devices. Did the update you did before river stopped working include either a driver  / mesa update or a kernel update?

And that leaves us with the additional question of why wlroots did not just fall back to software rendering.

**Comment by amydotsh** [comment]
> Did the update you did before river stopped working include either a driver / mesa update or a kernel update?

dont think so, i dont remember clearly but the latest date for mesa packages in /var/cache/ was Feb 5, but i dont know if thats a reliable way to check

**Comment by amydotsh** [comment]
> Can you try forcing wlroots to use the software renderer with `WLR_RENDERER=pixman river`?

gives the exact same error, the shorter one

**Comment by tiosgz** [comment]
> updated it, sorry for that! im posting on a phone which is tedious :(

Alright, i apologise too. I could have guessed that.

**Comment by novakne** [comment]
> dont think so, i dont remember clearly but the latest date for mesa packages in /var/cache/ was Feb 5, but i dont know if thats a reliable way to check

`svlogtail xbps` should give you the date, which is the 5 for me too, mesa 21.3.5, I don't know if it break something with river 0.1.0
