### ISSUE TITLE
A way to get the window position?

### ISSUE THREAD

**Issue by Euro20179** [riverwm/river#542]
## Problem

I've looked around a bit in the man pages, and checked out things like `wayland-info`, but i can't find any way to get the position of a 
window.

If there's already a way to do this or something similar please tell me.

## Potential Solution

It would be nice to be able to run something like `riverctl geometry` and it'll print the focused window's geometry, something like

```sh
$ riverctl geometry
50x50+0+0
```

Or even better a command to get general info about the focused window.

```sh
$ riverctl window-information
geometry: 50x50+0+0
title: some-window-title
...
```

### Geometry:

When resizing a window it is sometimes nice to know the current size of the window.
Knowing the position would allow scripts to move the window across monitors when it hits the edge of the screen.

### Title:

Really helpful for statusbars.

**Comment by Leon-Plickat** [comment]
> I've looked around a bit in the man pages, and checked out things like wayland-info, but i can't find any way to get the position of a window.

This is intentional. A Wayland client isn't supposed to have access to this data.

> Geometry: When resizing a window it is sometimes nice to know the current size of the window. Knowing the position would allow scripts to move the window across monitors when it hits the edge of the screen.

Window management should be done properly, not hacked in with scripts.

> Title: Really helpful for statusbars.

You can already get the window title for status bars, take a look at the river-status protocol.

---

I see no compelling reason to grant clients access to this data. Feel free to re-open if you think you have found a sensible use-case (that isn't scripting window management).

**Comment by Euro20179** [comment]
> You can already get the window title for status bars, take a look at the river-status protocol.

Yeah I've seen this, or at least i've seen `protocols/river-status-unstable-v1.xml`, but I have no idea how to interact with it.

**Comment by tpeacock19** [comment]
Being able to get window dimensions would be useful for taking screenshots of the active view. I have yet to find a way in wayland that doesn't use `swaymsg -t get_tree`.

**Comment by Leon-Plickat** [comment]
On Fri Feb 18, 2022 at 2:20 AM CET, tpeacock19 wrote:
> Being able to get window dimensions would be useful for taking
> screenshots of the active view. I have yet to find a way in wayland that
> doesn't use `swaymsg -t get_tree`.

This is better solved by extending the screenshot protocol, not with
such hacks.


Friendly greetings,
Leon Henrik Plickat
