### ISSUE TITLE
Add information for rpi

### ISSUE THREAD

**Issue by amydotsh** [riverwm/river#545]
using a raspberrypi 400, i was confused at first cause riverwm wasnt launching, installed sway and it gave an error which told me to enable dtoverlay=vc4-kms-v3d in /boot/config.txt since i was using an rpi4, now river works

basically just add something in readme or wiki to say RPI users must enable dtoverlay=vc4-kms-v3d in /boot/config.txt

**Comment by Leon-Plickat** [comment]
The Wiki is editable by everyone. If you like, you can create a page yourself.

**Comment by amydotsh** [comment]
added an entry in FAQ :)
