### ISSUE TITLE
Rivertile crashes with integer overflow if main-ratio is changed

### ISSUE THREAD

**Issue by KSPAtlas** [riverwm/river#546]
I added `-main-ratio 55` to `rivertile`s args, however, when trying to open a terminal, the first one opens fine, but the second causes `rivertile` to panic (integer overflow) and `SIGABRT`. Running it even with `-main-ratio 60` causes it to crash, but no args works fine. I have checked and no other args are causing this behavior.

OS: Void Linux aarch64-musl
Host: Raspberry Pi 4b
River version: 0.1.0

**Comment by Leon-Plickat** [comment]
Would be interesting to see the crash log as well as the dimensions of your screen.

**Comment by Leon-Plickat** [comment]
Can you check if #547 fixes the issue for you?

**Comment by KSPAtlas** [comment]
> Would be interesting to see the crash log as well as the dimensions of your screen.

1920x1080

**Comment by Leon-Plickat** [comment]
Ah, I was under the impression the screen would be small, like a lot f Raspberry Pi screens are. In thic case the crashlog will be even more important, so please show that so we can find out what's causing the bug.

You can kill the currently running rivertile and start a new instance in a terminal, then reproduce the crash, to get the backtrace printed by zig. River should handle the crash and re-launching of rivertile just fine.

**Comment by KSPAtlas** [comment]
> Ah, I was under the impression the screen would be small, like a lot of Raspberry Pi screens are. In this case the crashlog will be even more important, so please show that so we can find out what's causing the bug.
> 
> You can kill the currently running rivertile and start a new instance in a terminal, then reproduce the crash, to get the backtrace printed by zig. River should handle the crash and re-launching of rivertile just fine.

I have done that before, and there was no back trace:
```
thread 4024 panic: integer overflow
Aborted
```

**Comment by ifreund** [comment]
Should be fixed by e67a9423a81359bd9d3bc33215b24222a0c85775
