### ISSUE TITLE
Build with wlroots which installed locally.

### ISSUE THREAD

**Issue by ahmadraniri1994** [riverwm/river#550]
I'm trying to build river but it always complaint that it requires wlroots version 0.15, I do have wlroots version 0.15 but it's installed locally (/usr/local). Debian still have wlroots version 0.14.x, I won't rebuild wlroots and installed to /usr because I'm afraid that will break the entire Wayland stuffs. Any clue ? Thanks.

**Comment by ifreund** [comment]
You probably are looking for the `$LD_LIBRARY_PATH` and `$PKG_CONFIG_PATH` environment variables, which can be set to allow libraries such as wlroots to be installed wherever you like. For example I install wlroots to `~/.local` and set
```
export LD_LIBRARY_PATH="${HOME}/.local/lib"
export PKG_CONFIG_PATH="${HOME}/.local/lib/pkgconfig"
```

**Comment by ahmadraniri1994** [comment]
Thanks, still not successful, I'll try again.

**Comment by ahmadraniri1994** [comment]
I ended up compile wlroots to /usr and it works... still disappointed why the local one not works.

**Comment by reuleaux** [comment]
Hi, and sorry for warming up this old issue:

I am trying to install _river_ on debian bookworm/testing (which is a - all in all -
a fairly recent system).

And I have `libwlroots-dev` installed from debian, which is at version 15.1
```
rx@laptop ~ $ apt-cache show libwlroots-dev
Package: libwlroots-dev
Source: wlroots
Version: 0.15.1-4
...
```
but the _river_ build system requires a more recent version:

```
rx@laptop {master} ~/opt/river/river $ zig010 build -Drelease-safe --prefix ~/opt/river install
/home/rx/opt/river/river/deps/zig-wlroots/src/wlroots.zig:189:9: error: zig-wlroots requires wlroots version 0.16
        @compileError("zig-wlroots requires wlroots version 0.16");
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: river...
error: The following command exited with error code 1:
/home/rx/opt/zig/zig-linux-x86_64-0.10.1/zig build-exe /home/rx/opt/river/river/river/main.zig -lc -I/usr/include/libevdev-1.0/ -levdev -linput -lwayland-server -lxkbcommon -I/usr/include/pixman-1 -lpixman-1 -I/usr/include/libdrm -I/usr/include/pixman-1 -lwlroots -cflags -std=c99 -O2 -- /home/rx/opt/river/river/river/wlroots_log_wrapper.c -cflags -std=c99 -- /home/rx/opt/river/river/zig-cache/zig-wayland/river-control-unstable-v1-protocol.c -cflags -std=c99 -- /home/rx/opt/river/river/zig-cache/zig-wayland/river-status-unstable-v1-protocol.c -cflags -std=c99 -- /home/rx/opt/river/river/zig-cache/zig-wayland/river-layout-v3-protocol.c -cflags -std=c99 -- /home/rx/opt/river/river/zig-cache/zig-wayland/wlr-layer-shell-unstable-v1-protocol.c -cflags -std=c99 -- /home/rx/opt/river/river/zig-cache/zig-wayland/wlr-output-power-management-unstable-v1-protocol.c -cflags -std=c99 -- /home/rx/opt/river/river/zig-cache/zig-wayland/wayland-protocol.c -cflags -std=c99 -- /home/rx/opt/river/river/zig-cache/zig-wayland/xdg-shell-protocol.c -cflags -std=c99 -- /home/rx/opt/river/river/zig-cache/zig-wayland/ext-session-lock-v1-protocol.c -cflags -std=c99 -- /home/rx/opt/river/river/zig-cache/zig-wayland/pointer-gestures-unstable-v1-protocol.c -cflags -std=c99 -- /home/rx/opt/river/river/zig-cache/zig-wayland/pointer-constraints-unstable-v1-protocol.c -fno-strip -OReleaseSafe --cache-dir /home/rx/opt/river/river/zig-cache --global-cache-dir /home/rx/.cache/zig --name river --pkg-begin build_options /home/rx/opt/river/river/zig-cache/options/WK6ASFIUfzigmLD2UBt2n3iNUjvYreUxsxOCkLuAlXCH0kh6unI7IUOLq0wiER0d --pkg-end --pkg-begin wayland /home/rx/opt/river/river/zig-cache/zig-wayland/wayland.zig --pkg-end --pkg-begin xkbcommon /home/rx/opt/river/river/deps/zig-xkbcommon/src/xkbcommon.zig --pkg-end --pkg-begin pixman /home/rx/opt/river/river/deps/zig-pixman/pixman.zig --pkg-end --pkg-begin wlroots /home/rx/opt/river/river/deps/zig-wlroots/src/wlroots.zig --pkg-begin wayland /home/rx/opt/river/river/zig-cache/zig-wayland/wayland.zig --pkg-end --pkg-begin xkbcommon /home/rx/opt/river/river/deps/zig-xkbcommon/src/xkbcommon.zig --pkg-end --pkg-begin pixman /home/rx/opt/river/river/deps/zig-pixman/pixman.zig --pkg-end --pkg-end --pkg-begin flags /home/rx/opt/river/river/common/flags.zig --pkg-end -fno-PIE --enable-cache 
error: the following build command failed with exit code 1:
/home/rx/opt/river/river/zig-cache/o/0776e806277d3cf768f7b8bef5ba187a/build /home/rx/opt/zig/zig-linux-x86_64-0.10.1/zig /home/rx/opt/river/river /home/rx/opt/river/river/zig-cache /home/rx/.cache/zig -Drelease-safe --prefix /home/rx/opt/river install
rx@laptop {master} ~/opt/river/river $
```
This reminds me very much of the situation above - where the Debian version was at 0.14, but building _river_ required 0.15 - Debian being one small step behind the build requirements.

Thus, I may be able to proceed, by installing _wlroots_ from src (and install locally) - as the author of this issue: 
[ahmadraniri1994](https://github.com/ahmadraniri1994) did. - And I assume, that the advice given above: to use LD_LIBRARY_PATH, and PKG_CONFIG_PATH will come in handy then.

But really, I think: is this strict version policy really necessary? - Or could _river_ be built with my  0.15.1-4 _wlroots_ perhaps? (Or in other words: Could this version requirement be relaxed ?) - Maybe the river author (authors) are just on a system with happens to have wlroots 0.16 installed? 

In any case: this would make my life so much easier! (I could just install all the Debian libs, and then focus on building _river_, without first having to study _wlroots_ build/install instructions).

Many thanks in advance.
  -A

**Comment by ifreund** [comment]
> But really, I think: is this strict version policy really necessary? - Or could river be built with my 0.15.1-4 wlroots perhaps? (Or in other words: Could this version requirement be relaxed ?) - Maybe the river author (authors) are just on a system with happens to have wlroots 0.16 installed?

Yes this is strictly necessary. wlroots  0.16 is not backwards compatible with wlroots 0.15.

Someone does happen to maintain some unofficial debian packages for river if that makes your life easier though: https://www.ne.jp/asahi/nickh/debian/

**Comment by reuleaux** [comment]
OK, I see - and thanks for getting back to me so fast.

And great: I will check the unofficial debian packages then.

**Comment by reuleaux** [comment]
I had a look at the unofficial debian packages: these are for bullseye (the current stable release), whereas I am on testing. - Thus, they are useful for me only so much:I cannot install them immediately - but maybe I can find a way around (or cheat, and create my own debian testing packages from them). - I will see. Thanks so much.

**Comment by flub** [comment]
When running debian testing you can (currently) enable the experimental repository and install libwlroots-dev and libwlroot11 from there if you don't want to build wlroots manually.

**Comment by NickHastings** [comment]
I just uploaded packages for testing. Didn't update the readme yet though. Just switch out "bullseye-backports" for "testing" in the nickh.sources  file.

**Comment by reuleaux** [comment]
Hi,

I have successfully installed the river packages for debian testing, as kindly provided by Nick, and I am running it now!

Many thanks again,
  -A
