### ISSUE TITLE
[question] setting tags based on view_count (move to new "workspace")

### ISSUE THREAD

**Issue by RO5CH** [riverwm/river#556]
hey guys !

first of all, i love your work. it's really amazing. i'm tinkering around with the code base while learning zig.

i wanted to ask a quick question:

is it possible for the layout generator to implement a layout with max 2 views per tag & then assign the next opened view to the next tag and so on ? what i mean is to have a fixed layout of 2 views side-by-side on each tag, automatically assigning new tags if max view_count is > 2. so basically always just two windows per "workspace".

what would be the easiest way to implement this ?
would it be possible to edit rivers code without significant architectural changes ?

theoretically it should be fairly simple, but i wanted to ask you pro's before i'm taking a dive head first into the river :P

grüße aus deutschland ;)

**Comment by Leon-Plickat** [comment]
> is it possible for the layout generator to implement a layout with max 2 views per tag & then assign the next opened view to the next tag and so on ? what i mean is to have a fixed layout of 2 views side-by-side on each tag, automatically assigning new tags if max view_count is > 2. so basically always just two windows per "workspace".

Not in a clean way. The current layout protocol does not allow layout generators control over tags.

You *could* hack it by also using the river control protocol, but it won't be pretty or particularly reliable.

> grüße aus deutschland ;)

Grüße zurück :)
