### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Shinyzenith** [riverwm/river#560]
Hi! I've been trying to write my own compositor for a while now and I've really been trying to avoid c and just couldn't find any good bindings other than python and zig. While python works as proven by qtile, I would rather write it in a faster language.

That being said, I've been trying this for the past 4 months now with little to no progress as my wayland & wlroots knowledge was pretty much non existent, I have written a few apps in [rust](https://github.com/waycrate) since then and I think I've gained some knowledge and would like to try my hands at a compositor again.

Is there any resources that's good to learn from? I have looked at wayland-book wayland.app and both pretty much went over my head... :(

**Comment by ifreund** [comment]
I primarily learned by reading https://wayland.freedesktop.org/docs/html/ plus https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/tinywl/tinywl.c and the source code of wlroots/sway/wayfire. libwayland also has fairly good doc comments in the headers. 

If you don't know about the WAYLAND_DEBUG environment variable yet, it can be very useful for debugging. 

Other than that, just go for it and be persistent, everyone's gotta start somewhere.

**Comment by Shinyzenith** [comment]
I'll try my best, thank you!
