### ISSUE TITLE
Apache NetBeans doesn't render

### ISSUE THREAD

**Issue by James-Musselman** [riverwm/river#561]
Not sure what information you might need, so ask away! All I get when I launch the IDE is a splash screen and a gray box that i believe is the main window afterwards.

**Comment by FollieHiyuki** [comment]
Typical Java suspicion: have you set `$_JAVA_AWT_WM_NONREPARENTING` to `1`?

https://github.com/swaywm/sway/wiki#issues-with-java-applications

**Comment by James-Musselman** [comment]
Works! Thanks!
