### ISSUE TITLE
xwayland: cannot select anything in dialog window

### ISSUE THREAD

**Issue by dkwo** [riverwm/river#562]
I'm using the software mathemtica on void linux (musl), through a glibc container.
It works fine on xorg (dwm), while with river I encounter this problem,
which might be related to the xwayland implementation:

the software opens and operates fine, but when it's time to close it,
clicking on 'quit' brings up a new box ('save none', 'save', 'don't save', 'cancel'),
of which I'm unable to select any (neither with mouse or arrows).
(It is still responsive though, as I can close box itself with $mod4 Q,
and continue working, but not quit mathematica.)

The same behavior applies to any diaolog box that can be launched
from drop-down menu: it looks I cannot access its options.

My install template https://github.com/void-linux/void-packages/pull/35636
might be missing a dependency specific to xwayland,
as opposed to xorg, although that is strange.

Thanks.

**Comment by dkwo** [comment]
Let me add that it works fine in sway.

**Comment by tiosgz** [comment]
Does your version of river have https://github.com/riverwm/river/commit/e16eabd9282e77c89e47874838443fb34150b56d ?

**Comment by dkwo** [comment]
Void currently runs 0.1.1, so no.
That's likely the explanation, thanks.

I then wonder whether I can configure river to change focus by just moving mouse, see #565
