### ISSUE TITLE
Understanding how tags are supposed to be used

### ISSUE THREAD

**Issue by chcore** [riverwm/river#563]
Hello,

I am trying river out after using i3 for a number of years. I think I understand the benefits of tags vs workspaces, but am not sure if I am using them correctly. Let's say that for Tag No. 1 I want 4 terminal windows in a 2x2 grid. In Tag No. 2 I want a web browser and a text editor, split vertically (i.e. side-by-side).

Is this possible without having to modify my layouts each time I want to switch between tags? I am forming the 2x2 grid in Tag No. 1 by increasing the count of windows in the "main" area. Am I doing it wrong?

Thank you

**Comment by novakne** [comment]
Tags don't have anything to do with layout in river, what you want to do is a task assigned to layout generator via river-layout protocol.
What you seem to want is different layouts per tags, that is not possible with rivertile, so you should have a look at the [wiki](https://github.com/riverwm/river/wiki/Community-Layouts) and try kile or stacktile, that both have this feature.

You could also look at [How tags work](https://github.com/riverwm/river/wiki/How-tags-work) for a better understanding of what tags are for.

**Comment by chcore** [comment]
Thank you @novakne 

Yes I think different layouts per tag is what I am after. I also now see issue #218 which mentions that there are no plans to add such a feature to the default layout generator. With respect, I think the scenario I described in my initial post is going to be a very common one for new users like myself and hope the feature does make its way into rivertile in the future.

I am unsure whether stacktile fits my workflow, and after a glimpse of kile's documentation I wouldn't know where to begin with configuring it.

**Comment by Leon-Plickat** [comment]
> With respect, I think the scenario I described in my initial post is going to be a very common one for new users like myself and hope the feature does make its way into rivertile in the future.

Rivertile is meant as a reference implementation of a layout generator. It is kept very simple on purpose and I don't see that changing. We make it pretty clear that you can use alternative layout generators, so "new users" should not have a problem with that if they read the docs.

> I am unsure whether stacktile fits my workflow, and after a glimpse of kile's documentation I wouldn't know where to begin with configuring it.

If rivertile works for you, stacktile will as well: It can mimic rivertiles layout.
