### ISSUE TITLE
[Question] Regarding default config

### ISSUE THREAD

**Issue by uncomfyhalomacro** [riverwm/river#567]
So I noticed by now that river does not have a default config though there is an example config in https://github.com/riverwm/river/tree/master/example. Is there a reason why a default config is not included when doing the installation? e.g. default config in `/etc/river/init` or `/usr/share/river/init`. I do not mind having it not installed at all since I know my way around it but I found that newer users complain about it so I guess I will have to ask here.

Cheers! I do love this project. Hoping for a informative response :heart:

**Comment by novakne** [comment]
This commit [message](https://github.com/riverwm/river/commit/0063c722e55cec4c8e83b0c1ef2c818006d3eb41) should answer your question.

**Comment by uncomfyhalomacro** [comment]
Thanks. I understand :smile: . Closing.
