### ISSUE TITLE
SUPER key not set

### ISSUE THREAD

**Issue by henklt01** [riverwm/river#572]
Hi, I'm running River on NixOS when Im using the stable branch, 21.11, my super key isn't set. All the other keys work just fine. I can spawn, for instance, if I just set it to shift enter. Is there a way to manually set this or check why it isn't picking up correctly?
Thanks!

**Comment by Leon-Plickat** [comment]
The name `Super` for that modifier is a recent addition. Try using `Mod4` instead.

**Comment by henklt01** [comment]
That worked. I guess I have thought of that. Thanks!
