### ISSUE TITLE
fnott: spawning notifications until no more space crashes river

### ISSUE THREAD

**Issue by RO5CH** [riverwm/river#574]
hey guys,

i remember seeing a similar issue before, concerning dunst -> [https://github.com/riverwm/river/issues/555](https://github.com/riverwm/river/issues/555) the fix does not seem to resolve issues with [fnott](https://codeberg.org/dnkl/fnott).
somehow i can reproduce the issue with fnott as notification daemon.

`for i in $(seq 30); do notify-send $i; done`

crashes river with an integer overflow panic. river crashes exactly when there is no more space to attach a new surface.

will post logs & traces if you can't reproduce.

**Comment by novakne** [comment]
That's weird, as you can see in the issue you linked, I reproduced it with fnott before the fix and I can no longer do it, even with `for i in $(seq 1000); do notify-send $i; done`. So you probably should post logs and also your river version.

**Comment by RO5CH** [comment]
i'm using freshly-baked river & fnott..

so further investigation made me find the root cause of the issue:
if you set the `anchor=bottom-right` in **fnott.ini**, new notifications will stack up from the bottom to the top.
when there is no more space for the next notification, river will crash panic with integer overflow.

the fix for issue [#555](https://github.com/riverwm/river/issues/555) maybe only handled the default direction: **top-down**.

every direction should be handled by river to not cause a crash, 
from all possible anchor-points (top-left, top-right, bottom-left, bottom-right).

**Comment by novakne** [comment]
Yeah, I saw that, it does crash with `bottom-right` so this is indeed a river bug as it should never crash.

**Comment by ifreund** [comment]
fixed by ae349b0ce45b44b79a0a93e89c2cd05d24bb63d4
