### ISSUE TITLE
alternative configuration for fullscreen / keep status bars visible

### ISSUE THREAD

**Issue by RO5CH** [riverwm/river#575]
would it be possible to add a config option to allow the fullscreen mode to not overlay the status bar ?

the layout generator already gets the right dimensions to work with (usable area = screen_dimensions - layer_shell status bar).
so the focused window that gets the toggle-fullscreen event should overlap only the layout generator space.

it would look like having only a single view on a tag, but in this case you can keep multiple views on a tag
& then "zoom" or "fullscreen" a view while keeping the status bar in sight. 

would this make sense ?

thanks.

**Comment by Leon-Plickat** [comment]
On Sun Mar 27, 2022 at 1:23 PM CEST, RO5CH wrote:
> would it be possible to add a config option to allow the fullscreen
> mode to not overlay the status bar ?

You can just use a layout generator for that.

Custom things like this is exactly why layouts are external programs.

**Comment by RO5CH** [comment]
wow, you are absolutely right ! :man_facepalming:

i need to get some urgent sleep. the time change last night was not good for me :)

i was only thinking about the toggle-fullscreen command of riverctl, completely forgetting the fact 
that you can send the layout generator a command with send-layout-cmd.

basically rivercarro already implements this logic with it's monocle layout.

thanks leon, have a nice sunny day !

**Comment by Leon-Plickat** [comment]
On Sun Mar 27, 2022 at 2:37 PM CEST, RO5CH wrote:
> thanks leon, have a nice sunny day !

Thanks, I hope you have one as well!
