### ISSUE TITLE
Is it possible to remove borders from specific applications?

### ISSUE THREAD

**Issue by itsKia2** [riverwm/river#576]
Running Arch Linux with the latest versions of all applications. I currently run rofi alongside my river setup (love it so far by the way, great work), and I've noticed that even though its a floating window, river still decides to draw borders on it. This is compared to my bspwm setup before, which did not draw borders around rofi at all. Is this an issue with rofi being shown through xwayland and the issue will be resolved if I use something for wayland (e.g wofi), or is this done through a command in my config file? 

I had initially thought using csd-filter-add app-id would work with this but it does not seem to have any effect.

**Comment by Leon-Plickat** [comment]
Upstream rofi does not support Wayland yet AFAIK. It is going through
XWayland. It still should not be a regular window with borders, but
rather a pop-up / desktop widget, but with XWayland some hick-ups are
to be expected.

There is a rofi fork with native Wayland support: https://github.com/lbonn/rofi


Friendly greetings,
Leon Henrik Plickat

**Comment by itsKia2** [comment]
I installed the fork and it didn't have borders from the get-go. Should have looked into this properly before making a needless issue here. My apologies and thank you.

**Comment by Leon-Plickat** [comment]
On Mon Mar 28, 2022 at 2:59 PM CEST, itsKia2 wrote:
> Should have looked into this properly before making a needless issue
> here. My apologies and thank you.

No worries. Although generally for questions like these it might be
a good idea to ask on IRC first.
