### ISSUE TITLE
Issues with pointer constraints

### ISSUE THREAD

**Issue by Bonicgamer** [riverwm/river#594]
I don't know whether to make this two separate issues or just one since they're both pointer constraint issues, but I assume its easy to split them up later if they should be split up.

- [ ] 1: When a view starts with pointer constraints (such a gamescope or the wlroots pointer constraints example), the cursor doesn't get moved to the right place on the screen. This is more noticeable with `attach-mode bottom`. I think this might be because the views position and size isn't set by the layout manager immediately when the view is created (I guess this is a reason why Sway waits for the surface to commit before moving the cursor to the constraint area?).
- [ ] 2: There is a very weird camera snapping issue in Minecraft that can be reproduced by: pause > unpause > move mouse > click. I've been using a small patch (I think patch is the correct term) which seems to fix it, but it doesn't seem like a "correct" fix. I tried this in Minetest as well but it doesn't seem to have this issue. Minecraft is the only game that I know has this problem, but then again Minecraft is the only game that I play that has a first person camera. I also don't know for sure if this one is necessarily a "pointer constraints" issue.

<details>
<summary>Patch I use to fix Minecraft camera snapping</summary>

```
diff --git a/river/Cursor.zig b/river/Cursor.zig
index da1b8d6..e8ea9b8 100644
--- a/river/Cursor.zig
+++ b/river/Cursor.zig
@@ -962,7 +962,7 @@ fn passthrough(self: *Self, time: u32) void {
         // If input is allowed on the surface, send pointer enter and motion
         // events. Note that wlroots won't actually send an enter event if
         // the surface has already been entered.
-        if (server.input_manager.inputAllowed(result.surface)) {
+        if (self.constraint == null and server.input_manager.inputAllowed(result.surface)) {
             self.seat.wlr_seat.pointerNotifyEnter(result.surface, result.sx, result.sy);
             self.seat.wlr_seat.pointerNotifyMotion(time, result.sx, result.sy);
         }
```
</details>

**Comment by jokeyrhyme** [comment]
Ah, thanks for filing this bug, I've been experiencing this myself and wasn't sure exactly how to word it

I can reproduce this bug in Valheim and New World (both played via the Steam flatpak)

At first I thought it was a wlroots issue or Steam/Proton/Wine issue, but then I tried out sway (with the same version of wlroots) and the problem goes away

```
❯ paru -Qi river
Name            : river
Version         : 0.1.3-4
...

❯ paru -Qi sway
Name            : sway
Version         : 1:1.7-10

❯ paru -Qi wlroots
Name            : wlroots
Version         : 0.15.1-6
```

**Comment by jokeyrhyme** [comment]
Huh, well, I noticed that the patch in https://github.com/riverwm/river/issues/594#issue-1212686444 was for a `passthrough()` function, so I deleted the passthrough-related lines that I inherited from the default configuration: https://github.com/riverwm/river/blob/cacc986/example/init#L112-L120

I don't think I can reproduce this bug anymore

What's weird is that I've never activated/toggled passthrough mode, so I don't quite understand why deleting these lines had the impact they did

**Comment by jokeyrhyme** [comment]
I gave this a try in river 0.2.2 (wlroots 0.16.1) and I had difficulty reproducing this, just in the few minutes I had free to test

And the patch https://github.com/riverwm/river/issues/594#issue-1212686444 doesn't apply anymore

I'll try to give this a proper work-out over the next couple of days to see if this is still a problem

**Comment by ifreund** [comment]
The brand new pointer constraints implementation included in the scene branch (#793) should in theory fix both of these bugs but I'm not able to test with minecraft.

It would be helpful if those affected by this issue could test the new implementation and see if these bugs can still be reproduced or if any new bugs can be found.

Note that the new implementation has different behavior in some cases. For example, river will no longer warp the cursor into a surface when a surface with a pointer constraint gains keyboard focus. The constraint won't be activated until the user moves the cursor into the surface.

**Comment by Bonicgamer** [comment]
I haven't been able to do a proper test (play Minecraft for a long period of time) yet, but from a quick test it seems to be working great now! Thanks!

p.s. I think the constraint not being activated until the cursor moves into surface is a nice change, it feels a lot better in my opinion.

**Comment by ifreund** [comment]
Thanks for testing!
