### ISSUE TITLE
spawn multiple instances of status bar (yambar) for each output in river init

### ISSUE THREAD

**Issue by cmvanb** [riverwm/river#596]
Hello,

I have a multi monitor setup with river. I just started configuring [yambar](https://codeberg.org/dnkl/yambar). I am trying to get yambar to render on both of my monitors.

I understand yambar doesn't support multiple monitors natively. However, if I run two instances manually it works great. I start yambar (with wofi) on the primary monitor, then i switch focus and start a second instance on the secondary monitor. Once running, it works flawlessly. Of course, doing this manually is not satisfactory; it should be run automatically on startup.

I tried the following in my river init script:

```
riverctl spawn yambar && riverctl focus-output next && riverctl spawn yambar
```

Although the commands are run sequentially,  both yambars appear on my secondary monitor. I assume the spawn command is running it's executable concurrently, so there is a race condition and the focus switch command completes first.

Any ideas how I can make this work?

Thanks for any advice!

PS: Apologies if this issue is unwanted here, I wasn't sure if I should post it to the yambar repo or here. Since I am working with `riverctl` it seemed the more natural place to ask.

**Comment by MaxVerevkin** [comment]
Does this work?

```
riverctl spawn yambar && sleep 0.5 && riverctl focus-output next && sleep 0.5 && riverctl spawn yambar
```

**Comment by ifreund** [comment]
I don't intend to solve this race condition in this iteration of river's interface, especially since this can be solved client side by yambar.

**Comment by cmvanb** [comment]
Using `sleep` works. I was trying to avoid it since it's a hack, but I guess that's what unix ricing comes down to. Thanks for the input!

**Comment by adamcstephens** [comment]
> (Is there an open feature request for yambar?)

https://codeberg.org/dnkl/yambar/issues/26

**Comment by dnkl** [comment]
My own workaround is to use two different configs. They're (almost) identical, but have different `monitor` values. Then I launch yambar with `yambar --config <path>`.
