### ISSUE TITLE
Build fails with exit code 1 (Fedora linux)

### ISSUE THREAD

**Issue by Infinitybeond1** [riverwm/river#603]
This is the output from the `zig build -Drelease-safe -Dxwayland=true --prefix ~/.local install`

```bash
The following command exited with error code 1:
pkg-config --variable=pkgdatadir wayland-scanner 
error: the following build command failed with exit code 1:
/home/luke/Temp/river/zig-cache/o/0d8ded01666cace97b0dd68ced7d7048/build /usr/bin/zig /home/luke/Temp/river /home/luke/Temp/river/zig-cache /root/.cache/zig build -Drelease-safe -Dxwayland=true --prefix ~/.local install
```

I have run `git submodule update --init` before trying to compile, and i have verified that pkg-config is installed`

**Comment by novakne** [comment]
You're missing wayland-scanner, I don't know anything about fedora but with a quick search it seems that it is in the `wayland-devel` package, did you installed it?

**Comment by secteur0** [comment]
> I don't know anything about fedora

`$ dnf provides wayland-scanner`

**Comment by ifreund** [comment]
This doesn't seem to be an issue with river
