### ISSUE TITLE
xwayland views do not support override-redirect changes

### ISSUE THREAD

**Issue by zakvf** [riverwm/river#609]
Some of my Xwayland applications start as override-redirect views, then change to normal views (specifically, the games Kero Blaster and ZeroRanger (the demo) running through Wine). https://github.com/WayfireWM/wayfire/issues/684 and https://github.com/swaywm/sway/issues/4600 are about the same unhandled override-redirect change. I don't think river handles this, though, so it is difficult to interact with these windows since they are unmanaged.

**Comment by ifreund** [comment]
Fixed in 6ef97eea241ecc5bec32e0cf820c3644692f5554
