### ISSUE TITLE
Monitor transform/orientation lost on system wake (sleep/resume)

### ISSUE THREAD

**Issue by ideasman42** [riverwm/river#615]
Currently I use a command on startup to set the monitor orientation:

`wlr-randr --output DP-1 --transform 270 --pos 2160,0 --output DP-2 --transform 90  --pos 0,0`

This works, however when the system goes to sleep and wakes up, the orientation is lost.

According  to wlr-randr developer, it's the responsibility of the compositor to restore the orientation: https://todo.sr.ht/~emersion/wlr-randr/13

**Comment by ifreund** [comment]
I'd suggest using [kanshi](https://git.sr.ht/~emersion/kanshi) if you want persistent output configuration.

**Comment by ideasman42** [comment]
kanshi works well, thanks (perhaps worth noting in the wiki that `kanshi` supports suspend/resume with river while others don't).

**Comment by ideasman42** [comment]
While I got kanshi working it's also not rotating the monitors on wake after sleep.
(even though the process was running).

**Comment by ifreund** [comment]
> While I got kanshi working it's also not rotating the monitors on wake after sleep.

That's strange, I use `transform 90` for one of my displays with kanshi and have never had issues with this. What exactly do you mean by sleep here? What is your full kanshi config? What river version are you running?

**Comment by ideasman42** [comment]
- River (latest git `0.2.0-dev.91+2df2151`)
- `kanshi 1.2.0-3`

Full config (which works when I first run `kanshi`).

`~/.config/kanshi/config`

```
profile {
    output DP-1 transform 270 position 2160,0
    output DP-2 transform 90  position 0,0
}
```

----

Suspend is done by running:

`systemctl suspend`

Strangely, if I suspend & resume after 5-10 seconds or so (even without kanshi running), the monitor orientation is correct.

If I resume after being suspended for a long time (hours / overnight) the orientation is incorrect.

**Comment by ideasman42** [comment]
Posting a workaround here:

I managed to setup a systemd service to rotate the monitors on resume:


Create `/etc/systemd/system/i42-on-wake-for-wayland.service` and run:

`sudo systemctl enable i42-on-wake-for-wayland`

File contents:
```
[Unit]
Description=Run this after wake
After=suspend.target hibernate.target hybrid-sleep.target suspend-then-hibernate.target

[Service]
Type=oneshot
ExecStartPre=/bin/sleep 2
ExecStart=wlr-randr --output DP-1 --transform 270 --pos 2160,0 --output DP-2 --transform 90 --pos 0,0
Environment=WAYLAND_DISPLAY=wayland-1
Environment=XDG_RUNTIME_DIR=/run/user/1000

[Install]
WantedBy=suspend.target hibernate.target hybrid-sleep.target suspend-then-hibernate.target
```

**Comment by leroycep** [comment]
Silly question, have you tried using [the monitor's description instead of it's name](https://github.com/alex-courtis/way-displays/blob/master/doc/configuration.md#on-names-and-descriptions)? I realized today that I was using the name, which doesn't remain stable if the monitor has to reconnect or something.

**Comment by ifreund** [comment]
It seems likely that the root cause of this was https://todo.sr.ht/~emersion/kanshi/100, I think this should work with kanshi 1.5.1 or newer.
