### ISSUE TITLE
No cursor image when `imv` is full screen and `hide-cursor when-typing enabled`

### ISSUE THREAD

**Issue by MaxVerevkin** [riverwm/river#616]
Cursor is invisible when [`imv`](https://sr.ht/~exec64/imv/) is full screen. It works as expected if `hide-cursor when-typing` is disabled.

**Comment by ifreund** [comment]
This an imv bug. The `wl_pointer.enter` event of the wayland protocol states

> When a seat's focus enters a surface, the pointer image is undefined and a client should respond to this event by setting an appropriate pointer image with the set_cursor request.

imv doesn't have a single `wl_pointer_set_cursor()` call in its codebase from a quick grep.

**Comment by MaxVerevkin** [comment]
Okay. But just to note, it works in `sway`.

**Comment by ifreund** [comment]
I think that working around this imv bug in river would be less beneficial to the wayland ecosystem at large than reporting it to imv would be.

**Comment by ifreund** [comment]
https://todo.sr.ht/~exec64/imv/19
