### ISSUE TITLE
[Feature Request] Ability To Exclusivly Set View To View Padding

### ISSUE THREAD

**Issue by p0da** [riverwm/river#621]
Would it be possible to add a third padding option to rivertile to exclusively dictate the padding between two views? Currently view-padding will set the padding between two views and between the view and the layout area edge. Whereas I would only like the former behavior.

**Comment by Leon-Plickat** [comment]
rivertile is feature complete, so you'll have to use a different layout generator. For example, [mine](https://git.sr.ht/~leon_plickat/stacktile) implements gaps differently.
