### ISSUE TITLE
XKB_DEFAULT_LAYOUT br(nodeadkeys) makes river unusable

### ISSUE THREAD

**Issue by souxd** [riverwm/river#622]
Setting this env before starting river wont let me use my keyboard anymore, not even to swap tty.

**Comment by souxd** [comment]
> Does `xkbcli compile-keymap --layout br --variant nodeadkeys` return an error?
> 
> (No need to post the full output here, if there is more than a few lines, it worked)

It works. Nodeadkeys works fine except for the accents being in the wrong place and not letting i combine accents with letters. With the default layout without variants i can only use accents in gtk applications and it works fine there but i need to use alt gr to actually input accents everywhere else like the terminal, keepassxc and the launcher menu

**Comment by souxd** [comment]
Im starting to think this is a wayland issue but its been a while ive used wayland so i dont remember it doing that, ill test with different wm and DEs to check if its a river, wlroots or wayland issue

**Comment by calvinreu** [comment]
did You try 
> export XKB_DEFAULT_LAYOUT= your_layout

 in your login manager file or wathever starts your riverwm session it worked for me but note that it has to be executed before river starts this should work with the XKB_DEFAULT_OPTIONS as well hope I could help

**Comment by souxd** [comment]
I'll close this issue since its not related to river and thanks for the attention i really appreciate it
