### ISSUE TITLE
[Feature Request] Expansion of the "filter list" Concept To Other Features

### ISSUE THREAD

**Issue by p0da** [riverwm/river#625]
Currently river only seems to support the usage of two features (CSD, float) in conjunction with filter lists, would it be possible to expand the supported feature set to include other items such as dimension/location (floating views only), and tagmasks? This would synergize especially well with https://github.com/riverwm/river/issues/428 aswell.

**Comment by Leon-Plickat** [comment]
> This would synergize especially well with #428 aswell.

Not really.

Filters are something you set *before* the affected windows spawn, while unique window identifiers are only known after that.

**Comment by p0da** [comment]
Thanks for the correction, I was under the impression that the unique identifier would be assigned to the view before it spawns allowing it to be referenced in the filter.

**Comment by Leon-Plickat** [comment]
> unique identifier would be assigned to the view in a predictable/preset manner

That would be redundant with the app-id.

Unique window identifier would be completely random. The idea is to have a way to refer to one specific window between clients. Even if you had two completely identical windows, their identifiers would differ, giving you a way to still target each of them explicitly.

What you have in mind is a way to target a specific *class* of window, which is completely orthogonal to this and a use case already covered well enough by app-ids.

**Comment by p0da** [comment]
Wouldn't it also be useful to have an additional third reference element (after app-id/title) in the case of name collisions on the first two as the unique identifier doesn't necessarily have to be randomized, or is there something I am overlooking?

**Comment by Leon-Plickat** [comment]
app-id "name collisions" are expected and part of the design. If the same application (or multiple of the same application) opens multiple windows, they will have the same app-id. That's the point of the app-id, hence the name.

What you are overlooking is that we can not assign a hypothetical third identifier to windows, that is both different for windows of identical app-ids yet also predictable. The app-id and *maybe* the title are basically the only things we as the user know about a window before it shows up. We don't have any data two generate different yet predictable identifiers here.

Also, I really don't see how that would be useful in any way. The app-id and title are more than enough to satisfy all common matching needs, anything beyond that is fringe/hacky at best.

**Comment by p0da** [comment]
Got it, thanks for the clarifications.

**Comment by p0da** [comment]
@ifreund Any reason on the closure?

**Comment by ifreund** [comment]
@p0da I don't intend to implement this feature request, hence the closure.

I do intend for these use-cases to be satisfied, but through a different interface. It might take me a while to get around to implementing it.
