### ISSUE TITLE
Broken pipe on shutting down

### ISSUE THREAD

**Issue by dkwo** [riverwm/river#626]
On void linux, I start river in `.bash_profile` with
`exec gpg-agent --daemon river > ~/Projects/wmlogs/river-${timestamp}.log 2>&1`.
I noticed that, when I close river (by shift-alt-Q), it logs the following:
```
info: shutting down                                                             
(EE) failed to read Wayland events: Broken pipe
```
Of course this is not a problem for me, I was just curious if it's expected.
Thanks.

**Comment by ifreund** [comment]
> (EE) failed to read Wayland events: Broken pipe

This log message is not printed by river. It's probably printed by some wayland client you are running that is open when river exits and closes the the connection to all clients.

Anyhow, yes it is expected.

**Comment by dkwo** [comment]
I see, thanks for explaining this.
