### ISSUE TITLE
Ability to disable middle mouse button

### ISSUE THREAD

**Issue by actualdankcoder** [riverwm/river#627]
Hi, i've tried to disable the middle mouse button on my touchpad via the `middle-emulation` option, however it doesn't seem to work
here's my config
```
for pad in $(riverctl list-inputs | grep -i touchpad )
do
  riverctl input $pad events enabled
  riverctl input $pad tap enabled
  riverctl input $pad natural-scroll enabled
  riverctl input $pad disable-while-typing disabled
  riverctl input $pad middle-emulation disabled
done
```

**Comment by Ordoviz** [comment]
@actualdankcoder: You need to *enable* `middle-emulation` to remove the middle mouse button on clickpads. See libinput's documentation on [Middle button emulation](https://wayland.freedesktop.org/libinput/doc/latest/middle-button-emulation.html).
