### ISSUE TITLE
[Feature Request] Re-position cursor on resize

### ISSUE THREAD

**Issue by TripleK2004** [riverwm/river#628]
Since river only supports cursor resize from bottom right side, it will be visually helpful if the cursor also gets repositioned to bottom right edge of the window while resizing ( behaviour as dwm ). I am not sure if wlroots/wayland allows this. But it would be helpful with this behaviour

**Comment by Leon-Plickat** [comment]
> Since river only supports cursor resize from bottom right side

See #399 

> I am not sure if wlroots/wayland allows this.

We are the display server, we may do as we please. There are literally no restrictions to what we can put on screen.
