### ISSUE TITLE
Keyboard repeat after set-focused-tags

### ISSUE THREAD

**Issue by jeLee6gi** [riverwm/river#629]
I noticed that holding a key combination for `set-focused-tags` repeats when it leads to a change in the focused view. Depending on the application, this can lead to unwanted inputs in the application that comes into view.

When holding e.g. Super+1 to get emacs into view, emacs will tell me `s-1 is undefined`. If I do the same with obsidian (an electron note-taking app), it will start inputting 1s into the active window.

What makes this inconsistent is that the key combination is not repeated or sent to the active view at all if `set-focused-tags` does not lead to a view change. I don't know if everyone would consider this a bug, but I think shortcuts captured by river should not be sent to applications in any case to make it consistent and avoid unintended side-effects in applications.

**Comment by tiosgz** [comment]
This looks like if you had only the first commit from #611, although there may of course be a bug. What’s your exact river version?

> What makes this inconsistent is that the key combination is not repeated or sent to the active view at all if `set-focused-tags` does not lead to a view change.

This is ‘expected’, that is, it can easily be explained (but leaking eaten keys to the client is anyway a bug). There are two ways how a client can know a key is pressed: one takes place when the key is pressed (while the client is focused), the other when the client is focused (while the key is pressed).

**Comment by jeLee6gi** [comment]
Thank you, this is indeed already fixed in master. I was on `0.1.3` and just switched to `0.2.0-dev.96+78d96d1` for testing and key combinations are not repeated anymore after a view change.

**Comment by tiosgz** [comment]
Oops, just noticed that you wrote

> holding a key combination

so my note about ‘only the first commit from #611’ was somewhat wrong (it would apply if you released the keys and they kept repeating – but you held them, and this behaviour was present all the time up to #611).

**Comment by jeLee6gi** [comment]
Yeah, I only observed it when key repeat triggered for mapped key combinations until I released the keys and your PR works perfectly for me.
