### ISSUE TITLE
How to launch wofi on river?

### ISSUE THREAD

**Issue by pigeon46** [riverwm/river#630]
I added this on the init file and rofi isn't showing.

``riverctl map normal Super P wofi --show drun``. Please point where I did wrong.

**Comment by novakne** [comment]
You forget  `spawn`, `riverctl map normal Super P spawn wofi --show drun`

**Comment by tiosgz** [comment]
> `riverctl map normal Super P spawn 'wofi --show drun'`

(inserted quotes to hopefully finally fix it)

**Comment by pigeon46** [comment]
That worked perfectly. Thanks
