### ISSUE TITLE
Using Waybar with RiverWM.

### ISSUE THREAD

**Issue by pigeon46** [riverwm/river#631]
How do I have the tags appear on waybar, or the window titles for that matter?

**Comment by ifreund** [comment]
This issue tracker is not for generic questions on using river or related software, it's for bug reports.

Please refer to the waybar documentation or consider asking on IRC.

**Comment by pigeon46** [comment]
@ifreund thanks for ponting me to the right direction. But could you tell me what's IRC? I've only asked here as a last resort since  I couldn't find any discord server or other modes of communication. And the only subreddit there is is inactive. Anyway apologies for the trouble.

**Comment by novakne** [comment]
There is a link for the IRC channel #river in the beginning of the README

**Comment by adamcstephens** [comment]
Waybar has a dedicated wiki page for river which provides the reference for the relevant sections of the config. 

https://github.com/Alexays/Waybar/wiki/Module:-River
