### ISSUE TITLE
Implement touch drags

### ISSUE THREAD

**Issue by ifreund** [riverwm/river#634]
River now has basic touch support as of #632, but touch drags are not yet implemented.

I took an incomplete stab at this here but it's pretty tricky and I don't have hardware to test on: https://github.com/riverwm/river/tree/touch-drags

Related: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3452

**Comment by frnco** [comment]
Well, I do have a touchscreen (Dell Inspiron 2-in-1 has a 15" 1080p touch display). I do use the touch display a lot, to the point I set RiverWM aside in favor of Sway to keep using it. Still, I really like River. I never tried Zig so other than testing I won't be of much help, but I'll try to do what I can.

I noticed the branch `  touch-drags`  (https://github.com/riverwm/river/commit/683585bb8772cf893c584721e3dc98d2d539ef01) is stale, though there's only one commit in there that's not in ` master` . Not sure what that commit does an whether I should test it or not.

One early feedback though, the `  wlroots 0.16`   requirement is being a bit of a pain to deal with. I'm on Arch Linux, which is on ` 0.15`, and I'm currently considering the best way to install ` 0.16`  without risking any issues with my current setup. Once I deal with that I'll check the code and try to figure out how I may be of help. And then I'll get to the build-test-patch-repeat cycle. First I'll try testing it nested in Sway, but I have a feeling Sway will interfere, so I'll probably test River by itself as much as I can.

It would help me a lot if you could give me any pointers on what code I should check, what may (or may not) be working, things I should keep in mind etc.

Other than that, as I said, my knowledge of Zig is absolutely zero. I do have some good 20 years of experience as a programmer, and I know enough languages to not bother listing them all, so I know I'll be able to do stuff in Zig, though it'll be messier and take more time than usual (At least I hope so, considering I did manage Haskell and LISP). 

I'm not sure how much time I'll be able to put on this though, so I really appreciate any help.

**Comment by Leon-Plickat** [comment]
if you have any problems / questions, feel free to drop by on IRC

**Comment by ifreund** [comment]
I just opened #747 which implements touch drags. If anyone with a touchscreen could test that PR and give feedback on whether it works or not that would be very helpful.
