### ISSUE TITLE
Error while building river

### ISSUE THREAD

**Issue by matheusAMDS** [riverwm/river#636]
I have Zig version 0.9.1, and just clone this repo. When trying to build it I got this error: `/home/matheusandrade/Downloads/git/river/build.zig:7:35: error: unable to load '/home/matheusandrade/Downloads/git/river/deps/zig-wayland/build.zig': FileNotFound
const ScanProtocolsStep = @import("deps/zig-wayland/build.zig").ScanProtocolsStep;`

**Comment by Leon-Plickat** [comment]
You also need to initialize the submodules before building, just like it says in the README.

```
git submodule update --init
```

Also make sure you have all the required dependencies.
