### ISSUE TITLE
focus is not updated upon changing workspace and moving cursor

### ISSUE THREAD

**Issue by dkwo** [riverwm/river#639]
On 0.1.3, with rivertile and `riverctl focus-follows-cursor normal`, open two windows (a,b) in the same space, change focus to another space, move cursor, change focus back to the window: the old window (a) is still on focus, not the one (b) where the cursor is now. Is there any option such that I would end up with focus on window (b)?

**Comment by p0da** [comment]
May want to look at https://github.com/riverwm/river/commit/50c9e3d81bcd0f5d7aba9f136aece36960ed197e

**Comment by dkwo** [comment]
Thank you, that's quite close to what I meant.
