### ISSUE TITLE
double usage of key when switching mode with same key

### ISSUE THREAD

**Issue by calvinreu** [riverwm/river#641]
I used two scripts
I am using wofi usw in those scripts but thats not relevant
quit_menu
> riverctl enter-mode normal
> quit something

launch menu
> riverctl enter-mode menu
> start something

key config
>riverctl map -release normal $MOD $MENU spawn ".config/scripts/launch_menu.fish" 
>riverctl map -release menu $MOD $MENU spawn ".config/scripts/quit_menu.fish"
>riverctl map -release menu None Return spawn ".config/scripts/quit_menu.fish"

when i press the key $MENU key in my case Super_R it works most of the time but sometimes it  instantly quits after launching i fixed it by adding sleep 0.05 before riverctl enter-mode. I would propose there should be a very small delay before switching mode to prohibit this behaviour. If this would be accepted and someone can tell me where the file with the command is I would create an merge request

**Comment by ifreund** [comment]
I can't reproduce this issue and can't see how it could possibly occur from reading the code unless something below river in the input stack were to send duplicate release events.

As for the proposed fix, if something is racy like this adding a small delay does not resolve the issue but only make it less common. Such a solution won't be accepted into river.

Can you still reproduce this? Does it only happen with `-release` mappings?  Can anyone else reproduce this?

**Comment by ifreund** [comment]
If anyone can reproduce this on river's master branch please let me know and I will have another look.
