### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by mizzunet** [riverwm/river#642]
river just crashed. I was playing a video in mpv.

river version: river-git 0.1.0.r103.gdb366e9-1
coredump gdb: https://0x0.st/oQ-K.txt
log: https://0x0.st/oQ-K.txt

**Comment by ifreund** [comment]
Stack traces and safety checks are awesome! 

Thanks for the report, should be fixed by 7402cb8

**Comment by ifreund** [comment]
Related: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3646
