### ISSUE TITLE
OBS inner-display doesn't match window width when first spawned on a scaled monitor

### ISSUE THREAD

**Issue by fifty-six** [riverwm/river#644]
When I open obs on my monitor with 2x scaling, it spawns initially basically covering the whole screen, despite being tiled 
![image](https://user-images.githubusercontent.com/10470872/176989216-15acb571-3b94-4676-a0d3-364ae363e595.png)

If I put it into floating and resize it then I can control most of the window's size, but you can then see that the inner display rendering doesn't match the window size.

![image](https://user-images.githubusercontent.com/10470872/176989203-d2b00720-b932-46d3-9d86-6bc2475cc595.png)

A workaround is that spawning obs on other monitors seems to be fine, and moving it between monitors also works. Also spawning it on the scaled monitor, but then moving
it to another and back fixes the scaling, as pictured:

![image](https://user-images.githubusercontent.com/10470872/176989254-9c15b138-9b20-403e-be8b-b8b4dd8e27d2.png)

**Comment by Leon-Plickat** [comment]
This sounds like a client bug to me, not a river bug. Clients are themselves responsible for the dimensions of their surfaces.

I'll reopen if you can confirm that it works correctly in other compositors.

**Comment by fifty-six** [comment]
sway
![sway](https://user-images.githubusercontent.com/10470872/177024000-23ad3e8e-6627-44f5-ba5f-6f6f291a682c.png)

wayfire
![2022-07-02T23:40:40,759314746-04:00](https://user-images.githubusercontent.com/10470872/177024008-6d3150b2-3028-4055-abd6-3d95dfe534d9.png)

It's running under wayland, checked with xeyes.

**Comment by fifty-six** [comment]
Not quite sure what commit ended up doing it but this is fixed now!
