### ISSUE TITLE
Autostarting applications on login

### ISSUE THREAD

**Issue by itsKia2** [riverwm/river#647]
riverwm version: 0.1.3
Arch Linux Kernel: 5.18.9-zen1-1-zen

How do we autostart an application (such as terminal e.g kitty) on login to riverwm on tag 2. Is it possible so far or would a feature request be needed to implement this in the future?

**Comment by novakne** [comment]
You can autostart an application in your `init` file since it's just a shell script, just use `riverctl spawn 'foo'` or `foo &`  but you can't assign it to a tag, this feature is not yet implemented.

**Comment by ifreund** [comment]
See #472, #201
