### ISSUE TITLE
how to disable title bar on zathura

### ISSUE THREAD

**Issue by tienbuigia** [riverwm/river#658]
I'm using Voidlinux and installed river (from source: zig build...).
Somehow my zathura have title bar.

![1658660512-wayshot](https://user-images.githubusercontent.com/62953368/180644074-e346319b-516e-48bc-9b4f-7edb6ea50208.png)

How can I remove it?

**Comment by novakne** [comment]
You can't, see the [FAQ](https://github.com/riverwm/river/wiki#how-do-i-disable-gtk-decorations-eg-title-bar=)

**Comment by tienbuigia** [comment]
oh ok, sorry I read the faq and forgot.
