### ISSUE TITLE
Dropdowns/popups auto-closed instantly

### ISSUE THREAD

**Issue by icp1994** [riverwm/river#662]
https://user-images.githubusercontent.com/15713555/182020108-9f8a1441-da73-496c-93f3-a631d2aaedbc.mp4

I have had this issue for some time now, in Firefox(Wayland) and Vivaldi(XWayland). The dropdowns won't stay open. In Vivaldi it gets fixed temporarily after I restart Vivaldi. It could very well be a non river issue but if someone can point at what could be causing this, that would be great.

My system is up-to-date with void linux packages except for river 0.1.3 which I had to build locally. The logs for the recording session is at https://0x0.st/oe8T.log

**Comment by novakne** [comment]
I can't saw the video, not sure if it's from me or not, but on firefox could it be related to all this issues?

https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3449

https://bugzilla.mozilla.org/show_bug.cgi?id=1769323

https://bugzilla.mozilla.org/show_bug.cgi?id=1769457

Also if you use `hide-cursor timeout` with a small timeout it makes popup disappears quickly

**Comment by icp1994** [comment]
Yep, most likely related. I get the right-click context menu issue too in both my browsers.

**Comment by ifreund** [comment]
As evident from novakne's comment, this is a wlroots bug and is already fixed upstream. When wlroots 0.16.0 is released and river is updated to use it we can close this issue.
