### ISSUE TITLE
High idle CPU usage with wayvnc

### ISSUE THREAD

**Issue by chcore** [riverwm/river#667]
When running river, wayvnc consistently uses 30-40% of a CPU core when no VNC clients are even connected. For comparison, CPU usage under the same conditions is negligible when running Sway.

I am experiencing this on two different machines. Is this happening to anybody else? I would expect the load to be very low, if not nothing, while no clients are connected.

**Comment by Leon-Plickat** [comment]
Likely related to river not doing full damage tracking yet.

**Comment by chcore** [comment]
You may be onto something, the CPU usage is similarly high when there is a lot of "damage" when using sway (again, when no clients are connected). I might raise a wayvnc issue for this.

**Comment by chcore** [comment]
Thanks Leon-Plickat.

Worked around the issue by having wayvnc run only when needed via systemd socket activation. Hoping #206 will be implemented soon.
