### ISSUE TITLE
[rivertile] vertical monitor default split

### ISSUE THREAD

**Issue by KMIJPH** [riverwm/river#670]
Hey,
not sure where to put this, so it will be an issue for now.

The Problem:
Right now (as far as I understood), rivertile will always split the available space horizontally when creating new views (I think that's what they are called, right?. That really sucks for vertical monitors.
I realize it might be a niche problem (as most people don't use vertical monitors), but I propose some kind of check to figure out which way the available space should be split.

Something like [this](https://codeberg.org/KMIJPH/rivertile/src/branch/main/main.zig):
```
// check width/height
if (ev.usable_width > ev.usable_height) {
    output.main_location = default_main_location;
} else {
    output.main_location = default_secondary_location;
}
```

Please keep in mind I've not written a line of zig in my life, so this could probably solved more elegantly.
Maybe it'll help someone.
Cheers

**Comment by Leon-Plickat** [comment]
> rivertile will always split the available space horizontally when creating new views

You can change rivertiles split direction. In the example configuration, this is bound to Super plus the arrow keys.

**Comment by KMIJPH** [comment]
Ah cool, didn't see that, thanks. However I still don't like to do it manually.

**Comment by Leon-Plickat** [comment]
> However I still don't like to do it manually.

rivertile is feature complete, so won't get any new functionality. However layouts are implemented as an external program exactly because we want to allow users to easily create their own layouts.

So having your own local mod of rivertile is a perfectly valid and supported use case.
