### ISSUE TITLE
HDR

### ISSUE THREAD

**Issue by RossComputerGuy** [riverwm/river#672]
As the title says HDR would be a neat feature to have, this would involve using colord for profiles and it appears that [`libplacebo`](https://code.videolan.org/videolan/libplacebo) is capable of the rendering. I am not sure what changes would be needed but on the user side, enabling HDR might be as simple as enabling that profile, possibly could be done with an existing protocol but I am unsure.

**Comment by ifreund** [comment]
There is significant work that needs to happen upstream in wlroots first before river can support this. See for example weston's roadmap here: https://gitlab.freedesktop.org/wayland/weston/-/issues/467. Someone does seem to have started an implementation in wlroots but it doesn't seem to be actively developed at the moment: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/2353.

**Comment by RossComputerGuy** [comment]
> There is significant work that needs to happen upstream in wlroots first before river can support this.

Yeah totally, I hope that in the next year we see what is required to at least get a partial implementation. I've got an HDR monitor and an RTX 2060 (will Wayland working fine) so I should be able to test this implementation.

**Comment by ifreund** [comment]
I don't think having this issue open is helping anything. This will be worked on for river after support is added to wlroots.
