### ISSUE TITLE
Mouse cursor disappears

### ISSUE THREAD

**Issue by marcosgnaolin** [riverwm/river#682]
Hello, I installed river on Fedora 36 using this copr: https://copr.fedorainfracloud.org/coprs/alebastr/river/

It works good and looks promising but I have a critical issue with the mouse pointer. When river starts it works, it moves and acts normally. Then I open a terminal window and the cursor disappears. I open Firefox and it stays hidden. It keeps working though. If I blindly move it on links they behave normally... but the system is obviously unusable.

Any hints?

**Comment by marcosgnaolin** [comment]
Ok nevermind, I realized it's a common issue on wlroots-based window managers running on nvidia hardware.

**Comment by pfr-dev** [comment]
I'm experiencing the same issue but I dont have Nvidia hardware. It an old intel lapop with integrated graphics.
