### ISSUE TITLE
Change resolution/refresh rate

### ISSUE THREAD

**Issue by SkelyTony** [riverwm/river#683]
Hello, I've just stumbled upon riverwm and it looks great! Thank you for the great work. I have a 144hz monitor and i was wondering how to change the riverwm refresh rate. I've searched for it in the manpages but i didn't find anything useful.

**Comment by Leon-Plickat** [comment]
You need to use a program like [wlr-randr](https://sr.ht/~emersion/wlr-randr/) or [kanshi](https://sr.ht/~emersion/kanshi/).

**Comment by SkelyTony** [comment]
I know this is not related but is there a way to change xwayland cursor

**Comment by NickHastings** [comment]
> I know this is not related but is there a way to change xwayland cursor

Can do with riverctl. Eg `riverctl xcursor-theme whiteglass`
