### ISSUE TITLE
Timeshift and Gparted Err

### ISSUE THREAD

**Issue by niksingh710** [riverwm/river#684]
```
DISPLAY=:0 WAYLAND_DISPLAY=wayland-0 timeshift-launcher   took 2s 
localuser:root being added to access control list

(timeshift-gtk:105583): Gtk-WARNING **: 15:19:25.688: cannot open display: 
localuser:root being removed from access control list
access control enabled, only authorized clients can connect
SI:localuser:niksingh710
```

This launches polkit password prompt after putting password this error comes.

**Comment by ifreund** [comment]
This issue is caused by trying to run a graphical application as root. This is not a problem with river, but with the application and/or the way you are starting it.

**Comment by niksingh710** [comment]
Doing `sudo -E <command>` runs timeshift
But running like this does not persist the configuration e.g it does not create any snapshots.
