### ISSUE TITLE
Make sure that keyboard works before starting river

### ISSUE THREAD

**Issue by Ordoviz** [riverwm/river#688]
If you start river with `XKB_DEFAULT_LAYOUT=invalid river` or some other invalid XKB configuration, you won't be able to use any keyboard shortcuts, which usually means having to physically reboot your computer.

River already logs an error in this case, but exiting immediately would be better:

https://github.com/riverwm/river/blob/d4b2f2b0fc5766c8ae14a6f42fe76d058bfb3505/river/Seat.zig#L465

Sway used to have the same issue, see https://github.com/swaywm/sway/issues/4148.

I experienced this issue after [Arch Linux updated xkeyboard-config to the latest commit](https://github.com/archlinux/svntogit-packages/commit/7d3ec146335dc0de3304447eec2c37f8ac7e43a0), which broke my custom layout because [`level5(modifier_mapping)` was removed](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/commit/4a60b90f119db150132901bd13355611de67aa69).

**Comment by ifreund** [comment]
Fixed by 6a028639b84ea7c6e98f7831876457e64d54cb6a
