### ISSUE TITLE
Feature Request : bspwm like IPC for communicating to window manager

### ISSUE THREAD

**Issue by CoolnsX** [riverwm/river#689]
As an ex-bspwm user I like river very much cause of similar configuration style, but there are some feature that i strongly miss is the IPC. bspwm has bspc command that communicate to bspwm over a socket.
A similar approach is implemented in sway, so i m hoping for it in the river too..
Another feature I miss from bspwm is it's rules.. like u can set which application should be open on which workspace, their state etc.

**Comment by Leon-Plickat** [comment]
We already have IPC. We just implement it as Wayland protocols instead of using a separate socket. See the `protocols/` directory. All files in it that have "river" in their name are our custom protocols.
