### ISSUE TITLE
[Feature Request] Support for non-Latin keyboard layouts

### ISSUE THREAD

**Issue by TAforever** [riverwm/river#693]
Could you add support for non-Latin keyboard layouts so that if, for example, I have `XKB_DEFAULT_LAYOUT="us,ru"` configured, then when I use the Russian keyboard layout, keyboard shortcuts work. Such support is implemented in sway and hyprland.

**Comment by MaxVerevkin** [comment]
From `riverctl(1)`:

```
map [-release|-repeat|-layout index] mode modifiers key command
           Run command when key is pressed while modifiers are held down and in the specified mode.
           ...
           •   -layout: if passed, a specific layout is pinned to the mapping. When the mapping is checked against a
               pressed key, this layout is used to translate the key independent of the active layout
               •   index: zero-based index of a layout set with the environment variable XKB_DEFAULT_LAYOUT; see
                   river(1) for an example; if the index is out of range, the -layout option will have no effect
           ...
```

So in your case you will need to add `-layout 0` to your mappings. Or you can use `alias map='riverctl map -layout 0'`.

> hyprland

The last time I looked into it, `hyprland` required you to specify keycodes, did it change?

**Comment by TAforever** [comment]
Yes, hyprland 0.10.3 added this feature. It's good that this function already exists, I just had to read the manual. Well the question is over.
