### ISSUE TITLE
Document if condition for mapping command

### ISSUE THREAD

**Issue by Brixy** [riverwm/river#694]
Using a shell script for configuration is excellent.

Should we document how to use an `if` condition within a key mapping command—maybe in the wiki or the example config file?

```
riverctl map normal $mod+Shift I spawn '(
	if pgrep swayidle; then
		notify-send "Pkilling swayidle" && pkill swayidle
	else
		notify-send "Launching swayidle" &&
		swayidle -w \
		timeout 300 "waylock" \
		timeout 360 "wlopm --off \*" resume "wlopm --on \*"
	fi
)'
```

It took me some time to find out how this works because I tried it the other way round—mapping within an `if` condition.

**Comment by Brixy** [comment]
Totally ok! I’ll close this issue. The closed issue may serve as a reference.

**Comment by Leon-Plickat** [comment]
You can write something in the wiki though, if you like.
