### ISSUE TITLE
wofi rendering error

### ISSUE THREAD

**Issue by TAforever** [riverwm/river#697]
Actually, the problem is in the title. Tested in other wayland compositors and there is no such problem. I am attaching a screenshot.
![wofi](https://user-images.githubusercontent.com/52626363/190866635-99fdf207-1eae-4e19-80b3-4c7fab484638.png)

**Comment by Leon-Plickat** [comment]
Could you provide your wofi configuration? Otherwise there is no way for me to reproduce this.

**Comment by TAforever** [comment]
It's not about configuration. I moved the ~/.config/wofi directory to test. The effect is the same.

**Comment by Leon-Plickat** [comment]
Can you then explain what the rendering error is, so someone who does not use wofi and has no idea how the UI is supposed to look can spot it?

**Comment by TAforever** [comment]
In the first shot taken in hyprland, the wofi has a white border on all sides and the in-focus element does not go outside the window. In the second picture, river.
![wofi1_grim](https://user-images.githubusercontent.com/52626363/191807559-8239b879-fd13-4461-ab42-7926b6947d25.png)
![wofi2_grim](https://user-images.githubusercontent.com/52626363/191807588-9cd956ef-6323-4697-8bdd-09c73f399fcc.png)

**Comment by TAforever** [comment]
Even visually, you can see that the window in the river is smaller in height.

**Comment by TAforever** [comment]
I also noticed that if you run wofi with the --normal-window option, the window is drawn fine, but accordingly, since it has become a normal floating window, window decorations have appeared.

**Comment by ifreund** [comment]
In both of those screenshots exactly 12 items are visible. I don't see any evidence of a river bug, wofi does seem to have non-deterministic ordering of menu items though.

**Comment by Leon-Plickat** [comment]
Both look exactly the same on my end, with the sole difference that once has a border drawn by river, as expected.

**Comment by TAforever** [comment]
https://user-images.githubusercontent.com/52626363/191970491-16135ec2-4ad0-4287-8828-6d2e08c84883.mp4

**Comment by TAforever** [comment]
https://user-images.githubusercontent.com/52626363/191970557-4db4fc02-b6bb-4b96-b887-55249696c6f1.mp4

**Comment by TAforever** [comment]
https://user-images.githubusercontent.com/52626363/191971505-fe58343a-e4e6-45eb-9dec-5d51c09583d2.mp4

**Comment by TAforever** [comment]
https://user-images.githubusercontent.com/52626363/191971864-c050b373-2622-4668-8327-7856416a9a71.mp4

**Comment by TAforever** [comment]
https://user-images.githubusercontent.com/52626363/191972691-a0e872e5-2532-48d6-8f69-c7c905eb1a29.mp4

**Comment by Leon-Plickat** [comment]
Ah ok, now I can see it and I definitely can reproduce it. Thanks for the videos.

**Comment by Leon-Plickat** [comment]
Ok, so I can only reproduce on the larger of my screens.

Here is the abbreviated `WAYLAND_DEBUG` output:
```
[1806177.761]  -> zwlr_layer_surface_v1@33.set_size(50, 40)

[1806178.043] zwlr_layer_surface_v1@33.configure(34540, 50, 40)
[1806178.052]  -> zwlr_layer_surface_v1@33.ack_configure(34540)

[1806184.753]  -> zwlr_layer_surface_v1@33.set_size(1280, 432)
[1806184.794]  -> wl_surface@25.commit()

[1806184.965] zwlr_layer_surface_v1@33.configure(34542, 1280, 432)
[1806184.974]  -> zwlr_layer_surface_v1@33.ack_configure(34542)

[1806206.270]  -> wl_surface@25.damage(0, 0, 1228, 414)

[1806206.280]  -> wl_compositor@5.create_region(new id wl_region@36)
[1806206.289]  -> wl_region@36.add(0, 0, 1280, 466)
[1806206.298]  -> wl_surface@25.set_opaque_region(wl_region@36)

[1806206.313]  -> wl_compositor@5.create_region(new id wl_region@37)
[1806206.321]  -> wl_region@37.add(-10, -10, 1300, 486)
[1806206.330]  -> wl_surface@25.set_input_region(wl_region@37)

[1806239.152] zwlr_layer_surface_v1@33.configure(34543, 1280, 432)
[1806239.162]  -> zwlr_layer_surface_v1@33.ack_configure(34543)
```

Their math w.r.t. surface size seems to be a bit messed up? Smells like a client but to me. Note that rivers layer shell implementation is stricter than that of sway, so it may expose bugs previously unnoticed.

**Comment by TAforever** [comment]
Today the problem was solved in some magical way for me.
