### ISSUE TITLE
Touchpad not working if mouse is connected

### ISSUE THREAD

**Issue by yuval-benard** [riverwm/river#700]
When an external mouse is connected to the laptop the touchpad input doesn't register.
The moment the mouse is disconnected the touchpad works again.

**Comment by Leon-Plickat** [comment]
libinput allows to disable the events of touchpad devices automatically when an external mouse is connected. This seems to be the default configuration for your device on your system. You can permanently enable events for that device with the following command:

```
riverctl input <name of device> events enabled
```
