### ISSUE TITLE
[Feature Request] Regex for title and app-id filters

### ISSUE THREAD

**Issue by aivarsV** [riverwm/river#703]
While writing init file and browsing through river source, I noticed, that `app-id` and `title` for float-filter and csd-filter are compared one-to-one exactly. Has noone suggested adding at least minimal regex/globbing (dot for any single caracter and asterisk for any number of any caracter) support for filters? How much work it would require to implement something like this and would it be in line with river project goals?

As an example on use-case, I had issue with firefox sharing indicator back, when I was using sway. I set up floating filter for that window, providing exact window title. After firefox update they changed hyphen in window title and my setup broke. This a few times until I replaced exact title with regex.

**Comment by Leon-Plickat** [comment]
We have talked about this on IRC a few weeks ago. Not sure about full regex, but at least minor globbing is something we'd like to have. How much work an implementation requires strongly depends on how advanced you want to get: If all you want is multi-char globbing strictly at the end and/or start of the match string, it's probably no more than twenty lines. Anything more advanced will require more code though.

**Comment by aivarsV** [comment]
I guess, that wasn't me in IRC.
Now, that you mention, multi-char globbing at start/end of the match string might do the trick in most cases.

**Comment by sfrique** [comment]
Also it would be nice to be able to match `title`, `class` and `app-id`  for combinations
