### ISSUE TITLE
focus-output next with Super+Shift 0xff51 works but not Super+Shift 0xff53

### ISSUE THREAD

**Issue by ghost** [riverwm/river#705]
So I like using left and right arrow for changing focus. I have Super 0xff53 for changing focus to the next view so naturally I tried Super+Shift 0xff53 focus-output next which doesn't work.

This is strange because using 0xff53 works for my changing focus function. I can have focus-output working by only changing the 0xff53 into 0xff51 (my left arrow key) and that works. Super+Shift 0xff53 is not used anywhere else and I ensured there should be no typo. My only thought is maybe my keyboard has a limit on pressing those three keys at the same time? Its a thinkpad E15 i7 using Gentoo.

Here is the config.
[init.txt](https://github.com/riverwm/river/files/9763850/init.txt)

**Comment by ifreund** [comment]
There's no reproducible problem on river's end here and the provided information points to an issue lower in the input stack than river.
