### ISSUE TITLE
Enabling touch support?

### ISSUE THREAD

**Issue by cynicsketch** [riverwm/river#707]
I see that "basic touch support" is implemented, but it doesn't seem to be enabled by default on my system. I know it isn't a driver issue because touch works fine on Sway.

Documentation on this is... absent, to say the least, so I came to ask here. I assume this is a general libinput thing, and I see in my `$HOME/.config/river/init` that I've worked with libinput at least once to configure my touchpad, but I forgot how I did it because I probably did so while sleep deprived...

**Comment by alex-courtis** [comment]
Touch support was added ~2022 06

Which version are you running? The latest release 0.1.3 is ~2022 02

I'm running master for touch support.

**Comment by cynicsketch** [comment]
https://pkgs.alpinelinux.org/flag/testing/river/0.1.3-r3

0.1.3-r3, should theoretically work.

**Comment by cynicsketch** [comment]
Ah...

**Comment by novakne** [comment]
> When is it expected to be ready for a stable release?

Probably after the release of wlroots 0.16,  no idea when it is though
