### ISSUE TITLE
send-to-output and focus behaviour

### ISSUE THREAD

**Issue by flub** [riverwm/river#709]
With a multi-monitor setup I am very used to a workflow where when I send a focussed view to a different output the view remains focussed.  River does not do this which requires me to do a bunch of other operations before I have the view selected again.

I assume this is partially because river keeps the tags of the view the same, so the moved view might not even be visible on the new output.  This could potentially be rectified by computing the new tags as `current_view_tags || selected_tags_on_new_output`.

Wondering how to change this backwards compatibly there are a few options.  One is to maybe add a new option to `send-to-output` that enables this behaviour, e.g.:

```
send-to-output next|...|left|name [focus] [preserve-tags|merge-tags|output-tags]
```

* The optional `focus` argument would indicate to move focus to the new output.
* The optional `output-tags|merge-tags` would give some customisation of how to handle the tags on the view when `focus` is used:
  * `preserve-tags` would be the current behaviour of keeping the tags on the view the same.  This would be incompatible with the `focus` option.
  * `merge-tags` would OR all the tags of the view with the selected tags on the new output.
  * `output-tags` would use the selected tags from the new output only.

Is this a reasonable feature request?  Too complicated or too niche?  Or did I entirely miss how to do something like this already.

**Comment by Toesmasher** [comment]
@flub I don't know if you're interested, but It sounds like I've got similar problems. I haven't found a solution for the tags issue, but I did sort of get the focus behavior as follows:

```
# Move windows between outputs
riverctl map normal Super+Shift H spawn "riverctl send-to-output previous && riverctl focus-output previous"
riverctl map normal Super+Shift L spawn "riverctl send-to-output next && riverctl focus-output next"
```

**Comment by flub** [comment]
@Toesmasher huh, calling riverctl recursively is a clever idea!  I was also considering making a suggestion to allow multiple commands to solve some of this, but didn't think of your hack.  Nice.

**Comment by flub** [comment]
Going to close this issue as there seems to be no feedback on whether something like this is desirable and worth exploring.  I probably should have taken a stab at implementing this straight away, by now I'm starting to be more used to the existing approach.

**Comment by Cornelius-Figgle** [comment]
I don't know if this was ever properly raised but I also have to same issue with the focus not following the window when move to another monitor

@flub's suggestion to add a `focus` argument seems pretty good imo
