### ISSUE TITLE
Mouse cursor dissappearing on Pinebook-pro 

### ISSUE THREAD

**Issue by defini-tiv** [riverwm/river#710]
Touchpad seems to work fine until a Window is spawned. The cursor seems to be behind the Terminal because its visible in front of the Background, but dissapears behind the window.

[river.log](https://github.com/riverwm/river/files/9846731/river.log)

**Comment by Leon-Plickat** [comment]
Can you describe this in more detail? I unfortunately don't quite get what issue you are trying to report here. When is the cursor disappearing? How is the cursor disappearing? Can you provide a river debug log? Have you tried forcing software cursors?

> Is a workaround Planned for the known issue?(Yes, it is a wlroots bug. But workarounds seem possible (https://github.com/swaywm/wlroots/pull/1537))

I don't think the PineBook has an nvidia card, therefore this is likely unrelated. The funny thing about graphics drivers is that they can cause what appears to be the same problem in a lot of different ways. Also that workaround is already merged.

**Comment by defini-tiv** [comment]
I really thought it was basically the same issue as with the nvidia cards. I updated the issue to describe the problem and attached a logfile.

I use river 0.1.3 did not find a "software cursor" option in the manpage of riverctl. How can i enable it?

**Comment by ifreund** [comment]
There's not much we can do about a wlroots bug, which seems likely the case here. You could retry river master branch which now depends on wlroots 0.16.0 to see if that newer wlroots version has fixed it.

Setting `WLR_NO_HARDWARE_CURSORS=1` will force software cursors: https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/docs/env_vars.md
