### ISSUE TITLE
Mpv not starting fullscreen.

### ISSUE THREAD

**Issue by cronyakatsuki** [riverwm/river#711]
From what I may have read in other issues this might be a known issue.

My problem is that mpv with option `fs` set in `~/.config/mpv/mpv.conf` doesn't start fullscreen.

Any way to fix this?.

**Comment by Leon-Plickat** [comment]
This is a known issue. River ignores all window properties set before the window is mapped.

**Comment by ifreund** [comment]
Fixed in 096e175ceca0b0ce313da58cd2d00b189f5ac458
