### ISSUE TITLE
River not starting 

### ISSUE THREAD

**Issue by Eko450-eng** [riverwm/river#713]
Hi guys, I'm trying to get Riverwm working on my Arch system when `river` after the build I get:
`info: initializing server
info(wlroots): [backend/x11/backend.c:397] Creating X11 backend
info(wlroots): [backend/x11/backend.c:480] X11 does not support shared pixmaps
error(wlroots): [backend/x11/backend.c:609] Failed to query DRI3 DRM FD
error: BackendCreateFailed
???:?:?: 0x225438 in ??? (???)
???:?:?: 0x21f76c in ??? (???)
???:?:?: 0x21da80 in ??? (???)`

Anyone knows what I'm doing wrong? I've installed all dependencies and ran the submodule init

**Comment by novakne** [comment]
https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3335

https://forums.developer.nvidia.com/t/dri3open-missing-in-the-x11-driver-for-wlroots-compositors/214164

So just don't launch river in a X11 wm when you have a nvidia card I guess
