### ISSUE TITLE
Wlroots updated. We wait new version of RiverWM! ;)

### ISSUE THREAD

**Issue by n1rdeks** [riverwm/river#718]

**Comment by ifreund** [comment]
River's mater branch already depends on wlroots 0.16. An 0.2.0 River release will happen when it is ready.

**Comment by jbeich** [comment]
Would be nice if river 0.2.0 supports zig 0.9.1 while river 0.2.1 supports zig 0.10.0 (like during river 0.1.1 and 0.1.2). FreeBSD *downstream* already has wlroots 0.16.0 but not yet zig 0.10.0.

**Comment by ifreund** [comment]
@jbeich Thanks for the input, I wasn't sure how useful that path with river 0.1.1/0.1.2 was in practice. I'd be happy to split things up like that again as the Zig version shouldn't affect the behavior of river for end users at all.

I've also ran into some upstream Zig issues regarding conditional compilation while upgrading to 0.10.0 which I haven't been able to fully resolve yet.
