### ISSUE TITLE
switching keyboard layout

### ISSUE THREAD

**Issue by fahimscirex** [riverwm/river#721]
`setxkbmap -layout us,bd -variant ,probhat -option grp:win_space_toggle`

in xorg i used this command to switch layout, how can i get this done in river?

**Comment by Leon-Plickat** [comment]
X11 won't work for Wayland servers, as you have discovered.

Unfortunately we don't yet have a way to set the layout via command (see #708). However you can set certain env vars before starting river. Read the manpage (`river.1`) for more info on this.
