### ISSUE TITLE
about predefined tags

### ISSUE THREAD

**Issue by fahimscirex** [riverwm/river#724]
Any eta on when #696 is going to be merged?

**Comment by novakne** [comment]
I don't know if or when it gonna be merged but it's better to comment in the PR instead of opening an issue

**Comment by fahimscirex** [comment]
@novakne i know, sorry for that. i tried commenting on pr but couldn't, github didn't let me.

**Comment by Leon-Plickat** [comment]
Please in general don't ask about any state or time estimate on any PR or issue. All available information is already in the comments; Asking will reveal nothing new and only adds clutter. If you *really* feel like asking, do so on IRC. GitHub is not a user forum. Comments are for on-topic technical discussions; Only comment if you can add value to the topic at hand.
