### ISSUE TITLE
Dunst action does not work

### ISSUE THREAD

**Issue by NikitaIvanovV** [riverwm/river#725]
When I recieve a notification in some messanger app and click on it, the app instance does not gain focus. I used the same dunst configuration on Xorg and it worked there. What should I do to make it work or is it impossible to fix due to how Wayland protocol works internally?

**Comment by Leon-Plickat** [comment]
This seems like an issue with the application not supporting self-activation on Wayland.

This happens client-side:

1. Client creates notification, gets a handle for it.
2. Dunst displays notification.
3. User clicks on notification, dunst closes it.
4. The client gets informed that its notification was closed via the handle.
5. The client can now try to self-activate.
