### ISSUE TITLE
River failed to compile on Gentoo.

### ISSUE THREAD

**Issue by IchikaZou** [riverwm/river#729]
The maintainer of the River ebuild said the problem might cause by the upstream.(https://github.com/bsd-ac/wayland-desktop/issues/33)

Gentoo river build log:

[River-0.1.3 Build log](https://github.com/riverwm/river/files/10142076/River-0.1.3.Build.log.txt)

**Comment by novakne** [comment]
It seems to be build with zig 0.10 which river doesn't use yet

**Comment by IchikaZou** [comment]
Build with 0.9.0 and passed. Problem solved, close issue.
