### ISSUE TITLE
Resize any corner of a floating window using the mouse

### ISSUE THREAD

**Issue by XeroOl** [riverwm/river#736]
On river 0.1.3 and I have noticed that whenever resizing a floating window with the mouse (using Mod + Right Mouse), the size always changes in the bottom right corner, even if my mouse was closer to another corner. It would be nice if the user had the ability to adjust any of the four corners, and it selected whichever one the mouse was closer to. My understanding is that's how other window managers behave.

**Comment by novakne** [comment]
See #399, that's uncovered some bugs so I don't know what's the plan for this right now
