### ISSUE TITLE
How to setup river on NixOS?

### ISSUE THREAD

**Issue by mbledkowski** [riverwm/river#737]
Hi,
I need help with setting up river on NixOS system.
Whether I am trying to add river as a window manager using "programs.river.enable", or "services.xserver.windowManager.river.enable" it does not work.
Can you please help mi out with setting it up on my system?
Thanks in advance!

**Comment by ifreund** [comment]
Hello, I do not use nixos and this is not a support fourm. You could try the #river IRC channel on libera or nixos fourms of some kind.
