### ISSUE TITLE
riverctl(1) fails to enable tap-to-click in trackpoint

### ISSUE THREAD

**Issue by Baitinq** [riverwm/river#739]
Hi!

I was trying to enable the "tap to click" functionality on my x230's trackpoint, and it seems like river's input configuration utility is not working.

This is the command I performed which I thought would cause the desired functionality:

`riverctl input "pointer-2-10-TPPS/2_IBM_TrackPoint" tap enabled` (although I also tried with drag just in case)

I could get it working by using writing directly to /sys/devices/platform/i8042/serio1/serio2/press_to_select

`echo -n 1 > /sys/devices/platform/i8042/serio1/serio2/press_to_select`

I'm not sure whether is is a bug or its simply missing river/libinput functionality. I just wanted to log this in case anyone had a way of achieving this behavior using river's/wayland utilities.

**Comment by ifreund** [comment]
Hello, it unfortunately looks like libinput does not support this configuration option. As far as I understand, "tap to click" is only for trackpads and not supported for trackpoints. I would expect such an option to be called "press to click" or similar if it were available. 

I can confirm that I see the same behavior on my x220 and that libinput's tap to click does work as expected for the trackpad.

If you really want to be able to set this configuration through libinput/river then I suggest getting in touch with the libinput developers. It could be that they aren't yet aware of this feature of lenovo's trackpoints, I wasn't aware myself before I read your issue.
