### ISSUE TITLE
[Feature Request] Configure inputs by class

### ISSUE THREAD

**Issue by jalil-salame** [riverwm/river#741]
I currently use this script to configure my touchpa

```sh
configure_touchpads() {
    riverctl list-inputs \
        | grep 'type: pointer' -B 1 \
        | grep -vE 'type: pointer|^--$' \
        | xargs -I '{}' riverctl input '{}' $@
}

# Touchpad config
configure_touchpads natural-scroll enabled

configure_touchpads tap enabled
configure_touchpads tap-button-map left-right-middle
```

I don't like using the device names, because then I need to maintain different configurations for all my machines.

Ideally there would be a thing analogous to `xorg.conf`'s [Input-Class Selection](https://man.archlinux.org/man/xorg.conf.5#INPUTCLASS_SECTION):

- MatchIsKeyboard
- MatchIsPointer
- MatchIsJoystick
- MatchIsTablet
- MatchIsTabletPad
- MatchIsTouchpad
- MatchIsTouchscreen

Then you could do something like `riverctl input match:touchpad tap enabled`.

**Comment by Leon-Plickat** [comment]
Since this is so easily scriptable, I honestly don' see any advantages to having such functionality in river itself.

**Comment by salameme** [comment]
Then I guess this is something that should go to the documentation.

**Comment by jalil-salame** [comment]
Looking at sway, swaymsg implements this using `swaymsg input type:touchpad <command> `.

Maybe consider adding this for feature parity?

**Comment by Leon-Plickat** [comment]
Feature parity and/or similarity to any other software is not our goal and not enough reason to implement a feature.

This feature here has one valid use case: Configuring unknown future input devices.

If you want it, discuss on IRC and if you get a green light, submit a PR.

**Comment by ifreund** [comment]
River now has a basic glob matching implementation. Leveraging this for input configuration in a similar way to the rules system would solve this issue cleanly while being even more flexible.

**Comment by jameschensmith** [comment]
I'd like to contribute this. The actual change is quite simple. Would you like the input docs to be updated as well? Looks like the globbing is spoken in detail in the rules section. Trying to figure out how to best update the input docs without being DRY :thinking: I believe this is also my first contribution to a GPL-3.0 project. Do I need to sign anything before making the contribution?

**Comment by ifreund** [comment]
> Would you like the input docs to be updated as well? Looks like the globbing is spoken in detail in the rules section. Trying to figure out how to best update the input docs without being DRY

The docs definitely need updating yes but don't stress too much about style for the first draft. It's easier to see how the docs can be cleaned up after the docs exist.

> I believe this is also my first contribution to a GPL-3.0 project. Do I need to sign anything before making the contribution?

Nope, just open a pull request when you feel that your changes are ready for review.
