### ISSUE TITLE
Error from example init config

### ISSUE THREAD

**Issue by Will-Shanks** [riverwm/river#743]
I'm trying to setup river, and using the example config as a starting point.

I get this error `error: invalid pointer action toggle-float, must be move-view or resize-view` from [this](https://github.com/riverwm/river/blob/3141940efb7a241cc4998e7f8263533823f75ef3/example/init#L75) line in the config `riverctl map-pointer normal Super BTN_MIDDLE toggle-float`. Commenting it out removes the error.

I'm using river version 0.1.3 from the AUR on Manjaro

**Comment by ifreund** [comment]
It seems like you're trying to use the example init file from river's master branch with river 0.1.3. This isn't going to work as there have been new features and breaking changes on master branch.
