### ISSUE TITLE
Transparency is disabled on fullscreen mode

### ISSUE THREAD

**Issue by MelihDarcanxyz** [riverwm/river#744]
Terminal is transparent while not on fullscreen, but becomes opaque on fullscreen mode. I'm not sure if this is a bug or a feature. On Qtile, it remains transparent so it's not about the terminal.

**Comment by Leon-Plickat** [comment]
From the xdg-shell protocol:

> If the fullscreened surface is not opaque, the compositor must make
> sure that other screen content not part of the same surface tree (made
> up of subsurfaces, popups or similarly coupled surfaces) are not
> visible below the fullscreened surface.

Showing anything "behind" a transparent  fullscreen window would be a protocol violation.
