### ISSUE TITLE
Layout ratio changes globally

### ISSUE THREAD

**Issue by MelihDarcanxyz** [riverwm/river#745]
I'm using default layout.

Let's say I have 2 tags that I'm working with and in the first one, I want the left side of the screen to have a 0.4 ratio. But in the second one, I want the left side of the screen to have a 0.70 ratio. This is not possible in the current state of river. If I change ratio of one tag, it changes in all tags.

Maybe this is because, every screen is a 'tag' not a 'workspace'. I'm not sure.

**Comment by Leon-Plickat** [comment]
This is in fact the intended behaviour of rivertile. If you want different layouts per tag, you need to use a layout generator that supports that. Have a look in the wiki, we keep a list of layout generators there.
