### ISSUE TITLE
rivertile: main-count can still be set to zero

### ISSUE THREAD

**Issue by cbilz** [riverwm/river#757]
Both `riverctl send-layout-cmd rivertile "main-count 0"` and `riverctl send-layout-cmd rivertile "main-count 1"` produce the same layout with a single main view. But they are not the same state: Upon setting `main-count` to zero it takes *two* increments (`riverctl send-layout-cmd rivertile "main-count +1"`) to get an additional main view.

Should the following handler be modified to ensure that `output.main_count` is always at least `1`, rather than `0`? https://github.com/riverwm/river/blob/e49db7682c982f92d5f780e01f5fd4c952d8112f/rivertile/main.zig#L167-L180

Related to #290.

**Comment by ifreund** [comment]
Hello, thanks for the bug report. This has been fixed in c479525ab8f54cbaf5f63e83267ca6d1ef23296f.
