### ISSUE TITLE
Border alpha doesn't work as expected

### ISSUE THREAD

**Issue by MelihDarcanxyz** [riverwm/river#760]
According to riverctl manpage, color format can be:
0xRRGGBBAA

This border is represented as ```0xff79c6ff```

![image](https://user-images.githubusercontent.com/57872471/210861551-b1a283cd-aa26-42ae-a274-77ae85542eda.png)

This one is: ```0xff79c600```

![image](https://user-images.githubusercontent.com/57872471/210861611-3e60331c-a4c1-4665-91b8-f95ba50abb4d.png)

The interesting thing is, first color has 255 alpha and you can see the color fully. It's expected, but in the second one, the alpha is 0, I shouldn't be seeing any color. It should be fully transparent.

Am I missing something or is this a bug?

**Comment by Leon-Plickat** [comment]
A bug, either in our colour code parser or in upstream wlroots.

**Comment by novakne** [comment]
I can't reproduce, it does works as expected for me, I don't see any border with `0xff79c600` or any other colors with alpha at 0

**Comment by MaxVerevkin** [comment]
I can reproduce. Also I noticed that alpha works as expected if the background is white, but does not if it's black.

**Comment by novakne** [comment]
Hmm ok that's a weird one, I indeed used a white wallpaper and couldn't repdroduce it, but I tried with a dark one and it is buggy. Tried just with `riverctl background-color` for `0xffffff` and `0x000000` and that's clearly changed the color of the borders
