### ISSUE TITLE
Keychords

### ISSUE THREAD

**Issue by deepaknegilachu** [riverwm/river#765]
Hey is there a way to perform keychords.
Like:- if i press mod + x and then r or k 
 for wlsunset -t 2400 or pkill wlsunset .
and
mod + o and then l
for footclient -a fm lf

**Comment by ifreund** [comment]
You could use mod + x to enter a mode with keybindings for r and k. See the `riverctl enter-mode` command.

**Comment by deepaknegilachu** [comment]
# These  are working
riverctl declare-mode keychainsr
riverctl map normal $mod R enter-mode keychainsr
riverctl map keychainsr None S spawn 'wlsunset -t 2400'
riverctl map -release keychainsr None S enter-mode normal
riverctl map keychainsr None K spawn 'pkill wlsunset'
riverctl map -release keychainsr None K enter-mode'

riverctl declare-mode keychainso
riverctl map normal $mod O enter-mode keychainso
riverctl map keychainso None L spawn 'footclient -a fm lf'
riverctl map -release keychainso None L enter-mode normal
riverctl map keychainso None P spawn 'passmenu'
riverctl map -release keychainso None P enter-mode normal

# can i use two command at a keybind ?
