### ISSUE TITLE
Panic while unlocking

### ISSUE THREAD

**Issue by MaxVerevkin** [riverwm/river#766]
After df2fc30 river panics when unlocking.

Log: 
![image](https://user-images.githubusercontent.com/34583604/211152571-73ed8603-0f33-4363-a4bb-e75705930ecf.png)

Backtrace: 
![image](https://user-images.githubusercontent.com/34583604/211152591-f324e1bc-1482-4cdd-9963-80cab750f01a.png)

I use my own locker which I can share if this is not reproducible with other clients.

**Comment by ifreund** [comment]
Thanks for the report, I was able to reproduce this crash with an old swaylock build I had lying around though I never hit it with waylock.

I just pushed df2fc30238fe445cf04aaf64d0b906195129f726 which should fix things. Old and new swaylock now work and waylock still works. Let me know if this is fixed for your locker as well and I'll close this issue.

**Comment by MaxVerevkin** [comment]
Thanks, fixed for me!

**Comment by ifreund** [comment]
Excellent!
