### ISSUE TITLE
Variable 

### ISSUE THREAD

**Issue by deepaknegilachu** [riverwm/river#768]
Some variable are not working , especially one with spaces in it

Here bemenu works but term and monitor and many more are not.

#Variable
menu="bemenu-run"
term="foot tmux new -A -X -s basic"
monitor="foot -a monitor btop"

#Mod+Shift+Return to start an instance of terminal
riverctl map normal Super+Shift Return spawn $term
riverctl map normal Super+P spawn $menu

#Make certain views start floating
riverctl float-filter-add app-id monitor

**Comment by Ordoviz** [comment]
Doublequote your variables. Issues like these can be detected with shellcheck and are not river's fault.

**Comment by deepaknegilachu** [comment]
Hey thanks for suggestion, but its not working 
I tried
term=""foot tmux new -A -X -s basic""
term="'foot tmux new -A -X -s basic'"
term="foot 'tmux new -A -X -s basic'"

but none of them is working.

**Comment by deepaknegilachu** [comment]
Solved , Subsitute also required quote .
riverctl map normal Super+Shift Return spawn "$term"
Thanks Ordoviz.

**Comment by novakne** [comment]
That's here you need to double quote, to prevent globbing and word splitting.
```
riverctl map normal Super+Shift Return spawn "$term"
riverctl map normal Super+P spawn "$menu"
```

**Comment by deepaknegilachu** [comment]
Solved , Subsitute also required quote .
riverctl map normal Super+Shift Return spawn "$term"
Thanks Ordoviz.

**Comment by deepaknegilachu** [comment]
> That's here you need to double quote, to prevent globbing and word splitting.
> 
> ```
> riverctl map normal Super+Shift Return spawn "$term"
> riverctl map normal Super+P spawn "$menu"
> ```
> 
> Edit: You figured out while I was writing, see [this](https://www.shellcheck.net/wiki/SC2086) for an explanation

Thanks buddy.
