### ISSUE TITLE
[Feature Request] Expose `layout_name` via river-status

### ISSUE THREAD

**Issue by alex-courtis** [riverwm/river#769]
`layout_name` is set during layout commit, however it is unused.

Proposal: expose `layout_name` via river-status

Use case: display on status bar e.g. `=[]` `[1]` `[]=` `left` `monocle` `right`

**Comment by MaxVerevkin** [comment]
Already done in #673

**Comment by Leon-Plickat** [comment]
[We already do that.](https://github.com/riverwm/river/blob/master/protocol/river-status-unstable-v1.xml#L87)

**Comment by alex-courtis** [comment]
Thank you. I did not fetch upstream...

Apologies for the inconvenience.
