### ISSUE TITLE
Suggestion: Riverctl Multiple Commands

### ISSUE THREAD

**Issue by bagnaram** [riverwm/river#782]
Forking processes can be costly at startup based on the `strace` testing I have done for each of the configuration options. How difficult would it be to allow the config to be loaded from a single `riverctl` command like below?

```sh
riverctl --stdin <<EOF
# Super+J and Super+K to focus the next/previous view in the layout stack
map normal Super J focus-view next
map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
map normal Super+Shift J swap next
map normal Super+Shift K swap previous
EOF
```

This avoids the need for the init script to fork a new `riverctl` process for each of the config options.

**Comment by ifreund** [comment]
Sure it would be more efficient, but I don't see any evidence that this matters in practice and I don't plan on implementing this feature.

**Comment by bagnaram** [comment]
If I get some free time I will work on a separate wayland client to issue the startup.
