### ISSUE TITLE
Showed titlebar, expect dont show.

### ISSUE THREAD

**Issue by n1rdeks** [riverwm/river#784]
latest River, for reproduce - just install and open any GTK3 program, for example - transmission with gtk support. 

>River by default disables CSD (Client-side decoration) but GTK use an obsolete protocol. See [#24](https://github.com/ifreund/river/issues/24) for more information.

I read this, but... In Sway or DWL titlebars not shown. Why?

**Comment by MaxVerevkin** [comment]
Because they implement that obsolete protocol.
