### ISSUE TITLE
Mapping keyboard-layout to a key crashes river

### ISSUE THREAD

**Issue by czettnersandor** [riverwm/river#791]
I'm using the following mapping intended to switch keyboard layout:

```
riverctl map normal Super A keyboard-layout us
riverctl map normal Super S keyboard-layout hu|
```
When I try to use Super A or Super S, the compositor crashes. There's no output from the binary logged to the log file. I tried to launch river this way to catch any errors logs:

```
exec /usr/bin/river > /home/sandor/river.log
```

The file remains empty, so I'm not sure how else I could debug this.

**Comment by ifreund** [comment]
Should be fixed by 06cb76f937e15c1830e606c892dbf64601345201
