### ISSUE TITLE
Chromium-based applications steals cursor from other tags

### ISSUE THREAD

**Issue by linde12** [riverwm/river#794]
If i have two Chromium instances running on different tags, my mouse clicks and movements are "passthrough" to the other instance. So clicking something in chromium on one tag will instead click in chromium on the other tag.

It's not just with chromium to chromium, but it seems to be anything chromium based like OBS or the linux slack client.

River version: 0.1.1
Chromium version: 110.0.5481.77
River init:
```
riverctl map normal Mod4+Shift Return spawn alacritty
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &
riverctl map normal Mod4 Q close
riverctl map normal Mod4+Shift E exit
riverctl map normal Mod4 p spawn 'wofi --show drun'
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Mod4+[1-9] to focus tag [0-8]
    riverctl map normal Mod4 $i set-focused-tags $tags

    riverctl map normal Mod4 Tab set-focused-tags $tags

    # Mod4+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Mod4+Shift $i set-view-tags $tags

    # Mod4+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Mod4+Control $i toggle-focused-tags $tags

    # Mod4+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Mod4+Shift+Control $i toggle-view-tags $tags
done
```

I'm on voidlinux so we just have 0.1.1 in our package manager right now. I remember trying to compile from source, and i remember failing because of dependencies that weren't available in xbps and no other package manager to install them :-) Maybe i'll give it another shot. Will report back.

**Comment by ifreund** [comment]
This has been fixed since version 0.1.2 or 0.1.3, which were released over a year ago.

The void packaging is so out of date because of LLVM, though there's an attempt to get LLVM 15 merged which looks quite promising

**Comment by ifreund** [comment]
Note that you can compile from source fairly easily on void using a statically link zig binary of the correct version from https://ziglang.org/download

**Comment by linde12** [comment]
> Note that you can compile from source fairly easily on void using a statically link zig binary of the correct version from https://ziglang.org/download

Damn, quick replies haha. I just did this and compiled master. Works fine. Thank you for your amazing work!

**Comment by ifreund** [comment]
No problem, glad river is useful to you :)
