### ISSUE TITLE
Add a chain/concat command for chaining more than one command.

### ISSUE THREAD

**Issue by thezealousfool** [riverwm/river#800]
Usecase: Running more than one command on one keybind - eg. set-veiw-tags and set-focused tags with one keymap.

Proposal: Add a chain/concat command. I am not very familiar with the codebase but I feel this can be tricky as each command can have arbitrary number of arguments?
eg.
```
riverctl map normal Alt+Shift 1 chain set-view-tags $((1 << 0)) set-focused-tags $((1 << 0))
``` 

Current workaround:
```
riverctl map normal Alt+Shift 1 spawn 'riverctl set-view-tags $((1 << 0)) && riverctl set-focused-tags $((1 << 0))'
```

**Comment by ifreund** [comment]
I think the "current workaround" is fine for the time being, I don't plan on changing this in the short term and it's likely that this interface will be replaced in the long term.

One can of course put longer sequences of commands one wishes to map a keybinding for in a separate script.
