### ISSUE TITLE
Cursor warp to monitor not working if there is no visible window

### ISSUE THREAD

**Issue by gozenka** [riverwm/river#802]
With the setting: `riverctl set-cursor-warp on-output-change`
With two monitors active, if both of them currently have no visible windows, cursor does not warp on changing output focus. The output focus changes normally otherwise, as the new actions happen on the other monitor. Only the cursor warp is missing.
If either one of the monitors have a window visible, changing output focus between them warps the cursor properly, both ways. i.e. one output has a window visible, the other has no windows. cursor warps properly between the two when changing output focus.

**Comment by ifreund** [comment]
Fixed by 90f240355e1f8316167674219cec2326c9934b37
