### ISSUE TITLE
Zathura (possibly other GTK apps) not having titlebars handled properly

### ISSUE THREAD

**Issue by marcs-feh** [riverwm/river#808]
I'm not 100% sure if this is river, zathura or GTK's fault, however, when testing other dynamic WMs [Sway](https://github.com/swaywm/sway) and [dwl](https://github.com/djpohly/dwl) the titlebar is ommited/changed as it should.

OS: Arch Linux
River: 0.3.0-dev

Examples:

- river (default config) -> No border and redundant titlebar (border can be added with a ssd rule)
![river](https://user-images.githubusercontent.com/82233333/226083270-f176f971-2c5d-4dca-af53-4c77c807005d.png)
NOTE: in this image I saved river's screenshot on top of sway's because I'm an idiot 

- dwl (zero patches, default config) -> Desired(?) behavior (no titlebar + border working)
![dwl](https://user-images.githubusercontent.com/82233333/226083268-c1bd0d76-7a48-4688-ac98-6587bac543d9.png)

- Sway (default config) -> Changes style to match WM, handles border properly
![sway](https://user-images.githubusercontent.com/82233333/226083271-4965783b-2eab-4e84-89af-09ae799b8ecb.png)

**Comment by novakne** [comment]
See https://github.com/riverwm/river/wiki#how-do-i-disable-gtk-decorations-eg-title-bar
