### ISSUE TITLE
Drag icons sometimes show up in the top left corner of the screen

### ISSUE THREAD

**Issue by vainiovano** [riverwm/river#813]
Drag icons sometimes show up in the top left corner for one frame before moving to the correct position:

https://user-images.githubusercontent.com/16741932/227603743-21d6d2e9-4d84-4a8a-b5bd-f7d239be517f.mp4

**Comment by vainiovano** [comment]
Actually it happens every time I grab anything in weston-dnd without moving the mouse

**Comment by MaxVerevkin** [comment]
Happens in Firefox too.

**Comment by ifreund** [comment]
Fixed by 4cb65f9e2e992a685503ce3f78b731a3bcd954ca
