### ISSUE TITLE
drag floating window across screens

### ISSUE THREAD

**Issue by 10leej** [riverwm/river#817]
Hello I'd like to be able to drag a floating window from one screen to another, I dont see an option to enable this in rivertctl.  

While I recognize this is a tiling compositor I'm a normie that still uses my mouse quite frequently even though it's obvious not the same opinion as the potential future commenter.

**Comment by NickHastings** [comment]
People who don't have the same workflow as you are abnormal?

**Comment by Leon-Plickat** [comment]
Please keep it civil everyone!

@10leej It's probably best to not make remarks about "potential future commentors" in a feature request; That can make others think you are not here in good faith. We should all make sure not to import the antagonistic atmosphere common on typical social media platforms to github issues.

@NickHastings "normie" is internet slang for "not a member of the in-group". Usually it is not meant as insult towards the in-group, but rather the opposite. Also, tone-policing is my job.

**Comment by NickHastings** [comment]
@Leon-Plickat fair points. I should remember to keep my mouth shut when not sufficiently caffeinated.

**Comment by ifreund** [comment]
In any case, this isn't going to happen before the upcoming 0.3.0 release and (if ever) will only come as a side effect of making the layout/window management protocol more flexible.

Closing as this isn't really actionable.
