### ISSUE TITLE
Provide default config "init" file on Arch Linux install

### ISSUE THREAD

**Issue by fritzrehde** [riverwm/river#820]
Hi, I just installed a fresh copy of Arch Linux on my laptop, and wanted to try out `river` (for the first time). I installed it using `sudo pacman -S river` and, as the main readme states, launched it with `river`. However, I got a blank screen. I had to reboot and saw that there was no default config file installed at `.config/river/init`. I had to clone the `river` git repo to get the default config file. I think it would be more intuitive if the default config file was just installed to the default location when a `sudo pacman -S river` is run. I am not sure if this is possible, but if it is, this would greatly improve the first experience with river, in my opinion. Thanks for everyone's work on this!

**Comment by novakne** [comment]
This is not an default config but an example config, it is up to the distro package maintener to copy it somewhere on your system, which may have been the case. 
Also a copy/paste or curl the raw file is easy enough, no need to clone anything.

**Comment by Leon-Plickat** [comment]
This was discussed before but we came to the conclusion to not ship any default init, for a variety of reasons. The one we do have in the repo is, as novakne pointed out, purely an example.

River will only for an init inside your home directory anyway, so even is packagers decided to install the example init somewhere, it would still not be executed.
