### ISSUE TITLE
Firefox crashing on exit when using hardware acceleration

### ISSUE THREAD

**Issue by itshog** [riverwm/river#821]
Since updating River to the latest master, Firefox always crashes when closing it with the following error message:

`MozCrashReason: warning: queue 0x7f6b085b1700 destroyed while proxies still attached:`

While this gets printed to the terminal:

`ExceptionHandler::GenerateDump cloned child 3425`
`ExceptionHandler::WaitForContinueSignal waiting for continue signal...`
`ExceptionHandler::SendContinueSignalToChild sent continue signal to child`

I tested a clean profile to be sure that it wasn't related to my configuration, and I found out that when disabling hardware acceleration in Firefox settings the issue goes away. I am inclined to believe that this has something to do with River because it never happens in other compositors, and the issue wasn't there before the scene graph rewrite.

Some system info in case they are useful:

OS: Arch Linux
Firefox version: 111.0.1, installed from Arch repo
River version: 0.3.0-dev.109+b369815, installed from the AUR
Mesa version: 23.0.1-2
Kernel version: 6.2.10-arch1-1

**Comment by Leon-Plickat** [comment]
Have you maybe also updated Wayland and/or Firefox in the meantime as well? [I think it's this FF bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1826583) and not actually a fault in river.

**Comment by itshog** [comment]
Arch mesa package just got updated to 23.0.2-2 and the problem disappeared, at least for now. I'm closing the issue. Thanks for the response and for pointing me in the right direction!
