### ISSUE TITLE
Brightness keys (XF64MonBrightness[Up|Down]) not responding to `map -repeat` properly

### ISSUE THREAD

**Issue by fritzrehde** [riverwm/river#822]
I have noticed that mapping the brightness keys `XF64MonBrightnessUp` and `XF64MonBrightnessDown` behave quite weirdly. Without the `-repeat` flag, continously pressing the keys will still cause the key to be registered multiple times, but much slower than the actual keyrepeat.
For example:
```
    riverctl map -repeat $mode None XF86AudioRaiseVolume  spawn 'change-volume.sh up'
```
will work as expected, I can keep the raise audio key pressed and it will spawn the command according to my key repeat rate (also configured with riverctl). 
However,
```
    riverctl map $mode None XF86MonBrightnessUp   spawn 'change-brightness.sh up'
```
will also repeatadly execute, but at a slow speed (around 1 update every 0.5 seconds as far as I can tell). Furthermore, adding the `-repeat` flag changes nothing.
Any ideas?

**Comment by Leon-Plickat** [comment]
On some systems, changing screen brightness just seems to be a slow process when done in a "naive" way. Your script like `echo`s a number into a file somewhere in `/sys/`, right? Try writing a test script that does that in a loop and you'll likely see that it will be slow as well.

**Comment by fritzrehde** [comment]
```
On some systems, changing screen brightness just seems to be a slow process when done in a "naive" way.
```
Do you know why this is the case though. I don't think this has anything to do with river, I've seen it in many other window managers as well.
