### ISSUE TITLE
Fractional scaling for HiDPI devices

### ISSUE THREAD

**Issue by fritzrehde** [riverwm/river#823]
Text can look quite small even on a 1080p display running river. I think [sway supports HiDPI fractional scaling](https://wiki.archlinux.org/title/Sway#HiDPI) already, and I was wondering whether river already supported this, and, if not, whether there are plans to support this in the future. Thanks!

**Comment by fritzrehde** [comment]
My bad, I should have looked at the wiki first, as I have just found out I can use [external programs](https://github.com/riverwm/river/wiki/Recommended-Software) to control fractional scaling in wayland. Is [waydisplays](https://github.com/alex-courtis/way-displays) my only option that works with river, or are there other similar applications too?

**Comment by Leon-Plickat** [comment]
All applications listed in that wiki section work, otherwise they would not be listed there. Output scale can be adjusted with wlr-randr, kanshi, way-displays and any other application implementing the output configuration protocol.
