### ISSUE TITLE
[feature request] disable or overwrite handleBuiltinMapping (keyboard)

### ISSUE THREAD

**Issue by matthias-hmb** [riverwm/river#827]
The handleBuiltinMapping gets always priority and these keysyms cannot be mapped.
This can also be a security issue, because even in locked mode these keysyms are handled.
So, even with a session lock, it is still possible to switch to another VT. (Not always bad, can be a feature at a multiuser terminal)

**Comment by ifreund** [comment]
Perhaps you would be interested in something like https://github.com/xyb3rt/physlock
