### ISSUE TITLE
Firefox on Wayland has a border missing

### ISSUE THREAD

**Issue by greenfork** [riverwm/river#840]
Compiled river from the latest master. All the other window borders are present. Anything I could do?

![image](https://github.com/riverwm/river/assets/20167110/2ba3c424-e4a7-4df5-ba32-4d804750b38a)

**Comment by greenfork** [comment]
I was missing the border completely, yes. Thank your for your suggestion, it fixed my issue. I didn't bother to find the exact Firefox's app id and applied the rule globally `riverctl rule-add ssd`.

**Comment by MaxVerevkin** [comment]
You can get a list of titles and app ids of all open windows using [lswt](https://sr.ht/~leon_plickat/lswt/). In case of firefox, it is just `firefox`.

**Comment by greenfork** [comment]
Oh, right, for me it also was `firefox` with a small letter f. Thanks again, I've changed the rule to be more specific.
