### ISSUE TITLE
Failing to start river on void linux

### ISSUE THREAD

**Issue by jujpenabe** [riverwm/river#841]
Hi, I've being trying to install and start river with 
`sudo river` on void linux musl
 but I get the following error:
```
info: Initializing Server
error: AddSocketFailed to Wayland serverIME_DIR is invalid or not set in the environmentdepth_clamp GL_EXT_texture_query_lod GL_MESA_bgr _blackhole_render GL_MESA_frameb
???:?:?: 0x56492e4958d4 in ??? (???)
_(repeats)_
```

I couldn't find how to solve this.
Is this related with some missing packages?

Thanks in advance.

**Comment by novakne** [comment]
Are you using Nvidia? I don't know about the error but it usually not a good idea to run river with `sudo` anyway

**Comment by dkwo** [comment]
river on void-musl works ok for me.
did you check the docs at https://docs.voidlinux.org/config/graphical-session/wayland.html ?
some things that come to mind: seatd, the XDG_RUNTIME_DIR and XKB_DEFAULT_LAYOUT vars,
i'd not use sudo, you may need mesa-dri pkg.

**Comment by jujpenabe** [comment]
Thanks for the help!

Ok I managed to start river, in fact I needed to start without `sudo` but before that I added permissions to `_seatd` service and also enabled the `pam_rundir` module to the pam.d/system-login (which only includes a default to logind), this fix the required `XDG_RUNTIME_DIR` creating the path on login.

**Comment by dkwo** [comment]
Sure. It's enough to be a member of the `_seatd` group, and create the runtime dir in `/etc/rc.local`, but something like chimera linux's turnstile would be nice to have.
