### ISSUE TITLE
riverctl: focus-view -skip-floating

### ISSUE THREAD

**Issue by MaxVerevkin** [riverwm/river#846]
Often when using the `focus-view` keybinding I want to skip floating views and only cycle between tiled ones, especially because the order of floating views is not obvious.

Similarly an option to skip tiled views might be useful.

I am willing to implement it, but first wanted to ask if this would be accepted.

**Comment by TheFunctionalGuy** [comment]
Do you still want to implement it?
Otherwise I could do it.

Simply don't want to "steal" it from you.

**Comment by Leon-Plickat** [comment]
All the parts were already in place, all that was missing was some duct tape, so I went ahead and just did it myself.
