### ISSUE TITLE
Borders not displayed for certain applications

### ISSUE THREAD

**Issue by ohno418** [riverwm/river#849]
I'm not sure if this is a known issue, but I've noticed that borders for some applications are not being displayed. For example, borders are correctly displayed for the [foot terminal emulator](https://codeberg.org/dnkl/foot), but this isn't the case for Firefox.

### environment

- OS: ArchLinux
- River: Built from source code (`93a567ca945bd1f8a04b6453e59e0dbaeed0fcb3`, currently the latest master), not the ArchiLinux official package. Without Xwayland support.

Interestingly, when I tested the River official package for ArchLinux, it worked correctlly.

**Comment by ohno418** [comment]
I took a quick look into this issue and found that, within the `updateCurrent` function in `river/View.zig`, the borders seem to be sized correctly. I mean, the width and height of `view.borders`.

**Comment by Leon-Plickat** [comment]
River defaults to CSD, only using SSD for windows that explicitly request it.

This should add a border to firefox:
```sh
riverctl rule-add ssd -app-id firefox
```

**Comment by ifreund** [comment]
See also the section on rules in the `riverctl(1)` man page

**Comment by ohno418** [comment]
Ah, that makes sense. Thank you. However, I still don't understand why borders are displayed for Firefox when using the official ArchLinux package of River, but not when using River built from source...

**Comment by novakne** [comment]
Assuming the arch package was the latest river release, 0.2.4, the system for ssd/csd and rules has been changed since then

**Comment by ohno418** [comment]
Oh, got it. Thanks!
