### ISSUE TITLE
Is there a way to have more than 32 (changed from 10) tags?

### ISSUE THREAD

**Issue by Invertisment** [riverwm/river#850]
When I use my i3 setup (yes, not even wayland) I use 22 workspaces per namespace/context and I can have `a-z` amount of namespaces (so 26).
This means that I have a setup where I could work with 26 different contexts and use `1-2-3...` and `f1, f2, f3...` workspaces in each of them. And this gives me 22*26 combinations (which I don't need but the flexibility is there as I can create that many contexts).

I was fiddling around with river and I like the tiling layout but what I can't figure out is how to have more than 10 workspaces (I'll use tags as workspaces). For me the added binary combination flexibility doesn't really have any point it as I want to name my workspaces as text instead of having only 10 distinct views and performing binary operations in my head to view combinations of those windows simultaneously.

I think that this binary mode of combination solves a problem of interacting with existing windows but doesn't solve a problem when you want to fully switch your context from one multiple-window area to another.

I think that your window manager is limited to having only 10 distinct window layouts (a.k.a. "workspaces" and not tags).

So I'm thinking whether there would be a better way than finding 576 binary co-primes to implement the feature that I want. I don't even know whether 576 co-primes can even exist within your range. I also think that you enable the tags on `or`-like logic basis so that means that the number is simply too small and your compositor is limited to only ~10 of window layouting combinations:

```
[martin@wqe ~]$ riverctl set-focused-tags 11111111111111111
error: value out of bounds
[martin@wqe ~]$ riverctl set-focused-tags 1111111111111111
error: value out of bounds
[martin@wqe ~]$ riverctl set-focused-tags 111111111111111
error: value out of bounds
[martin@wqe ~]$ riverctl set-focused-tags 11111111111111
error: value out of bounds
[martin@wqe ~]$ riverctl set-focused-tags 1111111111111
error: value out of bounds
[martin@wqe ~]$ riverctl set-focused-tags 111111111111
error: value out of bounds
[martin@wqe ~]$ riverctl set-focused-tags 11111111111
error: value out of bounds
[martin@wqe ~]$ riverctl set-focused-tags 1111111111
[martin@wqe ~]$ 
```

I'm not sure if it's doable without simply changing the 32-bit number into a string (maybe it could somehow be moved into an external command line utility?).

I saw this comment but I think that being limited to only ~10-32 distinct views is not good enough (at least for me):
https://github.com/riverwm/river/issues/218#issuecomment-776283619

This is the same issue where your name in the registration would be limited to 15 characters. Eventually somebody will have a longer one.

And no, I didn't even have problems with different layouts per-tag as this context thing was the first thing I wanted to configure.

I'd like to know whether this is something you'd be thinking you'd want to have in your compositor.

**Comment by JustinLovinger** [comment]
Adding on to this, in Sway, I have a menu to select or move to an existing or new named workspace. For example, I can type `<Mod+;>bg<CR>` and create a new workspace named `bg`. This allows me to create infinite workspaces with arbitrary names, not limited to workspaces hard-coded to bindings.

Moving from workspaces to tags, I would ideally want at least this level of control. However, the use of bitmasks to represent tags seemingly makes this level of control and customization impossible.

**Comment by knotu** [comment]
You don't need to use "1111111111" if you just want to go to tags. I forget the proper term, but everything runs in a double sequence. So tag 1 is 1. 2 is 2. 3 is 4. 

So tags 1-9 are 1,2,4,8,16,32,64,128,256. I only use 9 tags, but used "riverctl set-focused-tags 2048" to go to tag 12 after reading your post as a test.

While I don't have it uploaded, I put the current tag in a tmp file, then use a bash script to go to prev/next tag with a bind. That actually led me to making a wrapper script that does much more, but that's more than what's being discussed. 

There's also a way to do the same thing with actual tag numbers, but i have a few issues to get worked out first. If i were to use 32 tags, going to 32 would be easier than whatever huge number it would actually be. But I only use 9 tags, so it's not really  priority at the moment.

**Comment by NickHastings** [comment]
River has 32 tags per display. Why do you think it only has 10?

**Comment by NickHastings** [comment]
> While I don't have it uploaded, I put the current tag in a tmp file, then use a bash script to go to prev/next tag with a bind. That actually led me to making a wrapper script that does 
much more, but that's more than what's being discussed.

This can be done with the protocol. See [riverwm-utils](https://github.com/NickHastings/riverwm-utils) and [river-shifttags](https://gitlab.com/akumar-xyz/river-shifttags) (both in the wiki).

**Comment by knotu** [comment]
> > While I don't have it uploaded, I put the current tag in a tmp file, then use a bash script to go to prev/next tag with a bind. That actually led me to making a wrapper script that does
> > much more, but that's more than what's being discussed.
> 
> This can be done with the protocol. See [riverwm-utils](https://github.com/NickHastings/riverwm-utils) and [river-shifttags](https://gitlab.com/akumar-xyz/river-shifttags) (both in the wiki).

I'm well aware that it can be done with the protocol. I've previously used river-shifttags. I just personally use scripts that help with functionality if I can, since I don't have to rely on a third party. 

I really like river, but certain things are offloaded and you are essentially at the mercy of that person having a continued interest in maintaining what they've created. It's one thing if a whole project goes down, but if there is something else you use and only one person provides it, them abandoning it makes the main project useless.

Anyway, I hope the person who made this post or anyone else who searches finds what I posted to be of some use.

**Comment by Invertisment** [comment]
Alright it's 32. But even if it's 32 I won't be able to have the flexibility that I have with workspace-like tags.
With 32 I can have a couple of contexts at most. It's not that I need more but this is lost when the tag limitation is in place.

**Comment by ifreund** [comment]
I have no plans to change this in the short term. Long term I'd like to move the implementation of tags/workspaces/whatever out of the compositor process into something like a more advanced layout generator.

It sounds like sway works for you, I suggest you keep using that for the time being.

**Comment by Invertisment** [comment]
> It sounds like sway works for you, I suggest you keep using that for the time being.

I'm using i3 and it works. But I wanted to finally fix the display scaling and now I'm researching what else I could fix at the same time.
And the layout generator would be a very nice thing to have in sway/i3.

**Comment by Invertisment** [comment]
> Long term I'd like to move the implementation of tags/workspaces/whatever out of the compositor process into something like a more advanced layout generator.

Maybe it's a good idea or maybe it's not. 
Because when you'll want to lay the windows then every time you'll need to send whole state to this generator to decide what it wants to show and how.
I think there could be several states -- all windows, visible windows and urgent windows.

For simplicity let's say we store those states as strings and deserialize them when the display action needs to happen.
So then you could invoke a CLI tool or a stateful API service (yes, LSP for UI (what a bad idea)) using these strings as inputs together with the user's action. Then you'd know which windows should be visible and which ones shouldn't. And how they should be laid out.
Is this how you understand the implementation of it?
