### ISSUE TITLE
[Question] Focus window by PID

### ISSUE THREAD

**Issue by idr4n** [riverwm/river#851]
Hi,
Sorry if I'm missing this in the docs... Is there a way to focus a window given its PID? In xorg I use a simple app called jumpapp to run or raise an application with a key binding.

In Sway and Hypr I can still do this with a script by getting the application pid's (e.g. with pgrep), cycle through them and focusing a particular window using a given PID. In Hypr, for example, there is `hyprctl dispatch focuswindow pid:$focus_pid` and in Sway there is something similar with `swaymsg`.

I wonder if River provides a command to do this as well, but I couldn't find one so far.

Thanks in advance!

**Comment by Leon-Plickat** [comment]
There is no clean way of mapping PIDs to windows, so I am not convinced this will be added.

**Comment by Leon-Plickat** [comment]
However, you don't actually want to focus windows by PID. What you want is to jump to open applications based by name. You just do a detour through the PID for whatever reason, which however is totally unnecessary. Focusing windows by app-id will be available in the future.

**Comment by idr4n** [comment]
Focusing by app-id would allow to focus only the first window of an app, right?

But if I have multiple windows opened of the same app (e.g. alacritty), potentially in different tags/workspaces, what I want is to be able to cycle through the windows of the same app  with the same key binding. For me is just a workflow that I implement or have in any OS or indow manager that I use, as I don't have to remember where a particular window of an app is located (workspace or tag)... This is just my workflow and so using PID's is the only way I can get it to work.

**Comment by Leon-Plickat** [comment]
This as well will be possible without caring about PIDs.

**Comment by idr4n** [comment]
Could you guide me in the right direction on how to accomplish this without PIDs  if you don't mind?

**Comment by Leon-Plickat** [comment]
Sure:

1. Wait for a wayland-protocols release
2. Wait for a wlroots release
3. Wait for me to create a proper river integration for that new protocol.

**Comment by idr4n** [comment]
Sure, thanks for letting me know!
