### ISSUE TITLE
Crash when trying to add empty tag rule

### ISSUE THREAD

**Issue by TAforever** [riverwm/river#854]
I tested the tag rule and found the following errors: if I don't specify a tag as an argument, it causes the river to crash. If I assign tags 1 2 3 to programs A B C, it works, but if I assign tags 1 3 5 for example, I get errors. Instead of opening on tags 1 3 5 the programs open on tags 1 2 3.  That is, as I understand it is impossible to have intermediate empty tags. In addition, programs are also marked with tag 1, that is, all 3 programs are also visible on the first tag. Just in case, I give a [link](https://pastebin.com/ZEAmY2ch) to my init script, if I'm doing something wrong.

**Comment by Leon-Plickat** [comment]
I can reproduce the crash, however the other thing is just a usage error. Putting a `5` there does not do what you think it does. The tag rule works like all other tag related commands in river as well: It takes a bit-field. `5` in binary is `101`, meaning tags 1 and three. Take a look at how the other tag keybinds work, especially the bit shift part (`$((1 << ($i - 1)))`).

**Comment by TAforever** [comment]
Well, I'm not a programmer, GNU/Linux is my hobby, so thanks for the clarification.
