### ISSUE TITLE
Not possible to build riverwm

### ISSUE THREAD

**Issue by bq-wrongway** [riverwm/river#856]
I have downloaded all the required dependencies, but every time when i try to build i get the same error :

```
/Dev/river/river/c.zig:17:20: error: C import failed
pub usingnamespace @cImport({
```

I have no idea what is the actual problem since this is not very descriptive. 

I am on the PopOS, but i dont think this should matter when building from source and dependencies are satisfied

**Comment by Leon-Plickat** [comment]
My first guess: PopOS is an Ubuntu derivative, isn't it? They split packages, meaning you need to install not just the "normal" version of the dependencies, but also their development versions. The package names should be the same, but with an additional `-dev` at the end IIRC.

**Comment by NickHastings** [comment]
How did you install zig?

**Comment by bq-wrongway** [comment]
i installed livwlroots-dev and error did change :

Now it says that zig-wlroots require wlroots version 0.16, but i dont know where to find livwlroots-dev 0.16 for ubuntu, or to build for source, as i did with normal wlroots

**Comment by NickHastings** [comment]
In wlroots 0.16 is in Debian experimental. You could grab the source package and backport it. This is what I do for Debian 12. See https://www.ne.jp/asahi/nickh/debian/

What version of PopOS are you using?

**Comment by bq-wrongway** [comment]
i am on popOS 22.04 LTS 

I get this error now, i need to install them too or at least try, since all versions are quite outdated

```
The following packages have unmet dependencies:
 libwlroots11 : Depends: libwayland-server0 (>= 1.20.92) but 1.20.0-1ubuntu0.1 is to be installed
                Depends: libxcb-xfixes0 (>= 1.15) but 1.14-3ubuntu3 is to be installed
                Depends: libxcb-xinput0 (>= 1.15) but 1.14-3ubuntu3 is to be installed
```

**Comment by bq-wrongway** [comment]
Okay, not to spam. But i did managed to install it, i will try to run it now and get a general feel. If it works okay il let you know and close the issue, if i dont come back soon well i crashed my system then :D

**Comment by bq-wrongway** [comment]
Does anyone have any idea how to troubleshoot this error ?

```
➜  ~ river -log-level debug 
river: symbol lookup error: river: undefined symbol: wlr_xwayland_create
```

**Comment by ifreund** [comment]
> river: symbol lookup error: river: undefined symbol: wlr_xwayland_create

There is some issue with how wlroots was linked or installed and the linker can't find symbols that should be provided by wlroots. Information about how you installed wlroots would be helpful, the output of `ldd` on the river binary might also provide some information.

In any case, there is no evidence of an issue on river's side here.
