### ISSUE TITLE
Option to Drag Application Windows off screen

### ISSUE THREAD

**Issue by Red1922** [riverwm/river#857]
I am unaware of any options to enable this if one exists. Whenever I drag a floating window towards the edge of the screen, it can't go offscreen, the entire thing gets stopped by the edge and displays over other applications.
Now, of course I can circumvent this simply by either sending the window to a different tag or by tiling it. However, in some specific scenarios it is quite inconvenient to do this, even more so considering I only have a single monitor at the moment.

**Comment by Leon-Plickat** [comment]
This behaviour is intentional.

**Comment by ifreund** [comment]
In other words, there are no plans in the short term to make this configurable. Long term, this may be possible but I can't say for certain yet. It depends on yet to be investigated details of my future plans regarding configuration.
