### ISSUE TITLE
riverctl: unable to tap-to-click with a touchpad 

### ISSUE THREAD

**Issue by Lassebq** [riverwm/river#861]
So my laptop's touchpad is listed in `riverctl list-inputs` as `pointer-2-8-AlpsPS/2_ALPS_GlidePoint`
Running `riverctl input "pointer-2-8-AlpsPS/2_ALPS_GlidePoint" click-method clickfinger` doesn't seem to enable tap-to-click. Unless click method is something else? I'm sorry but the wiki is just not very clear about it, and I have not found any other options which are responsible for touchpad settings.
```
river -version
0.3.0-dev.120+c16628c
```

**Comment by novakne** [comment]
You need to use `riverctl input "pointer-2-8-AlpsPS/2_ALPS_GlidePoint" tap enabled`

**Comment by Lassebq** [comment]
Thank you! IDK how I missed it
