### ISSUE TITLE
Keybinds are ignored when using another layout

### ISSUE THREAD

**Issue by Lassebq** [riverwm/river#862]
So I have two keyboard layouts:
```
riverctl keyboard-layout -options "grp:alt_shift_toggle" us,ru
```
For example:
I made Super+W close current window
```
riverctl map normal Super W close
```
If I press this key combination with english keyboard layout, everything works perfectly
If I do the same with russian keyboard layout 'ц' gets typed (Ц and W are on the same key) and window doesn't close

**Comment by ifreund** [comment]
See the documentation for the `-layout` flag for `map` in the `riverctl(1)` man page.
