### ISSUE TITLE
Feature Request: rules for: (initial) window-size, fullscreen, (initial) position, snap

### ISSUE THREAD

**Issue by simonhughxyz** [riverwm/river#865]
It would be nice to have some more rule options such as setting a default window X,Y size, position and maybe snap top/bottom/left/right.
The main reason I would find this useful is because I spawn terminals with fzf to perform various functions that I would like to have a pre-configured certain size and position. 

Something like:
`riverctl rule-add size --app-id "APP" 400x300`

And for position:
`riverctl rule-add position --app-id "APP" 300x500`

And for snap:
`riverctl rule-add snap --app-id "APP" top`

**Comment by Leon-Plickat** [comment]
These should be fairly trivial to implement. Just change the initial parameters of the views, the rest should work as expected. However care must be taken to avoid placing the view outside of the output bounds.

Also I think they should not auto-float views.

**Comment by justinesmithies** [comment]
> It would be nice to have some more rule options such as setting a default window X,Y size, position and maybe snap top/bottom/left/right. The main reason I would find this useful is because I spawn terminals with fzf to perform various functions that I would like to have a pre-configured certain size and position.
> 
> Something like: `riverctl rule-add size --app-id "APP" 400x300`
> 
> And for position: `riverctl rule-add position --app-id "APP" 300x500`
> 
> And for snap: `riverctl rule-add snap --app-id "APP" top`

I'd really like to see this implemented as described by @simonhughxyz as it would be immensely useful.

**Comment by JustinLovinger** [comment]
Your `sticky` behavior can be implemented by giving a window all tags.

**Comment by ralphptorres** [comment]
> Your `sticky` behavior can be implemented by giving a window all tags.

Indeed, although this has a potentially unwanted side effect: all tags will be occupied. So, say, if you set your bar to conditionally display tag numbers depending on window occupancy, then all tags are flagged and displayed.

In my case, I don't really mind that. Also, the sticky behavior will add unnecessary complexity to the simple tag system river implements (which is nice tbh).

**Comment by polykernel** [comment]
I implemented rules for window position and dimension in https://github.com/riverwm/river/pull/875. Any feedback is appreciated.
