### ISSUE TITLE
`LayoutDemand` timeout

### ISSUE THREAD

**Issue by JustinLovinger** [riverwm/river#867]
I am writing an experimental layout generator that does a non-insignificant amount of computation to determine window positions. However, if my algorithm takes more than a few milliseconds or so in response to a `LayoutDemand` event, River appears to ignore the result. Is there a timeout for `LayoutDemand` events, and can it be extended or removed?

**Comment by ifreund** [comment]
Indeed there is, and it is currently 100ms: https://github.com/riverwm/river/blob/c16628c7f57c51d50f2d10a96c265fb0afaddb02/river/LayoutDemand.zig#L37

It won't be removed as river must continue to function at some level regardless of what a layout generator does. It could be raised however. How long exactly does your layout generator take to respond?

**Comment by ifreund** [comment]
Note however that 100ms is really quite a long time. If every frame took 100ms to be drawn your desktop would run at 10fps. It is a long enough time that users will notice the delay and it won't feel snappy.

**Comment by JustinLovinger** [comment]
Assuming the issue is that River is blocking, waiting asynchronously would be an obvious solution. However, if implementing that is not practical, perhaps resending `LayoutDemand` requests with a geometric backoff could be a solution?

**Comment by Leon-Plickat** [comment]
> It seems to me it would be better to have no layout for a few seconds and then layout windows than to not layout windows at all.

On Wayland we try to adhere to "every frame is perfect", so this is a no-go. Yours is an edge case. The average layout generator will never even come close to the 100ms timeout. Needing multiple seconds to calculate a layout is kinda weird, what exactly are you doing?

**Comment by JustinLovinger** [comment]
"Every frame is perfect" refers to screen-tearing. I disagree with using the term to describe this issue.

My layout generator uses machine learning to invent layouts on-the-fly to fit a customizable set of objectives, like:

- Give the first N windows at least X width and at least Y height.
- Give all windows at least X width.
- Give windows higher in the stack more area.
- Place windows higher in the stack closer to the center.
- Give windows more width than height.

**Comment by Leon-Plickat** [comment]
> "Every frame is perfect" refers to screen-tearing.

It also refers to faux-states, like windows being in bad positions before the server "catches up". No hacks or janky-ness allowed.

I am honestly a bit suspicious if machine learning can create good layouts (where do you even get the training data?), but here is a workaround that should make your program work: On cache miss fall back to a hardcoded traditional layout algorithm or even time out if you like, wait for your algorithm to come up with a layout and cache it, then let your layout generator send itself a layout command (content is irrelevant) which will trigger a new layout demand.

**Comment by JustinLovinger** [comment]
It is not using supervised learning, so no training data, just mathematical optimization.

> Wait for your algorithm to come up with a layout and cache it, then let your layout generator send itself a layout command (content is irrelevant) which will trigger a new layout demand.

This sounds like the perfect solution for my use-case. By "send itself a layout command", you mean call `riverctl send-layout-cmd ...` from my layout generator?

**Comment by MaxVerevkin** [comment]
> By "send itself a layout command", you mean call `riverctl send-layout-cmd ...` from my layout generator?

Or since you are already writing a Wayland client, you can use `river-control` protocol directly.

**Comment by JustinLovinger** [comment]
I will need to figure out how to use the `river-control` protocol directly. I am using `wayland-client` in Rust and only learned enough to get the boilerplate working.

**Comment by MaxVerevkin** [comment]
Do you use `river-layout` directly? If so, it shouldn't be too difficult. Just bind the global, bind a `wl_seat` (river currently has only one seat anyway), and use your bound `ZriverContolV1` to send commands.

**Comment by JustinLovinger** [comment]
Using `river-control` to send a `send-layout-cmd` command worked perfectly.

Being able to trigger a new `LayoutDemand` solves this issue for me,
so I am closing it.
