### ISSUE TITLE
riverctl map-repeat doesnt work on send-layout-cmd commands

### ISSUE THREAD

**Issue by wreedb** [riverwm/river#868]
`riverctl map normal Super H send-layout-cmd rivertile 'main-ratio -0.05'`
works as expected
`riverctl map-repeat normal Super H send-layout-cmd rivertile 'main-ratio -0.05'`
returns an error

**Comment by MaxVerevkin** [comment]
You missed a space: `map -repeat`

**Comment by wreedb** [comment]
my apologies.
