### ISSUE TITLE
[Wiki] VRR?

### ISSUE THREAD

**Issue by GrabbenD** [riverwm/river#873]
[Recommended Software](https://github.com/riverwm/river/wiki/Recommended-Software) section mentions that [way-displays](https://github.com/alex-courtis/way-displays) has VRR support. Other than that there was a PR for this which was instead upstreamed to wlroots https://github.com/riverwm/river/pull/420?

What's actually the correct way to enable Adaptive Sync / VRR in River?

**Comment by ifreund** [comment]
any wlr-output-manangement client should work fine, that include wlr-randr and kanshi as well.
