### ISSUE TITLE
Have a different layout per output

### ISSUE THREAD

**Issue by masroof-maindak** [riverwm/river#876]
Hello, just finished reading through the manpage and I'd like to imagine I understand how tags function now.

Here's my sole concern, my secondary monitor is kept vertically so the default master stack isn't very usable. I'm aware I can't have a shared set of tags for all my outputs.

A layout where the top 50% of the screen is a master and the bottom 50% (or whatever ratio) is 100% width slaves dividing the height amongst themselves would be much more practical.

Generating the aforementioned layout is a separate issue but for now I'd just like to know how, and if, I could automatically assign my second monitor to have this separate layout

**Comment by Leon-Plickat** [comment]
Have a look at the [community layouts page in the wiki](https://github.com/riverwm/river/wiki/Community-Layouts). There you'll find layout generators which support this.
