### ISSUE TITLE
Crash with wl-mirror and unplugging

### ISSUE THREAD

**Issue by adamcstephens** [riverwm/river#877]
I'm able to consistently crash river by using the following steps.

1. Connect a second display
2. Run [wl-mirror](https://github.com/Ferdi265/wl-mirror) and add a mirroring window for the second display
3. Move the mirroring window to the initial display
4. Unplug the second display

[dump.tgz](https://github.com/riverwm/river/files/12518250/dump.tgz)

**Comment by ifreund** [comment]
I can't seem to reproduce this on river commit 7f30c655c75568ae331ed0243578d91870f3f9c6. wl-mirror exits with
```
error: mirror::output_removed(): output disappeared, closing

```

**Comment by ifreund** [comment]
tiosgz just reminded me on IRC that they were able to reproduce this and got a log with a failed wlroots assertion: https://libera.irclog.whitequark.org/river/2023-09-05#1693906336-1693906381

**Comment by ifreund** [comment]
I can reproduce this by placing the wl-mirror window on the output that gets unplugged and get the same assertion failure.

**Comment by ifreund** [comment]
This is a wlroots issue and has already been fixed upstream in https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3646

**Comment by adamcstephens** [comment]
I've applied the wlroots fix for that linked issue to 0.16 and it resolves the crash on https://github.com/riverwm/river/commit/7f30c655c75568ae331ed0243578d91870f3f9c6 (I didn't test the stable release).

Thanks for looking into it. I'm happy to close the issue, but will defer to you in case you want to leave it open until fixed in a release.

**Comment by ifreund** [comment]
Thanks for testing!

Yeah, I like leave stuff like this open for visibility until updating the wlroots dependency.

**Comment by ifreund** [comment]
River now depends on wlroots 0.17 :)
