### ISSUE TITLE
river fails to build on arch linux

### ISSUE THREAD

**Issue by user5815** [riverwm/river#879]
Building river on arch with zig 0.11, llvm 16, clang 16, and lld 16 causes the build to fail. Downgrading to the previous versions fixes the issue.
```
/home/user/.cache/paru/clone/river-git/src/river/deps/zig-wayland/src/scanner.zig:615:48: error: extra capture in for loop
            for (interface.requests) |request, opcode| {
                                               ^~~~~~
/home/user/.cache/paru/clone/river-git/src/river/deps/zig-wayland/src/scanner.zig:615:48: note: run 'zig fmt' to upgrade your code automatically
/home/user/.cache/paru/clone/river-git/src/river/build.zig:17:19: error: no field or member function named 'standardReleaseOptions' in 'Build'
    const mode = b.standardReleaseOptions();
                 ~^~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/zig/std/Build.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
referenced by:
    runBuild__anon_7166: /usr/lib/zig/std/Build.zig:1639:37
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
==> ERROR: A failure occurred in package().
    Aborting...
error: failed to build 'river-git-0.3.0_dev.r19.g6c7586e-1': 
error: packages failed to build: river-git-0.3.0_dev.r19.g6c7586e-1
```

**Comment by NickHastings** [comment]
The README.md states that Zig 0.10 is required.

**Comment by user5815** [comment]
hmm that is true. Maybe I just have to find a good way to keep zig 0.10 on arch for now. Currently it is only available through cache or the package archive since the repos have already upgraded to 0.11

**Comment by NickHastings** [comment]
If you want to use zig 0.11 you could try the next-zig branch of river.

**Comment by Doclic** [comment]
> hmm that is true. Maybe I just have to find a good way to keep zig 0.10 on arch for now. Currently it is only available through cache or the package archive since the repos have already upgraded to 0.11

I made [a Zig 0.10.1 AUR package](https://aur.archlinux.org/packages/zig-0.10-bin) if you want to compile `master`

**Comment by user5815** [comment]
I just noticed and installed it yesterday :D
