### ISSUE TITLE
Stuck when exit river 

### ISSUE THREAD

**Issue by minizilla** [riverwm/river#881]
<img width="1115" alt="Screenshot 2023-09-19 at 05 48 20" src="https://github.com/riverwm/river/assets/20436235/06c5ea26-2049-478b-bdbe-ce5eb1d523a2">

Either `riverctl exit` or `reboot` resulting in above screen and stuck.

**Comment by ifreund** [comment]
This issue needs more information, in particular a full log of river's output to stderr would be useful.

**Comment by sboysel** [comment]
@minizilla just to confirm, is `seatd` running? e.g. `systemctl status seatd`

**Comment by ifreund** [comment]
I'm just going to close this issue actually due to lack of information/reproducibility but will reopen if the original reporter or anyone else who's seen this is able to provide more information.
