### ISSUE TITLE
Keyboard layout switching with Super+Space doesn’t work

### ISSUE THREAD

**Issue by akho** [riverwm/river#882]
I’m setting my keyboard layout with

```
riverctl keyboard-layout -options 'grp:win_space_toggle' 'us,ru'
```

With this option, Super+Space should switch between us and ru keyboard layouts. In river, the combination is passed to the client, so usually it just prints a space.

This is the standard layout switch mapping across GNOME, Windows, and macOs in as much as it has a Super key )

**Comment by flub** [comment]
The default configuration does bind that key combination to toggling floating of windows.  Are you sure you're not already using this key combination in your configuration?

**Comment by akho** [comment]
> The default configuration does bind that key combination to toggling floating of windows. Are you sure you're not already using this key combination in your configuration?

No, I’m not using it.

**Comment by ifreund** [comment]
I can't reproduce this issue, can anyone reproduce this on river's master branch?

**Comment by akho** [comment]
Hello,

I can not reproduce it anymore, too; I think this should be closed.

Sorry for the trouble.

**Comment by ifreund** [comment]
No worries, thanks for testing again!
