### ISSUE TITLE
Float rule doesn't work

### ISSUE THREAD

**Issue by i34sti1337** [riverwm/river#883]
No matter if I add
riverctl float-filter-add "Pcmanfm"
riverctl float-filter-add -app-id "Pcmanfm"
or 
riverctl rule-add float "Pcmanfm"
riverctl rule-add float -app-id "Pcmanfm"

it does not make the window float
what works is toggle-float

**Comment by novakne** [comment]
Which version of river do you use?
for 0.2.4 you need to use: `riverctl float-filter-add app-id "<app-id>"` (no `-` before `app-id`)
for > 0.2.4 then this is `rriverctl rule-add float -app-id "<app-id>"`

And are you sure that is the right app-id for pcmanfm?

**Comment by i34sti1337** [comment]
You're right it works without the " - " In the example init it says -app-id so i was confused, thank you for the answer novakne.
