### ISSUE TITLE
some advice

### ISSUE THREAD

**Issue by superiums** [riverwm/river#884]
i'm new to river, come from sway & wayfire.
in my opinion, river has great thought about window organization (Tags, main Layout,etc).
but still, river was lack of most common features for wm.

## window control
this is the main job for wm. 

### status
every window/view has lots of status which we have to handle:
**For ALL**
- Tiling/Floating
- Tags
- Normal/Fullscreen
- size
- in which output

**For Tiling**
- main or secondary
- order

**For Floating**
- pix position
- snap position
- always Top or not

### Need to do
as i see, every config in river was done by command.
so, why not manage all window status by command? to do so, we have two things to do:
- print out all status by command. just like `swayms -t get_tree`
- set status by command. just like `for_window` did in sway config.
By these two step, river will be great enhanced, for it's full-circled and programable.

there're serial ways to do this.
1. sign status by params while lauch the view/window.
2. listen view/window create_event and apply the status setting.
3. sign status by command at any time neccessary.
4. maintain a list of every status, such as floating_filter . (I don't think its the best way, for it's only proterties of one view, if collecting it in another list, it's not so efficiant.  only ssd/csd_filter is good)

### identifier
additionaly, we have to give every window/view an ID to handle its status. the ID could be like this `$app_id$number`.
also, we should allow search ID by title, or app_id.
currently, the identifier in `riverctl rule` is app_id/title`, but sometimes we need wildcard for it.

## window search
image a situation, if we have tens of windows/views, we can't rememger the tags for every window/view. so how could we focus the destination view ? had to loop all tags ?

in waybar-wlr-taskbar we could have an icon, but when click, only the views in current focused tag could be focused. (in sway, the corresponding workspace could also be changed by click.)

## resize/move in tiling
1. currently , resize in tiling will set floating automaticly. but how about to add another function which resize and keep tilling ? 
seems only main view in tilling could be resized.
2. how about to add a drag to switch in tilling, just like sway do.

**Comment by superiums** [comment]
the following status may be configed as a bit number to simplify the handle:

Tiling/Floating
Normal/Fullscreen
main or secondary
snap position
always Top or not

**Comment by ifreund** [comment]
This is not a productive use of the issue tracker which should be reserved for bug reports and concrete, actionable items.

This kind of discussion belongs on IRC.
