### ISSUE TITLE
Allow dragging outputs to another monitor

### ISSUE THREAD

**Issue by Lassebq** [riverwm/river#896]
I have two monitors eDP-1 and HDMI-A-2
I want to move a window from eDP-1 to HDMI-A-2.

Unless there's a command I missed, I don't think there's currently a way to move windows between monitors.
I have two suggestions about implementing it:
- Add a dispatcher which moves focused output to the currently active tag on the specified screen
- Allow dragging a floating window between outputs without "hitting" the edge between screens.

**Comment by ifreund** [comment]
There is a command, `riverctl send-to-output`.

I don't have any plans to support dragging floating window between outputs currently.

**Comment by Lassebq** [comment]
That's for tags, huh? First tag on the second monitor has no relation to the first tag on the first monitor. Sending to output will only send to another output on current monitor

**Comment by Lassebq** [comment]
Nevermind.

**Comment by Aproxia-dev** [comment]
not even on the backburner? damn... this is currently the main thing keeping me away from using river and seeing it shrugged off entirely like that hurts quite a bit.

it's a part of my workflow, i want to be able to do everything i do regarding window management with my left hand on the left half of the keyboard, and my right hand on either the right side of the keyboard or the mouse. as you can imagine, this is preventing me from just moving a window to the other monitor with my mouse freely as i'm so accustomed to, and i don't even have any keys left available on my left side of the keyboard, so i just have to take my hand off the mouse just for a quick keybind for something that i can do with just the mouse on any other wm/wc.

would it really be that difficult to just add a setting to disable the windows hitting the edges of the outputs?
