### ISSUE TITLE
Issue: Playing videos in fullscreen and switching tags causes browser to reenter fullscreen with animation

### ISSUE THREAD

**Issue by Anachron** [riverwm/river#900]
When I open a video in my browser, for example `Firefox` and then play a video and put it on fullscreen (`F11`), then switch from the tag and back to it, the browser displays the "resize to fullscreen" animation again.

Edit:
To specify: Lets say I put the video on fullscreen and then switch away and back to it.
Firefox now returns to the fullscreen (with animation), but the video is not fullscreen anymore, only the browser/page

**Comment by ifreund** [comment]
Fixed in 642f9b7ae0b5fd55d7b677640f9df1e1f6bc4a42
