### ISSUE TITLE
Window never shows up with no monitor connected

### ISSUE THREAD

**Issue by barribarrier** [riverwm/river#906]
When launching any program while there is no monitor plugged in, river will not show the window after plugging a monitor back in.

How to reproduce:
PS: Make sure you have `eglgears_wayland` installed. Or just replace it below with any program.
1. Save this script as `run.sh`
```bash
#!/bin/bash

sleep 15 && WAYLAND_DISPLAY=wayland-1 eglgears_wayland &

river -log-level debug
```
2. Switch to any tty
3. Run it
```bash
/bin/bash run.sh
```
4. Unplug your monitor (or turn it off completely)
5. Wait 15 seconds
6. Turn monitor back on
7. `eglgears_wayland` is not visible (You can see its actually running with `ps -ef`, but not visible)

I tried `focus-view` `focus-output` `send-to-output` commands but didn't manage to make it visible.
It looks like it only happens when using tty. Running `river` in a nested Ubuntu Wayland session didn't cause this problem.

river version: 0.3.0-dev.151+927dceb

**Comment by ifreund** [comment]
Should be fixed by 69b61602cfa8ee5afd2a03748005e17eebeb6919, thanks for the report!
