### ISSUE TITLE
Focus tag to which view was set

### ISSUE THREAD

**Issue by jbirnick** [riverwm/river#911]
I want to implement the following behavior: When I do Super+Shift+2 on a window, I want that *both*
- the window is "moved to that tag" (i.e. `set-view-tags 00010`)
- this tag is focused (i.e. `set-focused-tags 00010`)

Is it possible to implement this somehow?
As far as I can see, right now one can only map a single command to a key...

**Comment by Leon-Plickat** [comment]
Write a script:

```sh
#!/bin/sh
riverctl set-view-tags $1
riverctl set-focused-tags $1
```

and bind it to a key

```sh
riverctl map normal Super+Shift W spawn "script.sh 00010"
```
