### ISSUE TITLE
How to find app-id

### ISSUE THREAD

**Issue by jbirnick** [riverwm/river#914]
One can make windows float by default using `riverctl float-filter-add app-id "[some app id]"`, but how do I find the app id of an application?

If there is no way, could you add a subcommand to `riverctl` to get a list of all windows and their properties?

**Comment by itshog** [comment]
You can use something like [lswt](https://git.sr.ht/~leon_plickat/lswt), which has the benefit of working also on other Wayland compositors. It's even listed in the [wiki](https://github.com/riverwm/river/wiki/Recommended-Software#other) under "Recommended Software".

**Comment by jbirnick** [comment]
Thanks!
