### ISSUE TITLE
add outer padding for floating views

### ISSUE THREAD

**Issue by charbelnicolas** [riverwm/river#918]
I know there is an alternative to rivertile called rivercarro with a monocle layout but it would be nice to not have an extra process running and be able to have an outer-padding for a nice and simple default monocle layout.

As it is right now, you can disable rivertile but then you don't get any outer-padding (gaps).

**Comment by charbelnicolas** [comment]
Hi @Leon-Plickat I don't know if I made myself clear on the feature request, maybe you misunderstood what I was meaning to say...

**Comment by Leon-Plickat** [comment]
Reading your title, I was under the impression that you wanted a way to change the outer gaps of rivertile live without restarting it and I updated the title accordingly. However, re-reading your issue makes me believe there is some confusion w.r.t. how layouts in river work. I would appreciate if you'd re-phrase your idea so I know what feature you are requesting.

**Comment by charbelnicolas** [comment]
You know that if you comment out the rivertile init file commands you practically end up with a non-tiling, stacking (monocle) window manager right? There is no rivertile process running at all.

This is straight from the river wiki:

_If no layout generator is active for the current output, river will fall back to floating window management. River is perfectly usable in this floating mode, thanks to the move, resize and snap commands_.

When I don't use rivertile, I lose the ability to have an outer padding. It would be nice if the outer padding setting was with riverctl and not with rivertile for us that don't like tiling or have no real use for it.

This is one of the last 'issues' I'm having when making the switch from awesome wm to river as my daily driver.

Like I said before, I know there is already a rivertile fork called rivercarro but I'd rather just have one less process running.

Less is more! It's not a coincidence I'm using river and not hyprland.

**Comment by Leon-Plickat** [comment]
So you run river without a layout and want floating windows to still  have some padding to the output edges in response to the move, resize and snap operations? I kinda doubt that will be accepted.

The place to implement this would be river b.t.w., not riverctl.

> [...] but I'd rather just have one less process running. Less is more!

Don't overdo it on the (perceived) minimalism, it gets you basically nothing and is not a healthy path to go down.

**Comment by charbelnicolas** [comment]
Yes I know river is the place this would be implemented in but riverctl is the command that would control it, that's what I meant by that.

As for the process, one more or one less doesn't really make a difference to me, but since river by default is useable without any layout generator it made sense to just add the padding by default too.

I've never understood why people prefer tiling as default instead of monocle, all the window splitting and resizing just invites for more glitchy behavior and rounding errors when calculating window sizes (as it certainly happens with foot terminal with certain padding and border sizes).

It was worth the try but as you already mentioned, its probably in the developers best interest to keep layout stuff separate from the main river process.

As it is right now I just spawn a single window for every tag to keep it simple.

**Comment by novakne** [comment]
>  As for the process, one more or one less doesn't really make a difference to me, but since river by default is useable without any layout generator it made sense to just add the padding by default too.

But padding/gaps is part of tilling, imo it doesn't make sense to have it for floating windows, it really seems your problems would be fixed just by using rivercarro. A point that makes river is great is that layouts are not handled by river and so it's easy for everyone to just use or make what they like.

> I've never understood why people prefer tiling as default instead of monocle, all the window splitting and resizing just invites for more glitchy behavior and rounding errors when calculating window sizes (as it certainly happens with foot terminal with certain padding and border sizes).

I'm curious to see how you get problems like that, are you talking about the content inside foot? Frame perfect is something really important to river, and rounding errors should not happens in well written layout generator like rivertile.
I never saw problems like that and I spend 99% of my time in foot.

**Comment by charbelnicolas** [comment]
In any case it would have made more sense for rivertile itself to have the monocle layout and not having to download another package with duplicate functionality but I can also understand why it's not something you'd put in a "tiling" layout generator if you don't care for it. Maybe you could change rivertile's name to riverlayout :)

**Comment by Leon-Plickat** [comment]
rivertile isn't meant to support every use case. It's feature set is kept sparse on purpose. It is a reference implementation; Most users are expected to use a third party layout.
