### ISSUE TITLE
Allow a program to steal focus

### ISSUE THREAD

**Issue by amarakon** [riverwm/river#920]
I am trying to use the [warpd](https://github.com/rvaiya/warpd) program, which is a keyboard driven virtual pointer. It allows me to move the mouse pointer anywhere on screen with a short keybinding. Unfortunately, it cannot move the pointer in such a spot where there is a window that isn't focused. It can only move the pointer within the focused window. Is it possible for me to make an exception for this program to allow it to steal focus and move the pointer anywhere it wants?

**Comment by Leon-Plickat** [comment]
There is no such thing as focus stealing, that is an X-ism. On river focus order follows well-defined rules. The warpd surface already gets keyboard focus as intended.

When the warpd surface is focused, the currently focused window gets unfocused. If you close warpd, river remembers the previously focused window and focuses it again. If you have pointer warp enabled, river will warp the pointer back to that window. Disable pointer warp and warpd works fine.

I am unconvinced that how warpd implements its functionality under Wayland is the correct way, so this really isn't a river issue.
