### ISSUE TITLE
No window borders in Mozilla windows.

### ISSUE THREAD

**Issue by jbirnick** [riverwm/river#921]
I use river `0.3.0-dev.155+50ccd4c` on Arch via the `river` package. (Yes the latest `river` package ships `0.3.0-dev.155+50ccd4c` even though it says `2.4` on the website. That's because river `2.4` doesn't build with the newest zig...

The issue: For Firefox and Thunderbird, I don't have any window borders.

Note: I use `MOZ_ENABLE_WAYLAND=1`.

**Comment by Leon-Plickat** [comment]
This is a change in how river handles decoration preferences of clients. To get a border around firefox and thunderbird, find out their app-ids and create ssd rules.

**Comment by jbirnick** [comment]
Oh sorry. I didn't notice this since there is not yet a changelog for river 0.3 (is there?)... (I never wanted to upgrade to 0.3 already, I was forced by the Arch package...)

**Comment by Leon-Plickat** [comment]
There is no river 0.3 release yet, but here are some of the changes: #796
