### ISSUE TITLE
Add a way to query the current monitor name and current window geometry

### ISSUE THREAD

**Issue by hillosipuli** [riverwm/river#926]
Allow querying the current monitor (or info about monitors in general) and current window.

I have a screenshotting script that on Hyprland used `hyprctl -j monitors` and `hyprctl -j activewindow` with a bit of parsing to get the currently selected monitor and currently select window location and size. That was quite useful as I could just have
` grim -o "$(hyprctl -j monitors | jq --raw-output '.[] | select(.focused) | .name')" - | wl-copy` to screenshot only the current monitor and `grim -g "$(hyprctl -j activewindow | jq --join-output '"\(.at.[0]),\(.at.[1]) \(.size.[0])x\(.size.[1])"')" - | wl-copy` to take capture only the current window.
There doesn't seem to be any way at the moment to get that information out of River since, as far as I know, that info is only available to the compositor and riverctl doesn't seem to provide any way to get that.

**Comment by Leon-Plickat** [comment]
> current monitor

Already possible

> current window

You can get the title.

> I have a screenshotting script [...]

However. Querying widow dimensions is arguably the wrong way to implement per-window screenshots. A proper solution is a new screencopy protocol. That will come eventually and we should not be complacent with such hacks in the meantime. Policy over mechanism.
