### ISSUE TITLE
leverage wlroots scene graph linux dmabuf feedback helper

### ISSUE THREAD

**Issue by ifreund** [riverwm/river#931]
As of wlroots 0.17, the scene graph API has a dmabuf feedback helper: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3726

**Comment by MaxVerevkin** [comment]
What exactly do you mean by "support"? If I understood correctly, wlroots now provides a way to customize dmabuf feedback, but what do we want to customize? Or maybe I misunderstood the feature.

**Comment by ifreund** [comment]
Yeah, "support" is the wrong word.

We want to leverage the new scene graph helper to send surface feedback with the correct output and render to make direct scanout more reliable.

**Comment by ifreund** [comment]
Done in 28dcd8320ac478a9aba36da7e261bc676a5a723e
