### ISSUE TITLE
Screen sharing stopped working for Firefox

### ISSUE THREAD

**Issue by arnilo** [riverwm/river#934]
Hi, I am running Riverwm on Nixos 23.11. I have xdg-desktop-portal-wlr enabled and have been able to share screen using Google meet with Firefox before. However, for no obvious reason it stopped working. I have tried to test in different scenarios before reporting here.

1. Tested with Microsoft Teams meeting and was unable to share screen in Firefox
2. I also have Hyprland installed which I used to use before. With hyprland, screen sharing with Google meet in Firefox work as expected.
3. Also deleted the mozilla profile once to see if that solves the problem. Didn't help

Might be wrong but I assume either it is a xdg-portal-wlr or Riverwm issue given it worked on hyprland?

Steps to reproduce:
1. Regular Google meet call
2. Click on the share screen button
4. Click on allow on the firefox popup asking permission to share screen
5. The share screen option becomes grey and cannot be clicked anymore
6. Nothing happens.

Thanks a lot for the help. Please let me know if I can provide more info

**Comment by ifreund** [comment]
I don't think there's any way in which this can be a problem on rivers end. I suspect it is an xdg-desktop-portal-wlr configuration issue. Please refer to their troubleshooting guide: https://github.com/emersion/xdg-desktop-portal-wlr/wiki/%22It-doesn't-work%22-Troubleshooting-Checklist

**Comment by adamcstephens** [comment]
> Nixos 23.11.

From the release notes under breaking changes:

> xdg-desktop-portal has been updated to 1.18, which reworked how portal implementations are selected. If you roll your own desktop environment, you should either set xdg.portal.config or xdg.portal.configPackages, which allow fine-grained control over which portal backend to use for specific interfaces, as described in [portals.conf(5)](https://github.com/flatpak/xdg-desktop-portal/blob/1.18.1/doc/portals.conf.rst.in).

Perhaps this is the issue?

**Comment by arnilo** [comment]
Thanks. Will check the docs suggested
