### ISSUE TITLE
add screenshots in readme file

### ISSUE THREAD

**Issue by Heus-Sueh** [riverwm/river#936]
For users who are curious to try the river, but don't know what it looks like and don't know if it's worth it

**Comment by novakne** [comment]
See #702

**Comment by Heus-Sueh** [comment]
> See #702

I still think it would be cool to have screenshots even if it's not official but to show what the river could look like and thus attract more users to the project

https://www.reddit.com/r/unixporn/search/?q=river&restrict_sr=1

It would also be cool to have a gallery of rices made by the community like hyprland has the hall of fame
https://hyprland.org/hall_of_fame/

**Comment by Leon-Plickat** [comment]
The wiki is free to edit by everyone, so feel free to add screenshots.

There are a few screenshots at the very end of my [river setup article](https://leon_plickat.srht.site/writing/river-setup-guide/article.html). But in general river focuses more on UX than flashy UI, which is hard to show off in a screenshot.
