### ISSUE TITLE
swhkd support

### ISSUE THREAD

**Issue by foxjaw** [riverwm/river#940]
[swhkd](https://github.com/waycrate/swhkd), a wayland fork of `sxhkd` that works even in `x11` & `tty`. Currently using with i3/sway which invokes i3-msg/swaymsg to perform window actions.  

But on river it's quite different. [Documentation](https://github.com/riverwm/river/blob/master/doc/riverctl.1.scd) states that I must need to use riverctl's map action with a key.  

How do I invoke riverctl action without mapping to a key, so that I can control river with swhkd only ?  
### PS
I still haven't configured river. Just thinking about using it. Because there's no issue tracker here about swhkd, I thought of opening a discussion on this.

**Comment by Leon-Plickat** [comment]
I am pretty sure swhkd works by listening directly to evdev, meaning it should already work.

> How do I invoke riverctl action without mapping to a key, so that I can control river with swhkd only?

You can call any command you'd bind to a key directly, like so:
```sh
riverctl map normal Super S <command>
riverctl <command>
```

I feel obliged to mention however that there is no benefit to using swhkd over rivers keymap mechanism. Nothing is gained by adding another program that implements functionality already present in river itself.
