### ISSUE TITLE
Can't spawn something where the bar is

### ISSUE THREAD

**Issue by jbirnick** [riverwm/river#944]
I use `river` with `waybar`. `waybar` automatically gets permanent space by river, say on the top of the screen. `river` windows will only spawn below the bar. So far so great.

Now I use the notification daemon `dunst`. I want that notifications are displayed say on the very top right of the display.
The problem is, when I configure `dunst` to spawn notifications at the very top right, it will only be in the top right of the normal window area, i.e., still _below the bar_. But I want notifications to spawn really on the very top right, floating above the bar.

How I can I fix this?

**Comment by Leon-Plickat** [comment]
Check if dunst has a option for setting the exclusive zone. This should have three settings, one of which should do what you desire.
