### ISSUE TITLE
Xwayland requires wl_drm for hardware acceleration

### ISSUE THREAD

**Issue by praschke** [riverwm/river#957]
- (merged) [Xwayland: Implement linux_dmabuf v4 feedback support](https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/818)
- [Use linux_dmabuf v4 when available to get the DRM device](https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/968)
- [Implement DRI3 v1.3 and per-surface dmabuf feedback](https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/969)
- blocked by [xwayland: Create a xwl_gbm context for each available GPU](https://gitlab.freedesktop.org/xorg/xserver/-/issues/1380)

```
(II) Raising the file descriptors limit to 524288
(II) glamor: No eglstream capable devices found
(II) Missing Wayland requirements for glamor EGLStream backend
(II) glamor: 'wl_drm' not supported
(II) Missing Wayland requirements for glamor GBM backend
Failed to initialize glamor, falling back to sw
```

**Comment by praschke** [comment]
probably unrelated, it proceeds to segfault in `llvmpipe_is_format_supported`. this is with mesa 23.3.2.

nixos currently packages mesa 23.1.9 and removing wl_drm support on that version completely breaks opengl and vulkan.

**Comment by ifreund** [comment]
Yeah, I guess we should probably wait a little longer before dropping wl_drm. No big deal really, I just pushed a commit adding support back.

**Comment by ifreund** [comment]
Thanks for the convincing links :)
