### ISSUE TITLE
Add the ability to add new views to the bottom of the stack instead of the top

### ISSUE THREAD

**Issue by thom-cameron** [riverwm/river#965]
I'm currently working on a layout generator ([river-dwindle](https://gitlab.com/thom-cameron/river-dwindle)) to get the tiling behavior I like/am used to from other dynamic WMs. 

It has occurred to me now that the generator is almost fully working though that river still isn't behaving quite as I want. Spawning new views adds them to the top of the stack, shifting everything around on the screen. This is just as much a problem for me when using rivertile too. 

I'd love if the option to add new views to the bottom of the stack by default - rather than them always being added to the top - was added. For me at least, this would be more consistent with the "predictable behavior" design goal listed in the readme because most of the content on the screen would stay in the same place when a new view was created. 

I have tried to work around this within the layout generator by drawing the stack in reverse (i.e. from smallest to largest view), but there doesn't seem to be any way to replicate the "zoom" riverctl function when working like this, which is not something I really want to live without. 

Unfortunately I have no idea what I'm doing with Zig, so can't offer to contribute to this myself. This is purely a feature request. 

Thanks!

**Comment by MaxVerevkin** [comment]
I think you want `riverctl attach-mode bottom`.

**Comment by thom-cameron** [comment]
I do, thank you very much and apologies for not using my eyes properly! Closing the issue.
