### ISSUE TITLE
Issues with Mozilla Apps (Firefox)

### ISSUE THREAD

**Issue by jbirnick** [riverwm/river#967]
I recently had issues with Mozilla Apps, in particular Firefox. For example:

- My frame around Mozilla Apps has a darker color than it should be (and than it is for all other windows). I think this is because Mozilla Apps draw a shadow around their windows, and that darkens my frame.
- Recently, I had issues where I couldn't use my keyboard in Firefox. Then it just doesn't type when I hit the keyboard. I have to switch a little bit around my desktops and some windows and then go back to Firefox to make it work again.
- Sometimes Firefox also shows the behavior that I can't spawn any windows on the same desktop.

Note: I'm using native-Wayland Firefox, not xwayland.

**Comment by Scherso** [comment]
Same issue here, that shadow seems to be a GTK thing, acting as though firefox is native to GNOME.

**Comment by Leon-Plickat** [comment]
Are you on river master or on a stable release? There has been a few changes w.r.t. CSD vs SSD. My system right now Firefox does not draw a drop-shadow when using SSD.

> Sometimes Firefox also shows the behavior that I can't spawn any windows on the same desktop.

Maybe you have accidentally made the firefox window floating and the new windows just appear behind it? This happens to me sometimes on my laptop.

**Comment by jbirnick** [comment]
I'm using the Arch Package.
```
river -version
0.2.6
$ riverctl -version
0.2.6
```

Note that the shadow is very subtle. I think it's not as crazy as in 0.3 which I tried briefly when the Arch Package broke.

Here is a screenshot of Firefox:
![image](https://github.com/riverwm/river/assets/6528009/240078f5-28be-45b1-bbe5-8def7900854d)

Here is a screenshot of a normal Terminal:
![image](https://github.com/riverwm/river/assets/6528009/b22c75ee-60b0-4b58-8fdd-ef40c4d5908e)

Notice how the yellow frame of the Terminal is much brighter. You can also see the shadow of Firefox a little bit on the bottom left of my bar. It reality it's actually even more subtle than on the screenshots. (For whatever reason.)


Btw, the thing with that I can't type in Firefox, I think it happens when I click a link from some other application like a Terminal and then go to Firefox.

**Comment by Leon-Plickat** [comment]
Could you check if this is still an issue for you on river master?

**Comment by Scherso** [comment]
Have you done any configuration changes to achieve the lack of Gnome-like decorations? I don’t even have a border present on firefox at the moment.

**Comment by jbirnick** [comment]
@Scherso I don't think so. I didn't have a border in 0.3, but I have one in 0.2.6.

@Leon-Plickat I could check it if someone (ideally familiar with Arch) could tell me how to do this without messing up my operating system / package manager. Also, as noted above, a few months ago I had actually no border at all in the master branch, which is even worse.

**Comment by Leon-Plickat** [comment]
On Fri Feb 2, 2024 at 10:13 PM CET, Johann Birnick wrote:
> Also, as noted above, a few months ago I had actually no border
> at all in the master branch, which is even worse.

Nope, not worse, but working as expected. On master, the heuristics
river uses to decide SSD vs CSD changed slightly, causing many GTK
programs to default to CSD, including Firefox. You just have to add a
rule to your config to make those windows use SSD, if you so desire.

> @Leon-Plickat I could check it if someone (ideally familiar with
> Arch) could tell me how to do this without messing up my operating
> system / package manager.

River master depends on zig 0.11.0 and wlroots 0.17.1, both of
which are the versions packaged in the arch repos right now (note
that there is also the extra/wlroots0.16 package, which is an older
version of wlroots as a separate package for compatability with
older compositors, so you may have to install the main wlroots
package explicitly).

Then just git clone the repo and follow the build instructions in
the README.

**Comment by jbirnick** [comment]
Yeah but running the installation will overwrite the river binary etc. on my system, no?

**Comment by Scherso** [comment]
If you want to backup your installation simply use cp, ex. `cp ~/.local/bin/river ~/.local/bin/river.bak`

**Comment by jbirnick** [comment]
Executing `zig build -Doptimize=ReleaseSafe --prefix ~/.local install` didn't overwrite `/usr/bin/river`. Where is the binary?

**Comment by Scherso** [comment]
the binary should be in `~/.local/bin`, check it with ls.

**Comment by jbirnick** [comment]
Oh yeah makes sense. Alright so I tested everything and here is the report @Leon-Plickat. On the master branch without further configuration I have a dropshadow and no border at all. (As expected I guess). When I turn on SSD I have a border with full brightness (great) but still a dropshadow (not great).

**Comment by Leon-Plickat** [comment]
Considering that right now I am also using Firefox on river master without seeing that shadow, I suspect that the issue may lie with your Firefox. Can anyone else reproduce this?

**Comment by Scherso** [comment]
I resolved it, at least I think I did.

Follow this: [https://github.com/riverwm/river/wiki#how-do-i-disable-gtk-decorations-eg-title-bar](https://github.com/riverwm/river/wiki#how-do-i-disable-gtk-decorations-eg-title-bar)

and add `riverctl rule-add -app-id "firefox" ssd` to your configuration file.

![image](https://github.com/riverwm/river/assets/90007553/42a157f6-f204-4bd5-b6e6-b7cdd6cf9792)

**Comment by jbirnick** [comment]
@Leon-Plickat are you absolutely sure? It's very subtle. I have recorded a video of how it looks for me: https://youtu.be/4CtV_7QWk0w

**Comment by Scherso** [comment]
Here is two unfocused windows:

![image](https://github.com/riverwm/river/assets/90007553/9b94f125-6065-47af-8658-6c7e37452fe5)

**Comment by jbirnick** [comment]
I don't know where it comes from but there is definitely a difference in your screenshots. Switch between the two and look at the top right corner. Weirdly, it's both times Firefox in that corner so I guess the difference doesn't come from a dropshadow. Could you do the same thing as I did in video? (switching between a desktop with Firefox and a desktop with a non-GTK window) And then look at the bright parts on the side if there is any difference.

**Comment by Scherso** [comment]
What software do you use to screen record? I haven't been able to screen record at all.

**Comment by jbirnick** [comment]
OBS (Open Broadcaster Software) through PipeWire.

But you don't need to record it. Just look for yourself and tell us if there is a difference.

**Comment by Scherso** [comment]
[Here](https://streamable.com/cju3s2) is a link to a video of it. I ended up using `wf-recorder.`

**Comment by jbirnick** [comment]
Indeed there is no dropshow. Did you have one before you applied [this](https://github.com/riverwm/river/wiki#how-do-i-disable-gtk-decorations-eg-title-bar)?

**Comment by Scherso** [comment]
I don't think I've ever had a dropshadow, I do have a drop shadow on easyeffects, and I didn't have a border on firefox until I made it a rule to add ssd.

**Comment by ifreund** [comment]
This issue thread has been quite unfocused and I'm not convinced there is any problem with the behavior of river's master branch here. If someone is still experiencing something they believe to be a river bug using river's master branch please open a new issue containing the river version used and steps for me to reproduce it.
