### ISSUE TITLE
Windows that refuse to resize can get rendered outside the output boundary

### ISSUE THREAD

**Issue by Isti115** [riverwm/river#969]
There are certain windows, such as Firefox, that have a hard limit on their minimum width / height and refuse to become smaller. This results in them sometimes being pushed out of the boundaries of the output they reside on, like in the following example:

Screenshot:
![20240120_00h27m23s_grim](https://github.com/riverwm/river/assets/3758493/62889b3b-be59-4507-ad3a-2ab4b35714e5)

Photo:
![image](https://github.com/riverwm/river/assets/3758493/ea4b2896-9cae-4f2c-9e3e-55f4c37e1ec3)

River by default doesn't allow windows to appear halfway across monitors, floating windows are stopped at screen borders, which makes me feel like this is unintended behavior. (Layout generators can still place them there though, I found that out while trying to implement a custom scrolling layout generator, not sure whether that's desirable or not.) Should the window be cut off and have a part of it missing instead in this case?

**Comment by ifreund** [comment]
I think cropping windows to their output is the correct fix for this given river's current semantics with regards to multi-monitor support.

**Comment by justinesmithies** [comment]
I too using the latest from git have noticed this and also I'm not sure if this is related but I use rules for `mpv` to display at `position` the size of `dimensions` which works fine until I toggle full screen and then back. then I see the border is in the correct place and size but `mpv` is outwith that border ??

config for the rules is [here:](https://git.sr.ht/~justinesmithies/dotfiles/tree/master/item/.config/river/init#L209)

**Comment by ifreund** [comment]
This should be fixed by f0b0606e9f6a9ffe4a05d26269508d860a97fc13

> I'm not sure if this is related but I use rules for mpv to display at position the size of dimensions which works fine until I toggle full screen and then back. Then I see the border is in the correct place and size but mpv is outwith that border ??

@justinesmithies that sounds related to #807. I really need to get around to solving that one, it's the trickiest known bug currently.
