### ISSUE TITLE
[Feature Request] A way to get information about the current focused window and/or display.

### ISSUE THREAD

**Issue by Scherso** [riverwm/river#970]
I've been using river for a while, and recently decided I needed screenshot functionality. Screenshots work, however, I would love if there was a way for river to provide information about the current display that's focused (eg DP-1, DP-0), or the current window.

It is possible to get the current output device with sway and [grim](https://sr.ht/~emersion/grim/) along with a json parser like `dp`. Here is the command that is demonstrated in grim's readme.

```bash
grim -o $(swaymsg -t get_outputs | jq -r '.[] | select(.focused) | .name')
```

I'm not saying "if it's possible there, do it here", I'm just giving that as a reference, a way to just use a command to get information.

**Comment by novakne** [comment]
The way to do this in river is to use the river-status protocol or any protocol needed to get this information.

So for example you could use [river-bedload](https://git.sr.ht/~novakane/river-bedload), something like `river-bedload -print outputs | jq -r '.[] | select(.focused) | .name'` would probably give you the same output that sway here.

There is also [ristate](https://gitlab.com/snakedye/ristate) or [lswt](https://git.sr.ht/~leon_plickat/lswt) that you can check.

**Comment by Scherso** [comment]
oh thank you so much that's so useful

**Comment by masroof-maindak** [comment]
@Scherso I'm in the same boat, did you end up implementing the screenshot functionality?

**Comment by Scherso** [comment]
Yeah, sorry for responding late, @masroof-maindak 

I compiled [river-bedload](https://git.sr.ht/~novakane/river-bedload), and added the following to my config:

```bash
riverctl map normal None Print spawn 'grim -o "$(river-bedload -print outputs | jq -r ".[] | select(.focused) | .name")" - | wl-copy'
```
