### ISSUE TITLE
The user_command_tags not being called?

### ISSUE THREAD

**Issue by zgb124** [riverwm/river#972]
Hello,

I am trying to modify rivertile to use per-tag ratios. I think I have done it, but when I try to test my code, it does not look like the `user_command_tags` switch in the `layoutListener` function is ever executed, whereas the documentation says it should be, before receiving any user command.

Is it only me that is affected by this? Thanks

**Comment by ifreund** [comment]
You're probably binding river-layout-v3 at version 1 while you need to bind it at version 2 to receive that event.

**Comment by zgb124** [comment]
> You're probably binding river-layout-v3 at version 1 while you need to bind it at version 2 to receive that event.
> 
> See https://wayland.freedesktop.org/docs/html/ch04.html#sect-Protocol-Versioning

How does this happen, and what might I need to do in order to bind to version 2?

I think I am following the compilation instructions largely as-is, inside a fedora container, and then packaging the install folder:

```
dnf install -y xz git gcc wayland-devel wayland-protocols-devel wlroots wlroots-devel xorg-x11-server-Xwayland xorg-x11-server-Xwayland-devel libxkbcommon libxkbcommon-devel libevdev libevdev-devel pixman pixman-devel pkgconf-pkg-config scdoc
git submodule update --init
zig build -Doptimize=ReleaseSafe -Dxwayland --prefix /build/river/build-output/usr install
```

**Comment by novakne** [comment]
[Here](https://github.com/riverwm/river/blob/master/rivertile/main.zig#L386) you can see the version, as you can see rivertile use the v1, and also in [build.zig](https://github.com/riverwm/river/blob/master/build.zig#L122) you need to generate the right version too, which is the case here.
