### ISSUE TITLE
[0.3.0] Stopping gamescope make River crash

### ISSUE THREAD

**Issue by NogradThGin** [riverwm/river#973]
Hello.

I'm currently using River (0.3.0, r202, commit 69a51cadb41443103370247ac515f1067da4b932).
When I start any game or software through gamescope (Non AUR - from extra package repository) with this argument:
`gamescope --nested-width 3936 --nested-height 1107 --output-width 5120 --output-height 1440 --force-grab-cursor --rt --steam --expose-wayland vkcube -m wayland`
Every time I close the software, either is it properly, with Ctrl+C or with a `pkill -9`. It will automatically make crash River.

It doesn't happen with River 0.2.6 from official repository.

Distro: ArchLinux
wlroots: From official repository (0.17.1)
RAM: 32Gb
GPU: AMD Radeon 7900XTX (Mesa 24.1 from mesa-git repository)

Here is the log for river in debug mode:
[river.log](https://github.com/riverwm/river/files/14057565/river.log)

Here is my river config (in .log extension for GitHub, but it's my config):
[init.log](https://github.com/riverwm/river/files/14057577/init.log)

**Comment by vide0hanz** [comment]
Came here to confirm this. 

```
river -version
0.3.0-dev.202+69a51ca
```

**Comment by ifreund** [comment]
Should be fixed by 026c832ba142cb28e8c2224be3e74bb4656441a1, thanks for the bug report!

**Comment by alex-courtis** [comment]
Many thanks!
