### ISSUE TITLE
River performs arbitrary keystrokes when focusing a qutebrowser window 

### ISSUE THREAD

**Issue by Brixy** [riverwm/river#978]
```
0.3.0-dev.203+66f1881
linux
wayland
```

Hi guys!

Qutebrowser is my main browser.

When I change the focus-view from any other window to qutebrowser, river(?) performs multiple arbitrary keystrokes. For example there is an endless number of `1`s or `2`s in the browser's status bar or the browser just changes to the root level of the domain, e.g. from https://github.com/riverwm/river/issues to https://github.com.

I am not familiar with zig, but apparently this issue was introduced with https://github.com/riverwm/river/commit/66f1881a723a3a583ebf1d70d355593ca8d74607

**Comment by justinesmithies** [comment]
I too have just gone back to Arch Linux using the same as above and I get a load of `1` or `4` depending which window I move Qutebrowser to. It is started by simply focusing from say tag 2 to tag 1 or where ever Qutebrowser resides and it can only be stopped by pressing escape.
It does not happen in a terminal though ??

**Comment by bwbuhse** [comment]
This seems to happen to me in Discord... and Baldur's Gate 3? I haven't had it happen in any other programming.

`0.3.0-dev.203+66f1881` on Gentoo with Linux 6.7.3

**Comment by novakne** [comment]
There is a fix coming on [codeberg](https://codeberg.org/river/river/pulls/9)
