### ISSUE TITLE
Cursor does not warp to "zoomed" view with on-focus-change enabled

### ISSUE THREAD

**Issue by vide0hanz** [riverwm/river#983]
This is a tiny bug I happened to notice when experimenting with the zoom command. 

Steps to reproduce:

- `riverctl set-cursor-warp on-focus-change`
- `riverctl zoom` when focused on a view that isn't already on top.

You'll see that the view being zoomed receives focus but the cursor does not follow suit. However, if you call it again to exchange it with the second view in the stack (default behavior), the cursor finally warps.

Thinking this is a bug because it technically does not initially warp when the focus is changed in this context :)

**Comment by ifreund** [comment]
Actually, to be pedantic this is not a bug as keyboard focus isn't changed by a zoom command while focusing a view that is not at the top of the stack. The same view has keyboard focus before and after the command is run.

**Comment by ifreund** [comment]
I don't use `on-focus-change` though. If there is consensus among users of this feature that it's expected for the cursor to be warped in this situation I don't think it would be too difficult to implement.

**Comment by adamcstephens** [comment]
As a user of `on-focus-change` I expect the cursor to follow the window that has focus, even if that window moves. As was mentioned on IRC, in the current behavior moving the mouse just the slightest in this scenario will refocus the window under the cursor. 

To me the purpose of warping with `on-focus-change` is to prefer keeping the mouse on top of the focused window, which the is done slightly inconsistently in this behavior.

**Comment by ifreund** [comment]
Seems to be consensus here and on IRC that this is the expected behavior, especially if focus-follows-cursor is enabled. 

Implemented in 93b8bbc2fd8d0204f1dab164081b1aacc8a54cf6

**Comment by vide0hanz** [comment]
Much appreciated!
